### PR TITLE
Bump core & ocis commit IDs & core node version in CI

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
@micbar @wkloucek @fschade this is now just commit-IDs & PHP-node-version

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
LGTM if CI passes.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18824/24/1
The following scenarios passed on retry:
- webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:114

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublicManagement</strong> https://drone.owncloud.com/owncloud/web/18824/34/1
The following scenarios passed on retry:
- webUISharingPublicManagement/publicLinkIndicator.feature:110

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/18824/12/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
Please don't restart CI, if #5675 turns green we'll merge that one and it supersedes #5773

**Comment by pascalwengerter** [comment]
Closed as master has updated commit IDs and drone config now

**Pull request closed without merging**
