### PR TITLE
Move acceptance test cmd package.json => run_sh, delete unused branch name rules

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
- Move `test:acceptance:drone` command from package.json to tests/*/run.sh to avoid developer confusion
- Remove `develop*` and `release*` branch name rules in .drone.star to avoid duplicate CI runs on release branches

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
LGTM

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternalUsers1</strong> https://drone.owncloud.com/owncloud/web/18492/55/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
Please don't re-run CI, needs a rebase after #5703 is merged

**Comment by pascalwengerter** [comment]
Also updated Node to minimum version 14 since that blew up in the app release process (due to ODS minimum version bump) today and downgraded Node CI images to 14 since 16 is not considered production ready

**Comment by ownclouders** [comment]
Results for <strong>oC10iPhone1</strong> https://drone.owncloud.com/owncloud/web/18500/45/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:59

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/18500/39/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:363

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/18500/12/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:36

**Review by phil-davis — APPROVED** [review]

**Review by fschade — APPROVED** [review]
❤️

**Comment by kulmann** [comment]
Nice! 😍

**Pull request merged**
