### PR TITLE
Divide "Shared with me" view into pending, accepted and declined sections

### PR DESCRIPTION
**Pull request by elizavetaRa**
## Description
The "Shared with me" view shows 2 different lists for pending and accepted shares. On request user can see the declined files (clicking "show declined shares).

## Motivation and Context
General UX improvement: Motivate the user to accept or decline the shares through better overview of the statuses and highlighted pending section. 

## How Has This Been Tested?
UI test scenario: Sharing multiple files through one testing account with another
- test case 1: pending shares, 3 or less pending shares --> simple list of pending shares
- test case 2: pending shares, more than 3 shares --> "show all", "show less" option
- test case 3: no pending shares--> no pending shares list shown
- test case 4: no accepted shares--> "You are currently not collaborating on other people's resources" message shown, "show declined shares" option appears at pending shares
- test case 5: accepted shares exist--> list with accepted shares and option to show declined shares appears
- test case 6: no declined shares--> "No declined files found" message appears
- test case 7 declined shares exist --> list with declined shares shown on click of "show declined shares"

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## General view
Bildschirmfoto vom 2021-05-31 10-14-23

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>oc10-integration-notifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15842/

<p>


### webUISharingNotifications-shareWithUsers-feature-53.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-40.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-53.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingNotifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15842/

<p>


### webUISharingNotifications-shareWithUsers-feature-53.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-40.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-53.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15842/

<p>


### webUISharingAcceptSharesToRoot-acceptShares-feature-50.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15842/

<p>


### webUISharingAcceptShares-acceptShares-feature-100.png
  

### webUISharingAcceptShares-acceptShares-feature-135.png
  

### webUISharingAcceptShares-acceptShares-feature-16.png
  

### webUISharingAcceptShares-acceptShares-feature-203.png
  

### webUISharingAcceptShares-acceptShares-feature-235.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-110.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-131.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-143.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-15.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-158.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-267.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-299.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-31.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-315.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-357.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-366.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-397.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-50.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-90.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>oc10-integration-notifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15843/

<p>


### webUISharingNotifications-shareWithUsers-feature-53.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-40.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-53.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingNotifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15843/

<p>


### webUISharingNotifications-shareWithUsers-feature-53.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-40.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-53.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15843/

<p>


### webUISharingAcceptSharesToRoot-acceptShares-feature-50.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15843/

<p>


### webUISharingAcceptShares-acceptShares-feature-100.png
  

### webUISharingAcceptShares-acceptShares-feature-135.png
  

### webUISharingAcceptShares-acceptShares-feature-16.png
  

### webUISharingAcceptShares-acceptShares-feature-203.png
  

### webUISharingAcceptShares-acceptShares-feature-235.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-110.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-131.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-143.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-15.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-158.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-267.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-299.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-31.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-315.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-357.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-366.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-397.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-50.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-90.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait1-Notifications</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait1-Notifications</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>oc10-integration-notifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16040/

<p>


### webUISharingNotifications-shareWithUsers-feature-53.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-40.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-53.png
  


</p></details>
<details><summary>:boom: Acceptance tests <strong>oc10-integration-notifications</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait1-Notifications</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingFilePermission</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait1-Notifications</strong> failed. The build is cancelled...</summary>

**Comment by elizavetaRa** [comment]
@kulmann I rebased the pr but we again face the problem with updating the list by accepting/declining https://github.com/owncloud/web/issues/5263 We also updated the server to 1.7.0, so it could be a server problem.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait1</strong> failed. The build is cancelled...</summary>

**Comment by kulmann** [comment]
Hey @elizavetaRa, I already rebased to our current master and wanted to work on the PR in https://github.com/owncloud/web/pull/5314 (opened a new PR since I can't push to CERN repos) - what kind of changes did you apply, except for rebasing?

**Comment by kulmann** [comment]
Thank you for your contribution! We finished the PR in https://github.com/owncloud/web/pull/5814, closing this PR here as the functionality is in master now.

**Pull request closed without merging**
