### PR TITLE
Fix space readme

### PR DESCRIPTION
**Pull request by JanAckermann**
## Related Issue

- Fixes https://github.com/owncloud/web/issues/8937

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/35284/71/1
:boom: The oC10IntegrationApp2 tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/35284/67/1
:boom: The oCISSharingPublic3 tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/35284/69/1
:boom: The oCISTrashbinJourney tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/35284/68/1
:boom: The oCISUploadMove tests pipeline failed. The build has been cancelled.

**Review by kulmann — APPROVED** [review]
Works like it should... but I had to recreate the `.space` folder manually first.

Edit: steps to reproduce:
1. Edit description
2. Delete `.space` folder
3. Create a .txt or .md file within space
4. Right click "Set as space description"

Gets an error. It only works if I recreate the `.space` in between (after 2. and before 4.).

**Pull request merged**
