### PR TITLE
Show error message when accessing space via publik link that is disabled

### LINKED ISSUE #11721: Trying to access to a disabled shared space shows no feedback
## Describe the bug
When an anonymous user tries to access to a disabled shared space via link, the user is stuck in the password page.

There are a couple of things going on:
* The user is asked for a password, as if it's possible to access the disabled space.
* When the user enters the correct password, nothing happens. The user doesn't enter the space, but there isn't any error showing.

## Steps to reproduce
1. Create a new space
2. Share the space via link (include password protection). Copy / keep the link and the password.
3. Disable the space
4. Logout
5. Access anonymously to the space via the shared link
6. Enter the password when asked

## Expected behavior
An error is shown, something like "the target space is currently disabled", or just a generic "an error occurred" if we don't want to give details.

It might be better if we don't ask for the password knowing that the user won't be able to access, although it might be more complex.

## Actual behavior
Nothing happens. The user can't enter the space, and there is no feedback that indicates an error.

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

## Additional context
There is a request with a 404 in the network tab, and some errors in the browser's console.

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Related Issue

- Fixes #11721

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by kulmann — COMMENTED** [review]
Puhhhh... can you try implementing a unit test for this? `Shows an error message when in invalid state xyz` should really have a unit test any time in any scenario 🙈

**Comment by AlexAndBear** [comment]
@kulmann sure, I see what can be done. 

And/or should I add an e2e test for the disabled space scenario ?

**Comment by kulmann** [comment]
> @kulmann sure, I see what can be done.
> 
> And/or should I add an e2e test for the disabled space scenario ?

Not an e2e-test, because that's not a happy path. It would probably be much easier than writing meaningful unit tests... that's what my `Puhhhh...` was about 😅

**Review by kulmann — APPROVED** [review]
Thank you for going the extra mile with the unit test 🥇

**Pull request merged**
