### PR TITLE
[full-ci] [tests-only] Bump ocis commit id

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description
This PR bumps OCIS commit id to match the latest

## Related Issue

- part of: https://github.com/owncloud/QA/issues/731

## How Has This Been Tested?

- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/23472/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23472/tracing/alice-shares-file-to-brian-alice-2022-3-10-04-38-33.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23472/tracing/alice-shares-file-to-brian-brian-2022-3-10-04-38-41.zip 


</p></details>

**Comment by kiranparajuli589** [comment]
do we need `full-ci` here? I think we run bump PRs with `full-ci` on the title.

**Comment by SwikritiT** [comment]
> do we need `full-ci` here? I think we run bump PRs with `full-ci` on the title.

yes sorry, thank you for reminding

**Comment by ownclouders** [comment]
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/23481/69/1
The following scenarios passed on retry:
- webUITrashbinRestore/trashbinRestore.feature:279
- webUITrashbinRestore/trashbinRestore.feature:46

**Review by kiranparajuli589 — COMMENTED** [review]
lgtm :+1:

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
