### PR TITLE
[tests-only] [full-ci] bump ocis commit id

### PR DESCRIPTION
**Pull request by kulmann**
Bump ocis commit id

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISResharing2</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIOCISSharingBasic</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISResharing1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISResharing2</strong> failed. The build is cancelled...</summary>

**Comment by phil-davis** [comment]
@kulmann I cherry-picked the commit from #5184 (issue #5183 ) onto here. That let's PRs easily run "full-ci", disabling the `earlyFail` behavior of the UI test pipelines. That should make it easier to see all the test pipelines that fail here, and be able to adjust the expected-failures more easily.

**Comment by kulmann** [comment]
Superseded by https://github.com/owncloud/web/pull/5179

**Pull request closed without merging**
