### PR TITLE
[tests-only][full-ci] Skip tests on oCIS related to batch request

### PR DESCRIPTION
**Pull request by saw-jan**
## Description
Acceptance tests that does batch actions are skipped due to following issues in oCIS
https://github.com/owncloud/ocis/issues/3613, https://github.com/owncloud/ocis/issues/3612, https://github.com/owncloud/ocis/issues/3614, https://github.com/owncloud/ocis/issues/3616

## Related Issue
closes https://github.com/owncloud/web/issues/6796

## How Has This Been Tested?
- test environment: CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingFolderAdvPermsGrp</strong> https://drone.owncloud.com/owncloud/web/24991/40/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L92.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L93.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L94.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L95.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L96.png
  


</p></details>

**Review by pascalwengerter — CHANGES_REQUESTED** [review]
I'd like to discuss this with the web team before merging

**Comment by kulmann** [comment]
@saw-jan are the tests still flaky with most recent ocis? I didn't observe them failing during the (heave drone-load) last days to be honest. But I might be mistaken. Could you clarify?

**Comment by saw-jan** [comment]
> @saw-jan are the tests still flaky with most recent ocis? I didn't observe them failing during the (heave drone-load) last days to be honest. But I might be mistaken. Could you clarify?

Yeah, there's one today (https://github.com/owncloud/web/issues/6796#issuecomment-1118134821)
Since others have not appeared, I could not say anything. I will try to reproduce them.

**Comment by saw-jan** [comment]
@kulmann I retested them. They can fail intermittently.

**Comment by kulmann** [comment]
Related? https://github.com/owncloud/ocis/issues/3757

**Comment by saw-jan** [comment]
> Related? [owncloud/ocis#3757](https://github.com/owncloud/ocis/issues/3757)

Seems like it.
So we may not need to skip those tests if there will be a fix.

**Comment by saw-jan** [comment]
I think, we no longer need this PR, the latest oCIS has some possible fixes. Commit id bump is in progress (https://github.com/owncloud/web/pull/6946)

Closing here!

**Pull request closed without merging**
