### PR TITLE
[tests-only][full-ci] Remove duplicate functions to use middleware's

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description
Remove duplicate functions to use middleware's

## Related Issue

- part of: https://github.com/owncloud/web/issues/6111

## How Has This Been Tested?

- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPerm3</strong> https://drone.owncloud.com/owncloud/web/22475/65/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L60.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L61.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L62.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L63.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L64.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L65.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternal2</strong> https://drone.owncloud.com/owncloud/web/22475/60/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingInternalUsers-shareWithUsers_feature-L108.png
  

### webUISharingInternalUsers-shareWithUsers_feature-L158.png
  

### webUISharingInternalUsers-shareWithUsers_feature-L243.png
  

### webUISharingInternalUsers-shareWithUsers_feature-L319.png
  

### webUISharingInternalUsers-shareWithUsers_feature-L77.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPerm1</strong> https://drone.owncloud.com/owncloud/web/22475/63/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPermissionsUsers-sharePermissionsUsers_feature-L243.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternal1</strong> https://drone.owncloud.com/owncloud/web/22475/59/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingInternalGroups-shareWithGroups_feature-L19.png
  

### webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases_feature-L45.png
  

### webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases_feature-L63.png
  

### webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases_feature-L81.png
  

### webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases_feature-L99.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternal3</strong> https://drone.owncloud.com/owncloud/web/22475/61/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIResharing1-reshareUsers_feature-L198.png
  

### webUIResharing1-reshareUsers_feature-L214.png
  

### webUIResharing1-reshareUsers_feature-L91.png
  

### webUISharingInternalUsersSharingIndicator-shareWithUsers_feature-L17.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic2</strong> https://drone.owncloud.com/owncloud/web/22475/68/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicManagement-publicLinkIndicator_feature-L110.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic1</strong> https://drone.owncloud.com/owncloud/web/22475/67/1
The following scenarios passed on retry:
- webUISharingPublicBasic/publicLinkCreate.feature:190

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
