### PR TITLE
[Do not merge] Do not reload files list after resource has been created

### LINKED ISSUE #3184: Don't reload folder after create action
After creating the resource the reload is triggered. This leads to extra network calls and extends the time needed to wait when confirming rename. We need to drop this and adjust the state without doing the network call.

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
After a resource is created, it gets pushed into the files list, automatically selected or opened and in case of folders also scrolled to.

## Related Issue

- Fixes #3184

## Motivation and Context
Increase performance.

## How Has This Been Tested?

- test case 1: Create a folder
- test case 2: Create a file

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Open tasks:

- [x] Update sdk after https://github.com/owncloud/owncloud-sdk/pull/456#pullrequestreview-397120920

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIOCIS</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/9468/

<p>







</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIOCIS</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/9469/

<p>







</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIOCIS</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/9495/

<p>







</p></details>

**Comment by PVince81** [comment]
- [ ] BUG: scrollto doesn't work correctly, it seems to scroll down but the entry doesn't become visible

My steps:
1. Upload a lot of files into a folder
1. Scroll to the top
1. Now upload a file called "zzz.txt" with the purpose of having it appear at the end of the list

Expected result: scrolls to the bottom of the list
Actual result: scrolls down a bit but doesn't reach the bottom

Observed with both Chromium 81 and Firefox 75.0

**Comment by LukasHirt** [comment]
> BUG: scrollto doesn't work correctly, it seems to scroll down but the entry doesn't become visible

#3265 - I would not see this as a part of this PR

On another note: I removed the highlighting of folders after creation since this doesn't make much sense on smaller devices. There would make much more sense the scroll and then highlighting just with the colour and not actually opening the sidebar.

**Comment by PVince81** [comment]
Sadly the current approach now makes it look even more broken.

Before it was clear to the user that the page had reloaded, so it is ok if it doesn't scroll directly.
Now that the page doesn't reload, it sometimes feel like nothing has happened.

Let's schedule the scrollto fix directly for the next sprint.

**Comment by PVince81** [comment]
> There would make much more sense the scroll and then highlighting just with the colour and not actually opening the sidebar.

Agreed

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIOCIS</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/9507/

<p>







</p></details>

**Comment by PVince81** [comment]
As you like.

**Comment by LukasHirt** [comment]
Closing as this will be part of #4627

**Pull request closed without merging**
