### PR TITLE
refactor: rename permissions

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
Renames the permissions to match the new names coming from the server. Also renames the `Space` ability subject to `Drive` to go hand in hand with the server's naming convention.

Needs https://github.com/owncloud/ocis/pull/6391 to run properly.

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/36198/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/admin-creates-group-admin-2023-5-31-09-35-24.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/admin-creates-user-admin-2023-5-31-09-48-44.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/admin-deletes-group-admin-2023-5-31-09-36-31.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/admin-user-can-change-personal-quotas-for-users-admin-2023-5-31-09-43-14.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/admin-user-can-change-personal-quotas-for-users-alice-2023-5-31-09-43-15.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/admin-user-can-change-personal-quotas-for-users-brian-2023-5-31-09-43-17.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/assign-user-to-groups-admin-2023-5-31-09-46-34.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/create-space-from-folder-alice-2023-5-31-09-51-06.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/create-space-from-resources-alice-2023-5-31-09-52-15.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/delete-user-admin-2023-5-31-09-47-39.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/edit-groups-admin-2023-5-31-09-37-37.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/edit-panel-can-be-opened-via-quick-action-and-context-menu-admin-2023-5-31-09-49-49.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/edit-user-admin-2023-5-31-09-45-28.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/list-members-via-sidebar-alice-2023-5-31-09-41-00.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/logo-can-be-changed-in-the-admin-settings-admin-2023-5-31-09-34-19.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/multiple-spaces-can-be-managed-at-once-in-the-admin-settings-via-the-batch-actions-alice-2023-5-31-09-39-52.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/spaces-can-be-managed-in-the-admin-settings-via-the-context-menu-alice-2023-5-31-09-38-45.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/unstructured-collection-of-testable-space-interactions-alice-2023-5-31-10-02-17.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/user-group-assignments-can-be-handled-via-batch-actions-admin-2023-5-31-09-44-23.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/user-login-can-be-managed-in-the-admin-settings-admin-2023-5-31-09-42-06.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/user-should-be-able-to-read-and-dismiss-notifications-alice-2023-5-31-09-55-23.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/user-should-be-able-to-read-and-dismiss-notifications-brian-2023-5-31-09-55-29.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36198/tracing/user-should-be-able-to-read-and-dismiss-notifications-carol-2023-5-31-09-56-31.zip 


</p></details>
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.

**Comment by kobergj** [comment]
@JammingBen ocis PR is merged. Bumping the commit id should make the tests green :+1:

**Comment by kobergj** [comment]
server problem. I missed one, sorry. https://github.com/owncloud/ocis/pull/6418

**Comment by JammingBen** [comment]
> server problem. I missed one, sorry. [owncloud/ocis#6418](https://github.com/owncloud/ocis/pull/6418)

Thx, I was just about to inform you about it 😄

**Review by JanAckermann — APPROVED** [review]

**Review by kulmann — APPROVED** [review]

**Review by lookacat — APPROVED** [review]

**Pull request merged**
