### PR TITLE
extension-sdk: Add a shared vite config for extensions

### PR DESCRIPTION
**Pull request by dschmidt**
## Description
Add a shared vite config file that can be used to develop external extensions.

## Related Issue

- #7930 

## How Has This Been Tested?

We ported
- https://github.com/dschmidt/web-app-gpx-viewer 
- https://github.com/cernbox/web-extensions -> top-bar extension

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/32686/75/1
:boom: The oC10IntegrationApp2 tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/32686/73/1
:boom: The oC10IntegrationNotifications tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/32686/74/1
:boom: The oC10IntegrationApp1 tests pipeline failed. The build has been cancelled.

**Comment by diocas** [comment]
Hi @dschmidt @kulmann , just a "small favour". I know this is not a very important PR, but it's also not that big nor changes the web code in a meaningful way..
So, do you think you could merge it today? This way I would avoid a fork to build our extensions.

**Review by kulmann — APPROVED** [review]

**Comment by kulmann** [comment]
@dschmidt do you still want to add anything to this PR or can it be merged?

**Comment by dschmidt** [comment]
Ok to merge I guess

**Comment by diocas** [comment]
Thank you all!

**Pull request merged**
