### PR TITLE
Prepare 4.7.0 release

### LINKED ISSUE #6160: Release 4.7.0
## Release checklist
- [x] pin release issue @pascalwengerter 
- [x] prepare release rc: @pascalwengerter
  - [x] create a branch `release-4.7.0` @pascalwengerter
  - [x] update the version in `packages/web-integration-oc10/appinfo/info.xml` @pascalwengerter
  - [x] update the version in `package.json` @pascalwengerter
  - [x] update the version in `sonar-project.properties` @pascalwengerter 
  - [x] move changelog/unreleased/* to changelog/VERSION_YYYY-MM-DD @pascalwengerter
  - [x] ~update the ocis commit id in `.drone.env` to the most recent one from ocis master~ skipped due to edge branch stuff
  - [x]  commit, push and create **draft** PR (#6159) for this branch @pascalwengerter
- [ ] create pre release tag `v4.7.0-rc1` from the release branch @pascalwengerter 
- [ ] smoke test 
  - [x] against oCIS @lookacat 
  - [x] against oc10 standalone @lookacat 
  - [ ] against oc10 as app installation @kulmann 
  - [ ] against oCIS wopi example / app provider @pascalwengerter
- [ ] if needed, fix issues or write down known issues 
- [x] update `YYYY-MM-DD` to current date in `changelog/VERSION_YYYY-MM-DD`
- [x] Make sure translations are up to date by updating them in Transifex and restarting translation sync job https://drone.owncloud.com/owncloud/translation-sync/ @pascalwengerter
- repeat above steps if a new rc is needed
- [x] Run translations sync job once again
- [ ] go to the releases section and click `Draft a new Release`. Use `v4.7.0` as a tag (the v prefix is important) and `4.7.0` as name and publish it
- [ ] ping in internal #btr channel to create a signed release and ask them to upload it to a) the github release page, b) marketplace.owncloud.com, c) portal.owncloud.com, d) customer.owncloud.com
- [ ] merge release branch https://github.com/owncloud/web/pull/6159 back to master (CI must be green)

### PR DESCRIPTION
**Pull request by pascalwengerter**
Fixes #6160

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21098/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublic1</strong> https://drone.owncloud.com/owncloud/web/21098/37/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by fschade** [comment]
LGTM, please pull in if https://github.com/owncloud/web/pull/6161 makes the ci green...

**Review by fschade — APPROVED** [review]
LGTM, please pull in https://github.com/owncloud/web/pull/6161 it it makes the ci green...

**Review by kulmann — APPROVED** [review]
👌

**Pull request merged**
