### PR TITLE
[docs-only] Fixes #4655 (link to developer manual in CONTRIBUTING.md)

### LINKED ISSUE #4655: Link to developer manual in contribution guides is broken
### Steps to reproduce
1. Think about contributing to this repository
2. Go to [the contribution guidelines](https://github.com/owncloud/web/blob/master/.github/CONTRIBUTING.md)
3. Click on the link to the [developer manual](https://owncloud.com/dev/) to further educate yourself

### Expected behaviour
I've done some research and perhaps [this page](https://owncloud.com/docs-guides/) was meant to be linked

### Actual behaviour
You find a 404 error page

### Server configuration
Non applicable

### Client configuration
**Browser:** Any

**Operating system:** Any

### Logs
Non applicable

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Changed the broken URL with my educated guess on where it should link to instead

## Related Issue
- Fixes #4655 

## Motivation and Context
Potential contributor onboarding

## How Has This Been Tested?
Needs confirmation that I've added the correct URL

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [X] Documentation improvement

### CODE REVIEW

**Comment by pascalwengerter** [comment]
AFAIK I couldn't complete the "Please set the following labels:" task since I don't have the necessary rights in the repository(?). Feel free to add them, of course!

**Comment by phil-davis** [comment]
Where to link to?

"Please read the [Developer Manuals][devmanual] to learn how to create your first application or how to test the ownCloud code with PHPUnit."

That sentence is not so relevant to the `web` app, it has a very different architecture to the ownCloud10 apps - certainly no PHPUnit! So we should rewrite that sentence.

**Review by kulmann — APPROVED** [review]
There is definitely much more broken about that .md file. Thanks for bringing this to our attention and already helping out, much appreciated! I will merge this for now, because it "makes things better" by fixing a non-existing url to something that at least exists. I will come up with a PR to make the md file more useful and link it to your issue, so that you'll (hopefully) get notified.

**Comment by pascalwengerter** [comment]
> There is definitely much more broken about that .md file. Thanks for bringing this to our attention and already helping out, much appreciated! I will merge this for now, because it "makes things better" by fixing a non-existing url to something that at least exists. I will come up with a PR to make the md file more useful and link it to your issue, so that you'll (hopefully) get notified.

@kulmann thanks, looking forward to an update (and also tomorrow's tech preview) and further contribution opportunities!

**Pull request merged**
