### PR TITLE
[tests-only][full-ci] Remove tests steps already present on middleware

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description
This PR removes the test steps present in the middleware and refactors the scenarios to match the test steps.

## Related Issue

- Part of: https://github.com/owncloud/web/issues/6111

## How Has This Been Tested?

- locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/21199/66/1
The following scenarios passed on retry:
- webUIMoveFilesFolders/moveFolders.feature:88
- webUIMoveFilesFolders/moveFolders.feature:81

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles2</strong> https://drone.owncloud.com/owncloud/web/21199/56/1
The following scenarios passed on retry:
- webUIFilesList/fileList.feature:61

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/21199/55/1
The following scenarios passed on retry:
- webUIFilesCopy/copy.feature:73
- webUIDeleteFilesFolders/deleteFilesFolders.feature:122

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/21199/53/1
The following scenarios passed on retry:
- webUISharingAcceptShares/acceptShares.feature:94

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic2</strong> https://drone.owncloud.com/owncloud/web/21199/65/1
The following scenarios passed on retry:
- webUISharingPublicManagement/shareByPublicLink.feature:152
- webUISharingPublicManagement/shareByPublicLink.feature:12
- webUISharingPublicManagement/shareByPublicLink.feature:67

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingAndUpload</strong> https://drone.owncloud.com/owncloud/web/21199/63/1
The following scenarios passed on retry:
- webUIUpload/upload.feature:34
- webUIUpload/uploadEdgecases.feature:94

**Comment by ownclouders** [comment]
Results for <strong>oCISRename</strong> https://drone.owncloud.com/owncloud/web/21199/52/1
The following scenarios passed on retry:
- webUIRenameFolders/renameFolders.feature:67
- webUIRenameFiles/renameFiles.feature:246
- webUIRenameFiles/renameFiles.feature:25
- webUIRenameFiles/renameFiles.feature:136

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternal3</strong> https://drone.owncloud.com/owncloud/web/21199/59/1
The following scenarios passed on retry:
- webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:139
- webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:42

**Comment by ownclouders** [comment]
Results for <strong>oCISBasic</strong> https://drone.owncloud.com/owncloud/web/21199/50/1
The following scenarios passed on retry:
- webUIPreview/imageMediaViewer.feature:60
- webUILogin/openidLogin.feature:38

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternal3</strong> https://drone.owncloud.com/owncloud/web/21316/59/1
The following scenarios passed on retry:
- webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:136

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21366/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by SwikritiT** [comment]
The failing tests are because of this issue https://github.com/owncloud/owncloud-test-middleware/issues/69 . After this issue is fixed the PR can be rebased and it should be green.

**Comment by Talank** [comment]
Blocked by https://github.com/owncloud/owncloud-test-middleware/issues/69

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublic1</strong> https://drone.owncloud.com/owncloud/web/21517/37/1
The following scenarios passed on retry:
- webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:11

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp1</strong> https://drone.owncloud.com/owncloud/web/21585/68/1
The following scenarios passed on retry:
- webUIPrivateLinks/accessingPrivateLinks.feature:17

**Comment by phil-davis** [comment]
Note: https://drone.owncloud.com/owncloud/web/21606/41/29
This is issue #6225 - probably needs to be fixed in the middleware. @SwikritiT is currently working on that.

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp1</strong> https://drone.owncloud.com/owncloud/web/21623/68/1
The following scenarios passed on retry:
- webUIPrivateLinks/accessingPrivateLinks.feature:17

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
