### PR TITLE
[tests-only][full-ci]Skip test on OCIS related to sharing

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description
This PR skips the tests that were linked to the following closed issues: 
- https://github.com/owncloud/ocis/issues/2260
- https://github.com/owncloud/ocis/issues/1277

The skipped tests are the ones that open the `Shares` folder using webUI check for resources or perform other actions. Since the implementation of `Share jail` the `Shares` folder is not available in `personal`, so this behavior is outdated for `OCIS` but relevant for `OC10`. Thus the tests are skipped in `OCIS` 
## Related Issue

- Follow up of:
   - https://github.com/owncloud/ocis/issues/2260
   - https://github.com/owncloud/ocis/issues/1277
 - https://github.com/owncloud/web/issues/6896
 

## Motivation and Context
Since we have decided that we won't be putting any effort into updating the Nightwatch tests, the tests that don't adhere with the current behavior of `OCIS` are skipped/removed. 

## How Has This Been Tested?

- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternal2</strong> https://drone.owncloud.com/owncloud/web/26741/61/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingInternalUsers-shareWithUsers_feature-L59.png
  


</p></details>

**Review by pascalwengerter — CHANGES_REQUESTED** [review]
@ScharfViktor please take a look if the approach suits you - I see the risk of deleting a lot of test cases that would be valid for oCIS also (but would need adaption since the share jail got merged)

**Comment by ScharfViktor** [comment]
> > @ScharfViktor please take a look if the approach suits you - I see the risk of deleting a lot of test cases that would be valid for oCIS also (but would need adaption since the share jail got merged)
> 
> I skipped these because I thought we were not going to update the tests in Nightwatch and these tests need to be updated in order for them to pass on Nightwatch for OCIS. I've mentioned the name of the scenario that is skipped in this PR here [#6896 (comment)](https://github.com/owncloud/web/issues/6896#issuecomment-1178668943) thinking that since the scenarios are already running in OC10 if we want to transfer it to playwright we can refer to the scenarios there. I can create a separate issue mentioning the complete scenarios skipped in this PR.

we agreed that we will not waste time for the old UI tests. we will close them but create a task to create new playwrigth tests

**Review by pascalwengerter — APPROVED** [review]
Fine with me then if @ScharfViktor is happy

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
