### PR TITLE
[tests-only][full-ci] Use incremental days for expiration date

### PR DESCRIPTION
**Pull request by saw-jan**
## Related Issue
Part of https://github.com/owncloud/web/issues/8151

## How Has This Been Tested?
- test environment: local

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
LGTM - see discussion in the issue for why we are doing this.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/30984/69/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicExpire-shareByPublicLinkExpiringLinks_feature-L11.png
  


</p></details>

**Comment by saw-jan** [comment]
> Results for **acceptance oCIS** https://drone.owncloud.com/owncloud/web/30984/69/1
> boom The acceptance tests failed on retry. Please find the screenshots inside ...

oCIS server doesn't accept date in this format `2023-01-07 00:00:00` (`yyyy-mm-dd HH:MM:SS`). Is it the expected one or a bug?

```diff
- datetime format invalid: 2023-01-07 00:00:00, parsing time "2023-01-07 00:00:00": extra text: " 00:00:00"
```

CC @phil-davis

**Comment by phil-davis** [comment]
The expiry date should just be a date `2023-01-07`. Expiry time is not supported. When the test code for the `Given` step calculates `+10` days, it needs to just get the date, and not append any time. This is a web test, so I guess the logic is in the nightwatch code somewhere.

**Comment by saw-jan** [comment]
> The expiry date should just be a date `2023-01-07`. Expiry time is not supported. When the test code for the `Given` step calculates `+10` days, it needs to just get the date, and not append any time. This is a web test, so I guess the logic is in the nightwatch code somewhere.

Yeah, the logic for getting the expiry date is in the test-middleware. Need to refactor there and probably release a new test-middleware version

**Review by dschmidt — APPROVED** [review]
Looks a little more brittle, as this has a potential race condition every midnight - but it's probably hard to hit, so fine with me

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
"Looks a little more brittle, as this has a potential race condition every midnight" - we have a lot of tests like this in various places (classic web UI, API tests...) that set some date +n days into the future and then check that the date is actually set to "+n" days in the future. There can be a slim chance of a fail if the scenario is run right before midnight and the system date changes between the execution of the When step and Then steps. I think that we just live with this.

Note: it is possible to fix this sort of thing - the test scenario would need to "decide" what "+10 days" "+5 days" etc is when it first comes to it, then remember that date and use that date in any later steps that mention that many days offset.

**Pull request merged**
