### PR TITLE
Merge stable-8.0 to master

### PR DESCRIPTION
**Pull request by JammingBen**
Ports `stable-8.0` to master.

### CODE REVIEW

**Comment by JammingBen** [comment]
@saw-jan @ScharfViktor There are changes in `.drone.star` and a new file `get-latest-ocis-commit-id.sh` coming from `stable-8.0`. Are they supposed to land in master as well?

**Review by kulmann — APPROVED** [review]
👍

**Comment by ScharfViktor** [comment]
> @saw-jan @ScharfViktor There are changes in `.drone.star` and a new file `get-latest-ocis-commit-id.sh` coming from `stable-8.0`. Are they supposed to land in master as well?

I see that PR is in the process https://github.com/owncloud/web/pull/10580

**Comment by JammingBen** [comment]
> I see that PR is in the process #10580

Meaning this PR would make https://github.com/owncloud/web/pull/10580 obsolete? Or are additional changed needed? I simply picked the commits from `stable-8.0`.

**Comment by saw-jan** [comment]
> > I see that PR is in the process #10580
> 
> Meaning this PR would make #10580 obsolete? Or are additional changes needed? I simply picked the commits from `stable-8.0`.

PR #10580 should not have anything different changes than stable-8. So, we can bring everything to the master. We were only waiting for keycloak-ocis thing to be fixed.

**Pull request merged**
