### PR TITLE
[tests-only][full-ci] Remove unused step definitions from generalContext

### PR DESCRIPTION
**Pull request by dpakach**
## Description
- use the server's app configuration steps from the middleware
- remove unused step definitions from the general context

## Related Issue

- part of #6111 

## How Has This Been Tested?

- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10iPhone3</strong> https://drone.owncloud.com/owncloud/web/21304/49/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21310/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/21436/40/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:106

**Comment by kiranparajuli589** [comment]
blocked due to https://github.com/owncloud/web/pull/6216#issuecomment-1010956488

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/22006/41/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:111

**Comment by phil-davis** [comment]
@kiranparajuli589 sorry about the conflicts. We just merged a few PRs by @SwikritiT 
I guess lines are edited in similar places in `Given` steps of scenarios.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic1</strong> https://drone.owncloud.com/owncloud/web/22249/64/1
The following scenarios passed on retry:
- webUISharingPublicBasic/publicLinkCreate.feature:190

**Comment by ownclouders** [comment]
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/22254/66/1
The following scenarios passed on retry:
- webUIUserJourney/journey1.feature:11

**Comment by phil-davis** [comment]
"This branch is 3 commits ahead, 35 commits behind master. "
https://github.com/owncloud/web/tree/update-steps-general-context

@kiranparajuli589 please rebase again. We need to be sure to have up-to-date CI.

**Review by SwikritiT — COMMENTED** [review]
LGTM

**Review by phil-davis — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternal3</strong> https://drone.owncloud.com/owncloud/web/22344/59/1
The following scenarios passed on retry:
- webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:17

**Pull request merged**
