### PR TITLE
[full-ci] Fix selectors for expiration dates and web container

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Fixed test selectors

Not too sure how the code changes handle the `undefined` scenario when getting the expiration date so opened a separate PR

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingInternalGroupsSharingIndicator-shareWithGroups-feature-136.png
  

### webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-124.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-17.png
  

### webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-118.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRoot2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-31.png
  

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-32.png
  

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-33.png
  

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-34.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRoot1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingInternalUsersToRoot-shareWithUsers-feature-129.png
  

### webUISharingInternalUsersToRoot-shareWithUsers-feature-142.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsToRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups-feature-167.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-179.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-245.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-315.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-316.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingAcceptShares-acceptShares-feature-218.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-379.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingInternalGroups-shareWithGroups-feature-182.png
  

### webUISharingInternalGroups-shareWithGroups-feature-196.png
  

### webUISharingInternalGroups-shareWithGroups-feature-271.png
  

### webUISharingInternalGroups-shareWithGroups-feature-349.png
  

### webUISharingInternalGroups-shareWithGroups-feature-350.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingFilePermission</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-60.png
  

### webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-61.png
  

### webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-62.png
  

### webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-63.png
  

### webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-64.png
  

### webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-65.png
  

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-61.png
  

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-62.png
  

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-63.png
  

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-64.png
  

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-65.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsers</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingInternalUsers-shareWithUsers-feature-141.png
  

### webUISharingInternalUsers-shareWithUsers-feature-350.png
  

### webUISharingInternalUsersCollaborator-shareWithUsers-feature-35.png
  

### webUISharingInternalUsersCollaborator-shareWithUsers-feature-36.png
  

### webUISharingInternalUsersCollaborator-shareWithUsers-feature-37.png
  

### webUISharingInternalUsersCollaborator-shareWithUsers-feature-38.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingFolderAdvancedPermissionMU</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-60.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-61.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-62.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-63.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-64.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-65.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-66.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-67.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-68.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-69.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-70.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-71.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingFolderPermissions</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-61.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-62.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-63.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-64.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-65.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-66.png
  

### webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-61.png
  

### webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-62.png
  

### webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-63.png
  

### webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-64.png
  

### webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-65.png
  

### webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-66.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPermissionsUsers</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingPermissionsUsers-sharePermissionsUsers-feature-100.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-101.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-102.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-103.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-104.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-122.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-123.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-126.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-156.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-157.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-158.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-161.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-179.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-22.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-37.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-53.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers-feature-69.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>ResharingToRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUIResharingToRoot-reshareUsers-feature-16.png
  

### webUIResharingToRoot-reshareUsers-feature-177.png
  

### webUIResharingToRoot-reshareUsers-feature-25.png
  

### webUIResharingToRoot-reshareUsers-feature-56.png
  

### webUIResharingToRoot-reshareUsers-feature-57.png
  

### webUIResharingToRoot-reshareUsers-feature-58.png
  

### webUIResharingToRoot-reshareUsers-feature-59.png
  

### webUIResharingToRoot-reshareUsers-feature-60.png
  

### webUIResharingToRoot-reshareUsers-feature-88.png
  

### webUIResharingToRoot-reshareUsers-feature-89.png
  

### webUIResharingToRoot-reshareUsers-feature-90.png
  

### webUIResharingToRoot-reshareUsers-feature-91.png
  

### webUIResharingToRoot-reshareUsers-feature-92.png
  

### webUIResharingToRoot-reshareUsers-feature-95.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingFolderAdvPermissionsGrp</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-61.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-62.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-63.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-64.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-65.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-66.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-67.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-68.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-69.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-70.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-71.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-72.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersExpire</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-104.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-105.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-108.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-134.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-211.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-228.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-34.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-100.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-126.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-203.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-220.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-30.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-96.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-97.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPermissionToRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16090/

<p>


### webUISharingPermissionToRoot-shareAdvancePermissionsGroup-feature-69.png
  

### webUISharingPermissionToRoot-shareFileWithMultipleUsers-feature-64.png
  

### webUISharingPermissionToRoot-shareFolderWithMultipleUsers-feature-65.png
  

### webUISharingPermissionToRoot-sharePermissionsFileGroup-feature-64.png
  

### webUISharingPermissionToRoot-sharePermissionsFoldersGroup-feature-65.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-112.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-113.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-116.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-144.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-145.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-146.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-149.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-157.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-17.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-32.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-47.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-62.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-91.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-92.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-93.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-94.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers-feature-95.png
  

### webUISharingPermissionToRoot-sharedFolderWithMultipleUsersAdvancedPermissions-feature-68.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16094/

<p>


### webUISharingAcceptShares-acceptShares-feature-218.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-379.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersExpire</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16094/

<p>


### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-228.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-220.png
  


</p></details>

**Review by kulmann — APPROVED** [review]
Cool 🥇

**Pull request merged**
