### PR TITLE
late deliver of accentuate new files tests

### PR DESCRIPTION
**Pull request by fschade**
## Description
To get #6020 into the sprint reviews we merged it early with core tests only.
To have a clean unit-test coverage some tests where missing and are included in this late PR.

Changelog is already delivered as part of #6020

## Related Issue
- Finalizes #6020

## Motivation and Context
Test all needed cases and edge cases

## How Has This Been Tested?
- jest

## Types of changes
- [X] Tests

## Checklist:

- [X] Unit tests added

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/20271/15/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:15

**Review by kulmann — COMMENTED** [review]
Could we move the `accentuatesTableRow` to a helper file, since you're using it in Personal and PublicFiles spec?

**Comment by fschade** [comment]
> Could we move the `accentuatesTableRow` to a helper file, since you're using it in Personal and PublicFiles spec?

good point, done

**Review by pascalwengerter — APPROVED** [review]
Restarted CI after a seemingly random failure (not being able to pull the `hugo` image for the docs), code LGTM

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/20292/15/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:15

**Pull request merged**
