### PR TITLE
Merge 7.1.2 release to stable-7.1

### PR DESCRIPTION
**Pull request by JammingBen**
Web `v7.1.2` is out (see https://github.com/owncloud/web/pull/9951), brings those changes to `stable-7.1`.

### CODE REVIEW

**Review by kulmann — APPROVED** [review]
👍

**Comment by kulmann** [comment]
Needs https://github.com/owncloud/web/pull/10051 to be merged first and then a rebase

**Comment by JammingBen** [comment]
> Needs #10051 to be merged first and then a rebase

Yep, the bigger issue is that the pipeline of the release ifself also isn't working 😬 https://drone.owncloud.com/owncloud/web/40575/2/2

**Comment by ScharfViktor** [comment]
@JammingBen  https://github.com/owncloud/web/pull/10051 is merged. please rebase

**Review by JanAckermann — APPROVED** [review]

**Pull request merged**
