### PR TITLE
[tests-only][full-ci]bump latest commit id

### PR DESCRIPTION
**Pull request by nabim777**
This PR bumps latest ocis commit id.
Part of https://github.com/owncloud/QA/issues/827

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/39080/20/13
```
Checking expected failures in /var/www/owncloud/web/tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
Error: Scenario webUIFiles/breadcrumb.feature:50 failed but was not expected to fail.
runsh: Total unexpected failed scenarios throughout the test run:
webUIFiles/breadcrumb.feature:50
```
I will restart CI to see if this is a flaky test.

**Comment by saw-jan** [comment]
`webUIFiles/breadcrumb.feature:50` looks like a hard failure. Also fails in ocis https://drone.owncloud.com/owncloud/ocis/27063/75/13

**Comment by PrajwolAmatya** [comment]
Multiple builds are currently failing on `webUIFiles/breadcrumb.fearure:50`.
Issue: https://github.com/owncloud/ocis/issues/7385

**Review by saw-jan — APPROVED** [review]

**Review by SagarGi — COMMENTED** [review]
is the change in `.drone.star` an deletion of another file `idnetifier-registration.yml` necessary? If so Why not mention in the PR description for it.

**Pull request merged**
