### PR TITLE
Add set password modal

### PR DESCRIPTION
**Pull request by JanAckermann**
## Related Issue

- Fixes https://github.com/owncloud/web/issues/6963

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by pascalwengerter — CHANGES_REQUESTED** [review]
The same check would have to happen in `FileLinks.vue` both for creating and updating links 😬

**Comment by JanAckermann** [comment]
@pascalwengerter 
is this a statement or a guess?

AFAIK we have those checks? 
image

**Comment by JanAckermann** [comment]
@pascalwengerter ok, but I think the issue ticket is not targeting this, will be done in the future, you might want to ping me after merge

**Comment by pascalwengerter** [comment]
> @pascalwengerter ok, but I think the issue ticket is not targeting this, will be done in the future, you might want to ping me after merge

Tobi's ticket is targeting this (or more like "what we spoke about in a call yesterday and which isn't clear in the ticket, namely update failures when changing roles via the dropdowns for links that would require a password for the new role"), your PR closes what is reported in https://github.com/owncloud/web/issues/6782. I'm fine with merging this PR, but we'd have to reopen #6963 again after merge with an updated description

**Review by pascalwengerter — APPROVED** [review]
I'm fine with merging now as code LGTM, we'll have to put more work into password-enforcement upon creating/updating links in the sidebar in the future though. Also, please squash-on-merge :)

**Comment by JanAckermann** [comment]
@pascalwengerter can we please open a new issue with detailed information please?

**Comment by pascalwengerter** [comment]
> > @pascalwengerter can we please open a new issue with detailed information?
> 
> Taking care of it now, thx

Lives in #6974 now

**Pull request merged**
