### PR TITLE
Bump ODS to 7.4.1

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
See PR title

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait1-Notifications</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>iPhone1-Notifications</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsSharingIndicator</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISSharingInternalUsers1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingFolderPermissions</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISSharingPermissions2</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISSharingInternalUsers1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Visual regression tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16513/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16513/

<p>


### webUIFilesDetails-fileDetails-feature-116.png
  

### webUIFilesDetails-fileDetails-feature-66.png
  

### webUIFilesDetails-fileDetails-feature-82.png
  

### webUIFilesDetails-fileDetails-feature-99.png
  

### webUIFilesList-fileList-feature-46.png
  


</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISSharingPublic</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIOCISBasic</strong> failed. The build is cancelled...</summary>

**Review by kulmann — APPROVED** [review]
LGTM 👍

**Pull request merged**
