### PR TITLE
fix: keyboard actions for deactivated resources

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
Prevents actions for disabled resources from being accessible via keyboard navigation. This is achieved by either disabling them (checkboxes) or hiding them (rename action, quick actions).

## Related Issue

- Fixes https://github.com/owncloud/web/issues/11335

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

### CODE REVIEW

**Review by AlexAndBear — CHANGES_REQUESTED** [review]
Unfortunately this disables the context menu in the tiles view for disabled spaces, actions like enable/delete life in there, and therefore should be accessible.

As you are already on it, the show members button will still be shown in the tiles view on a disabled space, clicking on that button opens the sidebar and ends in an endless loading animation. We might need to disable the show members button, but I think seeing members was possible on a disabled space, before switching to sharing ng 🤔

**Comment by JammingBen** [comment]
> Unfortunately this disables the context menu in the tiles view for disabled spaces, actions like enable/delete life in there, and therefore should be accessible.

Good catch, should be fixed now.

> As you are already on it, the show members button will still be shown in the tiles view on a disabled space, clicking on that button opens the sidebar and ends in an endless loading animation. We might need to disable the show members button, but I think seeing members was possible on a disabled space, before switching to sharing ng 🤔

IMO this is a server issue, listing members should be possible for disabled spaces. I'll create an issue in the oCIS repo for that 👍

**Comment by AlexAndBear** [comment]
Thank you, I took the opportunity, to disable the edit description action when space is disabled and don't load previews, since we don't have access to those files when disabled

**Review by AlexAndBear — APPROVED** [review]

**Review by AlexAndBear — CHANGES_REQUESTED** [review]
you commited some vitest files by accident

**Review by AlexAndBear — APPROVED** [review]

**Pull request merged**
