### PR TITLE
[tests-only] Change a unit test

### PR DESCRIPTION
**Pull request by phil-davis**
This is just a test to confirm what CI runs when I only change a unit test.

### CODE REVIEW

**Comment by ownclouders** [comment]
<summary>:boom: Acceptance tests <strong>oC10iPhoneNotifications</strong> failed. The build is cancelled...</summary>

https://drone.owncloud.com/owncloud/web/16717/42/1

**Comment by ownclouders** [comment]
<summary>:boom: Acceptance tests <strong>oC10Files2</strong> failed. The build is cancelled...</summary>

https://drone.owncloud.com/owncloud/web/16717/11/1

**Comment by ownclouders** [comment]
<summary>:boom: Acceptance tests <strong>oC10XGAPortrait1</strong> failed. The build is cancelled...</summary>

https://drone.owncloud.com/owncloud/web/16717/40/1

**Comment by ownclouders** [comment]
<summary>:boom: Acceptance tests <strong>oC10iPhone1</strong> failed. The build is cancelled...</summary>

https://drone.owncloud.com/owncloud/web/16717/43/1

**Comment by phil-davis** [comment]
There are some problems processing some steps of the acceptance tests when they need to be skipped. PR incoming...

**Comment by phil-davis** [comment]
Fixed in #5338

**Pull request closed without merging**
