### PR TITLE
Bump SDK to newer version

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
...

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>oC10SharingExternalRoot</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/web/16755/38/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>oCISTrashbinUploadMoveJourney</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/web/16756/60/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>oCISTrashbinUploadMoveJourney</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/web/16757/60/1

**Comment by pascalwengerter** [comment]
Closing this for now, we'll need to investigate the whole issue further and then bump the SDK to a (newer) version that work with `web`

**Pull request closed without merging**
