### PR TITLE
Fix v-image-source updates

### PR DESCRIPTION
**Pull request by dschmidt**
## Motivation and Context
Images loaded via v-image-source are not updated when the url changes.

## How Has This Been Tested?
I'm using it in web-app-ownbrander and it works this way.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/16820/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by phil-davis** [comment]
SonarCloud coverage fails because https://sonarcloud.io/organizations/owncloud-1/quality_gates/show/36668 the default "quality gate" requires that new/change code should have >50% coverage.

The SonarCloud CI result has not yet been made "Required". And unit tests are in the process of being added for all the code. So in this PR, I guess we ignore the SonarCloud result.

**Comment by dschmidt** [comment]
Fine with that obviously. I anyhow already asked on RocketChat if tests are required and how they should look like because currently the code is completely untested and unused as well (afaict). At least I could not find a single reference to v-image-source outside of the code itself. 🤷‍♂️

**Review by kulmann — APPROVED** [review]
Thanks for the fix :heart:

**Pull request merged**
