### PR TITLE
[tests-only][full-ci] test: bump latest commit id of ocis master

### PR DESCRIPTION
**Pull request by anon-pradip**
## Description

Bump latest ocis master commit id

## Related Issue

- Part of: https://github.com/owncloud/QA/issues/866

### CODE REVIEW

**Comment by anon-pradip** [comment]
> bump PR requires `full-ci` in the title

Oops! Sorry. I totally forgot about that :facepalm:

**Review by saw-jan — APPROVED** [review]

**Review by SagarGi — APPROVED** [review]
LGTM :+1:  Please rebase and resolve conflict.

**Review by amrita-shrestha — CHANGES_REQUESTED** [review]
update latest commit id

**Review by amrita-shrestha — APPROVED** [review]
ci passed so lgtm

**Comment by anon-pradip** [comment]
Ok. Thanks all. Merging this now

**Pull request merged**
