### PR TITLE
Fix typos in changelogs

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Fix some typos in changelogs.

I am mainly doing this to check that the CI logic in PR #5729 is working. The unit tests and acceptance tests should not be run, because this is a docs-only change.

## How Has This Been Tested?
N/A

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/19168/7/6
`ONLY DOCS FILES ARE CHANGED` - correct - good

**Comment by phil-davis** [comment]
In the 2nd commit, I adjusted some minor docs grammar that my IDE told me about. The CI should understand that there are still only docs changes in this PR, and skip running unit and acceptance tests.

**Review by pascalwengerter — APPROVED** [review]
LGTM

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/19171/6/2
ONLY DOCS FILES ARE CHANGED

That is correct - good.

**Pull request merged**
