### PR TITLE
[tests-only] bump ocis commit id

### PR DESCRIPTION
**Pull request by individual-it**
bump commit id of ocis to test with the most current version of ocis

blocked by https://github.com/owncloud/ocis/pull/1734

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
If it passes!

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13328/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>

**Comment by kiranparajuli589** [comment]
Lgtm ✌️

**Review by LukasHirt — APPROVED** [review]

**Comment by individual-it** [comment]
CI crashed again during user creation, hopping that https://github.com/owncloud/ocis/pull/1734 will make it more stable

**Review by dpakach — APPROVED** [review]

**Comment by individual-it** [comment]
added newest ocis commit id, lets see if CI got more stable

**Pull request merged**
