### PR TITLE
[tests-only] run unit and integration tests on tags

### PR DESCRIPTION
**Pull request by saw-jan**
## Description
run unit and integration tests on tags

## Related Issue
- Fixes https://github.com/owncloud/web/issues/5620

## How Has This Been Tested?
- test environment: 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsers</strong> https://drone.owncloud.com/owncloud/web/17961/25/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/17961/25/15
```
runsh: Total unexpected failed scenarios throughout the test run:
webUISharingInternalUsersShareWithPage/shareWithUsers.feature:91
runsh: There were no unexpected success.
```

That is the same test that failed in demo PR #5622 - that test seems to be failing now. Needs separate investigation about why it is failing.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsers</strong> https://drone.owncloud.com/owncloud/web/17963/25/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by phil-davis** [comment]
`webUISharingInternalUsersShareWithPage/shareWithUsers.feature:91` failed again, and I have restarted CI.

After the new release happens, we need to check again if that test scenario is still intermittent.

**Pull request merged**
