### PR TITLE
Add file picker mode

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
for testing add ?embed=true&embed-target=file&embed-extensions=txt
image

## Related Issue

- Fixes https://github.com/owncloud/web/issues/11052

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by AlexAndBear** [comment]
File click action will be done in the Open file PR

**Review by JammingBen — COMMENTED** [review]
The tiles view is still showing checkboxes in file picker mode. Other than that, LGTM.

Please don't forget to extend [the docs](https://owncloud.dev/clients/web/embed-mode/) though (maybe in a follow-up).

**Comment by AlexAndBear** [comment]
Check boxes are visible in target location as well. Can you check if this is on purpose (since not shown in usual files list)? If no, I can disable on both  targets

**Comment by JammingBen** [comment]
> Check boxes are visible in target location as well. Can you check if this is on purpose (since not shown in usual files list)? If no, I can disable on both targets

Then this is a bug for the location target as well 😬

**Comment by AlexAndBear** [comment]
> > Check boxes are visible in target location as well. Can you check if this is on purpose (since not shown in usual files list)? If no, I can disable on both targets
> 
> Then this is a bug for the location target as well 😬 

Then I'll just resovle it (:

**Comment by AlexAndBear** [comment]
> > Check boxes are visible in target location as well. Can you check if this is on purpose (since not shown in usual files list)? If no, I can disable on both targets
> 
> Then this is a bug for the location target as well 😬

Fixed. I will add the docs later, when I implement the open file action part and I get the idea how all of this will work together :D

**Review by JammingBen — APPROVED** [review]

**Pull request merged**
