### PR TITLE
[tests-only] [full-ci] fix for intermittent share-exp-date test fail

### PR DESCRIPTION
**Pull request by sakshamgurung**
## Description

Fix for intermittent fail in share-expiration-date related tests.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/5992

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by sakshamgurung** [comment]
I was not able to reproduce the fail in my local environment. These fixes are based on assumptions related to cause of fail.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/20280/42/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:111

**Review by SwikritiT — COMMENTED** [review]
LGTM

**Review by kiranparajuli589 — COMMENTED** [review]
lgtm 👍🏼

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/20337/15/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:15

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
