### PR TITLE
[full-ci][Tests-Only]Remove tag @issue-4295

### PR DESCRIPTION
**Pull request by swoichha**
## Description
As issue https://github.com/owncloud/web/issues/4295 no longer exist. This PR removes tag `@issue-4295` from test.

## Related Issue
- https://github.com/owncloud/web/issues/4295

## How Has This Been Tested?
- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersBlacklisted</strong> failed. The build is cancelled...</summary>

**Comment by phil-davis** [comment]
I rebased to get fresh CI

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISResharing1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIOCISFiles1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISSharingInternalUsers2</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait2</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIOCISSharingBasic</strong> failed. The build is cancelled...</summary>

**Comment by pascalwengerter** [comment]
@swoichha if you want to run the full CI please put [full-ci] in the PR title and not commit a modified `.drone.star` file

**Comment by swoichha** [comment]
> @swoichha if you want to run the full CI please put [full-ci] in the PR title and not commit a modified `.drone.star` file

Okay got it :+1:

**Review by phil-davis — APPROVED** [review]

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRoot2</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsSharingIndicator</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingFolderAdvPermissionsGrp</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIOCISSharingBasic</strong> failed. The build is cancelled...</summary>

**Comment by phil-davis** [comment]
I rebased again - let's see if we get luck with CI this time.

**Pull request merged**
