### PR TITLE
[tests-only][full-ci]Remove steps that browses to  panel

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description
Previously there were different panels for link share and people share but now they both have been merged into one and there's no `links` panel, so these steps can be removed. The steps basically browse to the `shares` panel and the same thing is done by step that browses to `people` panel

## Related Issue

- Fixes: https://github.com/owncloud/web/issues/7392

## How Has This Been Tested?

- locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/30715/19/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIFilesDetails-fileDetails_feature-L113.png
  

### webUIFilesDetails-fileDetails_feature-L128.png
  

### webUIFilesDetails-fileDetails_feature-L84.png
  

### webUIFilesDetails-fileDetails_feature-L98.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/30715/57/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIFilesDetails-fileDetails_feature-L113.png
  

### webUIFilesDetails-fileDetails_feature-L128.png
  

### webUIFilesDetails-fileDetails_feature-L47.png
  

### webUIFilesDetails-fileDetails_feature-L67.png
  

### webUIFilesDetails-fileDetails_feature-L84.png
  

### webUIFilesDetails-fileDetails_feature-L98.png
  


</p></details>

**Review by saw-jan — COMMENTED** [review]
:+1:

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
I guess that this should also be ported to the stable-2 branch?

**Comment by SwikritiT** [comment]
> I guess that this should also be ported to the stable-2 branch?

Not sure most of the changes have been merged to the master branch only.

**Comment by phil-davis** [comment]
@individual-it is the web repo maintaining a "stable*" branch?
And do we port test PRs to it?

**Review by grgprarup — APPROVED** [review]
:+1:

**Review by SagarGi — COMMENTED** [review]
lgtm :+1:

**Review by individual-it — APPROVED** [review]

**Pull request merged**
