### PR TITLE
Add tags to ResourceTable

### PR DESCRIPTION
**Pull request by lookacat**
## Description
See https://github.com/owncloud/web/issues/7169
Needs: https://github.com/owncloud/owncloud-design-system/pull/2284

## Related Issue

- Fixes https://github.com/owncloud/web/issues/7169

## Screenshots
Screenshot (21)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- https://github.com/owncloud/owncloud-design-system/pull/2284

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10XGAPortrait2</strong> https://drone.owncloud.com/owncloud/web/27281/46/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by JanAckermann** [comment]
@lookacat can you change the target branch to experimental?

**Review by kulmann — COMMENTED** [review]
Was merged without approval. 😛 ex post LGTM 👍 implementation looks really clean, good job.

**Comment by kulmann** [comment]
Also, I set up branch protection on the `experimental` branch now.

**Comment by lookacat** [comment]
@kulmann sorry don't know why it happened :O at least I know have the YOLO Batch for GitHub

**Comment by kulmann** [comment]
> @kulmann sorry don't know why it happened :O at least I know have the YOLO Batch for GitHub 

Perfect achievement to have. 😁

**Pull request merged**
