### PR TITLE
[tests-only] [full-ci] Fix typos in tests folders

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Make some minor typo fixes. I did this to demonstrate that CI is now OK.

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21605/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by phil-davis** [comment]
Needs issue #6225 fixed to get green CI. @SwikritiT is working on it.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/21621/53/1
The following scenarios passed on retry:
- webUISharingAcceptShares/acceptShares.feature:111

**Review by SwikritiT — APPROVED** [review]

**Review by fschade — APPROVED** [review]
👍 LGTM

**Review by kulmann — APPROVED** [review]

**Pull request merged**
