### PR TITLE
Show space icons in search

### PR DESCRIPTION
**Pull request by JanAckermann**
## Description
Show space icon in search, when applies to resources, also fixes the problem, that disabled spaces won't be indicated in Spaces (list view) 

## Related Issue

- Fixes https://github.com/owncloud/web/issues/9347
- Fixes https://github.com/owncloud/web/issues/9350

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by tbsbdr** [comment]
Nice!
Lets please use `function-line` as icon equivalent to `function`
screenshot_001335

**Comment by JanAckermann** [comment]
Don't merge, we missed the preview search -.-

**Comment by JanAckermann** [comment]
> Nice! Lets please use `function-line` as icon equivalent to `function` screenshot_001335

done

**Review by JammingBen — APPROVED** [review]

**Comment by tbsbdr** [comment]
hm.. thought outlined style would be consistent, but it looks quite turbulent. could you please change to to the filled style (even if its not consistent, but I thinks that way its the better solution)

**Comment by JanAckermann** [comment]
Does that include the create space from folder?

**Comment by tbsbdr** [comment]
> Does that include the create space from folder?
no, I'd only change it to solid in the search preview

**Comment by tbsbdr** [comment]
deviating in the context menu from the outlined style would be awful imo

screenshot_001360

**Pull request merged**
