### PR TITLE
feat: remove allow-same-origin from drawio iframe sandbox

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Drawio v24.5.2 no longer requires `allow-same-origin`

https://github.com/jgraph/drawio/issues/4340

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by dschmidt** [comment]
CI is failing:
```
  ✖ And "Alice" creates the following resources # tests/e2e/cucumber/steps/ui/resources.ts:19

       | resource            | type       | content   |

       | shareToBrian.txt    | txtFile    | some text |

       | shareToBrian.md     | mdFile     | readme    |

       | shareToBrian.drawio | drawioFile |           |

       | sharedFile.txt      | txtFile    | some text |

       locator.click: Timeout 30000ms exceeded.

       =========================== logs ===========================

       waiting for frameLocator('#drawio-editor').locator('.geBigButton').locator('text=Save')

       ============================================================

           at createNewFileOrFolder (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:311:71)

           at async Object.createResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:488:3)

           at async Resource.create (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:15:5)

           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:26:7)
```

**Comment by DeepDiver1975** [comment]
@dschmidt any idea why? :shrug:

**Review by kulmann — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
Who can help out on the failing acceptance test.

**Comment by kulmann** [comment]
> Who can help out on the failing acceptance test.

For the first pipeline please do a rebase, that's unrelated to your PR. Translations were broken in master Friday to Monday.

**Comment by DeepDiver1975** [comment]
🤷

**Comment by ScharfViktor** [comment]
I see here 2 failed steps: 
- `And "Alice" sets the expiration date of share` it's flaky, please rebase 
- 
```
And "Alice" creates the following resources
      │ shareToBrian.drawio │ drawioFile │ 
``` 

here is problem - endless loading when open/create file in drawio
image

trace for that (just put to terminal): npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/45208/tracing/file-alice-2024-6-17-10-52-24.zip

**Comment by kulmann** [comment]
> 🤷

another rebase needed after https://github.com/owncloud/web/pull/11051 🙈

**Comment by DeepDiver1975** [comment]
https://github.com/jgraph/drawio/issues/4483

**Pull request closed without merging**
