### PR TITLE
Extract login uri from webfinger

### PR DESCRIPTION
**Pull request by JanAckermann**
## Related Issue

- Fixes https://github.com/owncloud/web/issues/9707

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by lookacat — APPROVED** [review]

**Comment by JanAckermann** [comment]
We actually have an issue with redirect urls with this implementation

**Review by dschmidt — COMMENTED** [review]
Hm - can't we handle this from the web-finger app somehow?

**Comment by JanAckermann** [comment]
@dschmidt no. It seems also that this isn't the way to go for bycs

**Comment by JanAckermann** [comment]
replaced by https://github.com/owncloud/web/pull/9710

**Pull request closed without merging**
