### PR TITLE
Enable readOnly prop for OcSelect and OcTextInput

### PR DESCRIPTION
**Pull request by JanAckermann**
## Related Issue

- Needed for https://github.com/owncloud/web/issues/8840

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):
image
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by JanAckermann** [comment]
🤯

**Comment by JanAckermann** [comment]
snapshots look weird, should they have icon inside?

**Review by JammingBen — COMMENTED** [review]
I'd suggest putting the icon in the `no-options` and in the `selected-option-container` slot. Then you don't have to fiddle around with absolute positioning.

It also breaks currently if you use the `header` slot:

image

**Comment by JanAckermann** [comment]
Not so happy with that as if the drop down opens the icon won't be shown. This would also mean a different type of implementation than the oc-text-input one

**Comment by JammingBen** [comment]
> Not so happy with that as if the drop down opens the icon won't be shown. 

Hmm then add it to the `option` container as well? 😄 Unfortunately, `vue-select` does not provide a global slot for such use cases.

> This would also mean a different type of implementation than the oc-text-input one

Different component = different solution, no? I mean, we have to find a solution. Or we need to document that the `header` slot can't be used together with an icon, which I really don't like.

**Comment by JanAckermann** [comment]
I mean I can check if a header is provided and adjust the margins. 
I don't think it's quite elegant to repetitive add icons in n slots

**Comment by dschmidt** [comment]
What is the semantic difference between ` readonly`  and ` disabled`?

**Comment by JanAckermann** [comment]
For example:
The login(allowed) select might be disabled because you are not allowed to change this for your own account. 
It is readOnly if the server doesn't allow to change this option for any user

**Comment by dschmidt** [comment]
and maybe you can extend this table: https://github.com/owncloud/web/issues/8857

So we know what property name we used here and that we might want to add it to additional components as well.

**Comment by dschmidt** [comment]
> For example: The login(allowed) select might be disabled because you are not allowed to change this for your own account. It is readOnly if the server doesn't allow to change this option for any user

Might be worth documenting/giving this example in the prop documentation

**Comment by JanAckermann** [comment]
I don't know this would be very case specific, I think we shouldn't go too much in detail here, for me its enough if we say sth like: "same as disabled but adds a lock item"

**Comment by dschmidt** [comment]
> I don't know this would be very case specific, I think we shouldn't go too much in detail here, for me its enough if we say sth like: "same as disabled but adds a lock icon"

I would argue: it's a design system, it should guide its users on how to use it. One can decide to not follow the usual rules, but for that one needs to know the rules.

**Comment by JanAckermann** [comment]
I'll add the example, can't block that any longer because its needed for a sprint task

**Review by dschmidt — APPROVED** [review]
Haven't tested it, but I'm happy with the explanation now ;-)
Thanks!

**Review by JammingBen — APPROVED** [review]

**Pull request merged**
