### PR TITLE
Style fixes for menus

### PR DESCRIPTION
**Pull request by elizavetaRa**
## Description
- moving hover effect for tippy-box implemented in web to ods
- unifying spacings for tippy-box menus
- ods part: https://github.com/owncloud/owncloud-design-system/pull/2069

## Related Issue
Fixes hover menus issues from https://github.com/owncloud/web/issues/6555

## Motivation and Context
More consistency in style of different menus

## Screenshots (if appropriate):
menus

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by elizavetaRa** [comment]
@pascalwengerter @fschade @tbsbdr  In contextActions I see menuSections() implementation, in "New" the separator is broder-bottom of the folder item, which is in our opinion inconsistent.

Would it make sense from your point of view to implement menu sections for "New" menu as well?
I would propose the following sections:
- folder
- files, grouped by their origin app (MS Office, Open Office etc) if there is more than one file for the app. (example: Word Document, Excel Spreadsheet, PowerPoint slides in one section)
- All other files in one section

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternal1</strong> https://drone.owncloud.com/owncloud/web/24839/60/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases_feature-L42.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by diocas** [comment]
ping @pascalwengerter @fschade @tbsbdr @kulmann

**Comment by tbsbdr** [comment]
thanks for your patience! thumbs up for the grouping, hover effects and housekeeping!
@pascalwengerter any objections?
But still I would rate it with Prio3 .

**Comment by kulmann** [comment]
Hey @elizavetaRa I've create a release candidate after your ODS PR has been merged. Could you please bump ODS to [v13.1.0-rc.9](https://drone.owncloud.com/link/owncloud/owncloud-design-system/tree/refs/tags/v13.1.0-rc.9) in this PR? Thanks :-)

**Comment by diocas** [comment]
@kulmann rebased with latest master + bump ods + changelog. Let us know if you need anything else.

**Review by kulmann — APPROVED** [review]
LGTM 👍

**Pull request merged**
