### PR TITLE
Show full height drop in modals, without user needs to scroll inside the modal

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Related Issue

- Fixes https://github.com/owncloud/web/issues/11032

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by JammingBen — CHANGES_REQUESTED** [review]
This undos the fix https://github.com/owncloud/web/pull/10816, the modal itself must be scrollable when vertical space is limited.

image

**Comment by AlexAndBear** [comment]
> This undos the fix #10816, the modal itself must be scrollable when vertical space is limited.
> 
> image

Ahhh now I get, why everything stopped working :D 
Coming up with a whole new approach

**Review by kulmann — COMMENTED** [review]
while the dropdown now can overflow the modal, now it's not scrolling if the dropdown list is too long for the current viewport height.

**Comment by AlexAndBear** [comment]
> while the dropdown now can overflow the modal, now it's not scrolling if the dropdown list is too long for the current viewport height.

now it is.

**Comment by JammingBen** [comment]
When I click on the arrow on the right side of a select, nothing happens 🤔 It's not optimal on master either since you have to click the arrow twice, but after that it toggles the options as it should.

**Comment by AlexAndBear** [comment]
> 🤔 It's not optimal on master either since you have to click the arrow twice, but after that it toggles the options as it should.

Unfortunately, this has been brought in by (https://github.com/owncloud/web/commit/973b00ad368c0825d96749e4dc29a23c94589235), in general dropdown-should-open behaves very strange, because it destroys the wanted workflow of the vue-select open event (it doesn't constantly trigger on open).

I introduced a new computed to find out if the dropdown is open or not and adjust the watcher to obey that, instead of 'dropdownEnabled' because its also behaving kind of weird

**Review by JammingBen — APPROVED** [review]
LGTM 👍 The arrow-issue still exists, but since it's the same behavior on master and not critical I'd be fine merging this.

**Pull request merged**
