### PR TITLE
Typo: WebDAV + URL with uppercase characters

### PR DESCRIPTION
**Pull request by michaelstingl**
See:
- https://en.wikipedia.org/wiki/WebDAV
- https://en.wikipedia.org/wiki/URL

## Description

Proper uppercase characters in WebDAV + URL

## Related Issue

- Improves [<issue_link>](https://github.com/owncloud/web/issues/9714)

## Motivation and Context

WebDAV + URL abbreviatiojns should follow the usual conventions

- https://en.wikipedia.org/wiki/WebDAV
- https://en.wikipedia.org/wiki/URL

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by michaelstingl** [comment]
> If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

Done ✅

**Review by EParzefall — APPROVED** [review]

**Comment by JanAckermann** [comment]
Could you guys please wait for an actual developer to approve and merge prs? you missed to add it to the changelog item as well, I'll create a followup....

**Comment by JanAckermann** [comment]
https://github.com/owncloud/web/pull/10196/files

**Comment by michaelstingl** [comment]
Sorry, I activated the `auto-merge` feature 🙈

**Pull request merged**
