### PR TITLE
[full-ci][tests-only] Check resource type in test steps

### LINKED ISSUE #5405: [tests-only] Refactor tests step to also check the resource type
Currently, there is a step `as "Alice" folder "FOLDER" should exist`. Its definition part checks the existence of the given resource but doesn't check its type. This means the following scenarios will also pass (grammatically they should not):
`as "Alice" file "FOLDER" should exist`
`as "Alice" folder "file.txt" should exist`

TODO: Refactor the step definition so that it also checks the resource type

### PR DESCRIPTION
**Pull request by saw-jan**
## Related Issue
- Fixes #5405

## How Has This Been Tested?
- test environment: CI :robot: 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10Trashbin</strong> https://drone.owncloud.com/owncloud/web/16881/34/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUITrashbinRestore-trashbinRestore-feature-260.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/16881/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/16881/9/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUISharingAcceptShares-acceptShares-feature-218.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-379.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10ResharingToRoot</strong> https://drone.owncloud.com/owncloud/web/16881/15/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUIResharingToRoot-reshareUsers-feature-203.png
  

### webUIResharingToRoot-reshareUsers-feature-215.png
  

### webUIResharingToRoot-reshareUsers-feature-227.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroupsToRoot</strong> https://drone.owncloud.com/owncloud/web/16881/21/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups-feature-163.png
  

### webUISharingInternalGroupsToRootEdgeCases-shareWithGroupsEdgeCases-feature-36.png
  

### webUISharingInternalGroupsToRootEdgeCases-shareWithGroupsEdgeCases-feature-37.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroups</strong> https://drone.owncloud.com/owncloud/web/16881/20/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUISharingInternalGroups-shareWithGroups-feature-180.png
  

### webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-41.png
  

### webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-42.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp2</strong> https://drone.owncloud.com/owncloud/web/16881/63/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUIUpload-upload-feature-34.png
  

### webUIUpload-upload-feature-48.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublicExpireAndRoles</strong> https://drone.owncloud.com/owncloud/web/16881/33/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-141.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-149.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-159.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-169.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-181.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-189.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-199.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-209.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-227.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-248.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsersRoot1</strong> https://drone.owncloud.com/owncloud/web/16881/27/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUISharingInternalUsersToRoot-shareWithUsers-feature-125.png
  

### webUISharingInternalUsersToRoot-shareWithUsers-feature-138.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/16881/10/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUIFilesCopy-copy-feature-74.png
  

### webUIMarkdownEditor-markdownFile-feature-12.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10MoveUpload</strong> https://drone.owncloud.com/owncloud/web/16881/12/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUIMoveFilesFolders-moveFiles-feature-140.png
  

### webUIMoveFilesFolders-moveFiles-feature-85.png
  

### webUIUpload-upload-feature-166.png
  

### webUIUpload-upload-feature-34.png
  

### webUIUpload-upload-feature-48.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Resharing</strong> https://drone.owncloud.com/owncloud/web/16881/13/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUIResharing1-reshareUsers-feature-198.png
  

### webUIResharing1-reshareUsers-feature-214.png
  

### webUIResharing1-reshareUsers-feature-230.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Rename</strong> https://drone.owncloud.com/owncloud/web/16881/8/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUIRenameFiles-renameFiles-feature-186.png
  

### webUIRenameFiles-renameFiles-feature-202.png
  

### webUIRenameFiles-renameFiles-feature-227.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsers</strong> https://drone.owncloud.com/owncloud/web/16881/23/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUISharingInternalUsers-shareWithUsers-feature-137.png
  

### webUISharingInternalUsers-shareWithUsers-feature-346.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/16881/37/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:364

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/16882/26/1
The following scenarios passed on retry:
- webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature:98

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/16882/9/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUISharingAcceptShares-acceptShares-feature-218.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-379.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublicExpireAndRoles</strong> https://drone.owncloud.com/owncloud/web/16882/33/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-248.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/16882/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/16885/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/16888/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Review by Talank — COMMENTED** [review]
LGTM

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/16890/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Review by kiranparajuli589 — COMMENTED** [review]
lgtm

**Review by SwikritiT — COMMENTED** [review]
LGTM

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
