### PR TITLE
[full-ci] Remove/refactor `sharesTree`

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
This is (hopefully) the last big refactoring PR regarding shares.

* Removes the `sharesTree`. All (in-)direct shares are now stored in `outgoingShares` and `incomingShares`. The best and easiest way to use them is via the new `useShares` composable (incl. proper type-support).
* Removes a lot of ancient logic to retrieve parent share information in sidebar panels - use `ancestorMetaData` instead.
* Adds types for `ancestorMetaData`.
* Fixes a bunch of sidebar errors in share jail (see https://github.com/owncloud/web/issues/8487).
* Adds proper unit tests for the refactored `loadShares` method.
* Adds proper unit tests for the `FileDetails` component.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/6929
- Fixes https://github.com/owncloud/web/issues/8487

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

### CODE REVIEW

**Review by kulmann — CHANGES_REQUESTED** [review]
Hm... Adding or removing shares is only reflected in share indicators and in the right sidebar when doing a page reload. 🙈 

E.g.
1. Create folder structure `/a/b`
2. Navigate into folder `/a`
3. Open right sidebar (without selecting any `/a/b` before)
4. Share foldler `/a` with `einstein`

Expected: Share indicator for current file list gets updated and selecting the folder `/a/b` shows the share with `einstein` in the right folder as a `via` share / indirect share.

Actual: Noooope. Share indicator not present, indirect share in the right sidebar not visible without page reload.

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/33267/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33267/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2023-3-2-04-13-50.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33267/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-brian-2023-3-2-04-14-18.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33267/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-carol-2023-3-2-04-14-23.zip 


</p></details>
:boom: The e2e-oc10 tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/33272/64/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingInternalGroupsSharingIndicator-shareWithGroups_feature-L142.png
  

### webUISharingInternalUsersSharingIndicator-shareWithUsers_feature-L17.png
  


</p></details>

**Review by kulmann — APPROVED** [review]
🥳 🥳 🥳 ❤️

**Pull request merged**
