### PR TITLE
Tiles view - keyboard navigation, dynamic allocation based on view mode

### PR DESCRIPTION
**Pull request by jacob-nv**
## Description

Adding ability to switch between different views, automatically binding and unbinding keybinds

## Related Issue

- Fixes https://github.com/owncloud/web/issues/8429

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by JammingBen — COMMENTED** [review]
The shift + arrow navigation behaves a bit weird. Let's say I have 6 resources in a 3x2 grid (`tiles-size=3`). Then I select the first resource. Then I go down -> right -> up. It will de-select the previously selected resource.

**Comment by jacob-nv** [comment]
> The shift + arrow navigation behaves a bit weird. Let's say I have 6 resources in a 3x2 grid (`tiles-size=3`). Then I select the first resource. Then I go down -> right -> up. It will de-select the previously selected resource.

Okay, what if I do it same as in files in desktop?
In 3x2 grid.
Select first resource, then go down, it will select whole first row and first tile of second row?

**Comment by jacob-nv** [comment]
> > Select first resource, then go down, it will select whole first row and first tile of second row?
> 
> That would be fine IMO!

Pushed update, please test it if it's to you liking. If so, I'll try to rewrite code into something more streamlined

**Comment by JammingBen** [comment]
> Pushed update, please test it if it's to you liking. If so, I'll try to rewrite code into something more streamlined

Works fine for me 👍

**Review by JammingBen — APPROVED** [review]

**Pull request merged**
