### PR TITLE
Mandatory filtering implementation

### PR DESCRIPTION
**Pull request by JanAckermann**
## Description
Don't load users initially and requires active filters if config var `WEB_OPTION_USER_LIST_REQUIRES_FILTER`is set to true
## Related Issue

- Fixes https://github.com/owncloud/web/issues/10088

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by JanAckermann** [comment]
@kulmann I added the generic mark-element class, we talked about for the mark initialization element selector

**Review by dschmidt — APPROVED** [review]
Hard to tell, but looks good from afar.

just minor nitpicks

**Comment by ScharfViktor** [comment]
@JanAckermann sorry I created commit to wrong branch. I wanted to commit to` fix-quicklink-issues` but it done already so I create new PR

**Review by kulmann — APPROVED** [review]
Brilliant, love it! 🥇

**Comment by JanAckermann** [comment]
> @JanAckermann sorry I created commit to wrong branch. I wanted to commit to` fix-quicklink-issues` but it done already so I create new PR

Don't worry I dropped the commit

**Pull request merged**
