### PR TITLE
[docs-only] fix docs sync after owncloud/owncloud.github.io#29

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
Fix doc build

## Related Issue

- caused by owncloud/owncloud.github.io#29
- same as https://github.com/owncloud/ocis/pull/2366

### CODE REVIEW

**Review by pascalwengerter — APPROVED** [review]

**Comment by phil-davis** [comment]
Note: if we merge #5641 first, then rebase this PR, then it will get minimal "docs-only" CI.

**Comment by wkloucek** [comment]
urrrggg... there is no [docs-only]  flag in Web !? :scream:

**Comment by phil-davis** [comment]
That is waiting to be merged in #5641

**Comment by pascalwengerter** [comment]
> urrrggg... there is no [docs-only] flag in Web !? 😱

See https://github.com/owncloud/web/issues/5637 for discussion

**Comment by pascalwengerter** [comment]
Killed CI so we don't have 2x >1h of acceptance tests running for this

**Comment by pascalwengerter** [comment]
Cherry-picked in #5641, thanks @wkloucek

**Pull request closed without merging**
