### PR TITLE
[full-ci] Acceptance test improvements

### PR DESCRIPTION
**Pull request by kulmann**
Things that this PR (tries to) improve:
- Introduce new short timeout variable for waiting conditions (WIP)
- Delete duplicate page reload stepDefinition & delete unused occurrences to speed up tests

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPermissions2</strong> https://drone.owncloud.com/owncloud/web/18996/58/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/19151/24/1
The following scenarios passed on retry:
- webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature:22

**Comment by ownclouders** [comment]
Results for <strong>oC10iPhone1</strong> https://drone.owncloud.com/owncloud/web/19151/45/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/19160/39/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:106

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/19626/12/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:15

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublicExpireAndRoles</strong> https://drone.owncloud.com/owncloud/web/19627/35/1
The following scenarios passed on retry:
- webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:106

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/19664/12/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:15

**Comment by pascalwengerter** [comment]
Closing this as we don't want to spend any more efforts on the nightwatch tests

**Pull request closed without merging**
