### PR TITLE
sanitize resource id

### PR DESCRIPTION
**Pull request by fschade**
## Description
resource id is used on some places where not all characters are allowed, this tries to clean the id by sanitize it.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/5927

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by kulmann — CHANGES_REQUESTED** [review]
This is not going to work, we need the original id in some places. Please introduce a `cleanId` or `safeId` (or similar naming) prop instead which can be used in html. And please add it to all three resource building helpers. 😅

**Comment by fschade** [comment]
superseded by https://github.com/owncloud/owncloud-design-system/pull/1766

**Comment by pascalwengerter** [comment]
> This is not going to work, we need the original id in some places. Please introduce a `cleanId` or `safeId` (or similar naming) prop instead which can be used in html. And please add it to all three resource building helpers. sweat_smile

What happened to the idea of introducing a `cleanId` or `safeId`? I think this has come up before and I vaguely remember implementing two patchy replace-unsafe-stuff-solutions we could get rid of by adding this to our resource "interface to be" :)

**Comment by fschade** [comment]
I don’t like the idea to have something like a “safeId” in the resource object, I expect that the resource object has only data that describes the object and no data that is used for displaying it. In my opinion we should separate those things strictly.

**Comment by kulmann** [comment]
You're right, fully agreeing with that. However, this means code duplication at the moment, as we need the same helper in both the design system and in web.

**Pull request closed without merging**
