### PR TITLE
[tests-only][full-ci]Forward port resume upload to `master` from `stable-7.0`

### PR DESCRIPTION
**Pull request by SagarGi**
### Description
Forward Port this PR https://github.com/owncloud/web/pull/9190 from `stable-7.0` to `master` branch

### CODE REVIEW

**Review by SwikritiT — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS-1</strong> https://drone.owncloud.com/owncloud/web/36459/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36459/tracing/upload-large-resources-in-personal-space-alice-2023-6-12-06-27-34.zip 


</p></details>

**Comment by ScharfViktor** [comment]
image
This is the second time I've encountered that tracing doesn't work. Anybody has idea why?

**Comment by SagarGi** [comment]
> image This is the second time I've encountered that tracing doesn't work. Anybody has idea why?

same i cannot see the trace

**Comment by SagarGi** [comment]
This is failing because of this issue: https://github.com/owncloud/web/issues/9202.

**Comment by JammingBen** [comment]
> This is failing because of this issue: #9202. so this PR is blocked until it is fixed.

The issue has been fixed via https://github.com/owncloud/web/pull/9291.

**Comment by phil-davis** [comment]
https://github.com/owncloud/web/tree/forward_port_resume_uplaod
This branch is [1 commit ahead](https://github.com/owncloud/web/compare/master...forward_port_resume_uplaod), [93 commits behind](https://github.com/owncloud/web/compare/forward_port_resume_uplaod...master) master.

This branch is quite a lot behind `master` now. IMO it would be good to rebase and get really up-to-date CI results.

**Pull request closed without merging**
