### PR TITLE
[full-ci][tests-only] Bump ocis commit id for tests

### PR DESCRIPTION
**Pull request by grgprarup**
## Related Issue

- Part of https://github.com/owncloud/QA/issues/744

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10Sharing2</strong> https://drone.owncloud.com/owncloud/web/26083/25/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIResharingToRoot-reshareUsers_feature-L25.png
  


</p></details>

**Comment by kulmann** [comment]
I am trying to update the ocis commit id in a different branch as well and have the same issue as you: https://drone.owncloud.com/owncloud/web/26140/12/7
Restoring the ocis binary from cache doesn't work. Tried two different commit ids. Same behaviour. You branch has the same issue with yet another commit id. Do you have any idea what's going on here? 🤔

**Comment by kiranparajuli589** [comment]
https://drone.owncloud.com/owncloud/web/26119/7/3, here the cp command is failing I think. needs more investigation.

**Comment by kulmann** [comment]
> for this pr, https://drone.owncloud.com/owncloud/web/26119/7/3, here the `cp` command is failing in `build-ocis` section. needs further investigation.

Oh, didn't see that, because that step looked successful, although ocis had a build failure. Solution: bump go image in CI to go 1.18, which is a requirement for the most recent ocis. Meta: would be cool to see the build failure in the CI pipeline, can you take care to catch that (in a separate PR)?

**Comment by grgprarup** [comment]
> catch

I will fix that in this PR and if CI goes green then make a separate pr for that.

**Comment by grgprarup** [comment]
> > for this pr, https://drone.owncloud.com/owncloud/web/26119/7/3, here the `cp` command is failing in `build-ocis` section. needs further investigation.
> 
> Oh, didn't see that, because that step looked successful, although ocis had a build failure. Solution: bump go image in CI to go 1.18, which is a requirement for the most recent ocis. Meta: would be cool to see the build failure in the CI pipeline, can you take care to catch that (in a separate PR)?

I will fix that in this PR and if CI goes green then make a separate pr for that.

**Comment by grgprarup** [comment]
> > for this pr, https://drone.owncloud.com/owncloud/web/26119/7/3, here the `cp` command is failing in `build-ocis` section. needs further investigation.
> 
> Oh, didn't see that, because that step looked successful, although ocis had a build failure. Solution: bump go image in CI to go 1.18, which is a requirement for the most recent ocis. Meta: would be cool to see the build failure in the CI pipeline, can you take care to catch that (in a separate PR)?

Golang version is changed to 1.18 in this PR https://github.com/owncloud/web/pull/7115.

**Comment by phil-davis** [comment]
@grgprarup the golng 1.18 change has been merged.

Please rebase this PR and let's see what CI thinks.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
