### PR TITLE
[not-for-merge][tests-only] Run flaky test (webUISharingAcceptSharesToRoot/acceptShares.feature:108) more often

### PR DESCRIPTION
**Pull request by kiranparajuli589**
### Description
Run flaky scenario mentioned in the issue below is run more often in the CI

### Related
https://github.com/owncloud/web/issues/6097

> This PR is just created for demonstration purpose

### CODE REVIEW

**Comment by pascalwengerter** [comment]
You can also comment out the unit/integration/smoke tests in the drone config for an even faster feedback loop

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/20781/8/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:814
- webUISharingAcceptSharesToRoot/acceptShares.feature:574
- webUISharingAcceptSharesToRoot/acceptShares.feature:1094
- webUISharingAcceptSharesToRoot/acceptShares.feature:234
- webUISharingAcceptSharesToRoot/acceptShares.feature:494
- webUISharingAcceptSharesToRoot/acceptShares.feature:534
- webUISharingAcceptSharesToRoot/acceptShares.feature:1174
- webUISharingAcceptSharesToRoot/acceptShares.feature:474
- webUISharingAcceptSharesToRoot/acceptShares.feature:354
- webUISharingAcceptSharesToRoot/acceptShares.feature:1154
- webUISharingAcceptSharesToRoot/acceptShares.feature:454
- webUISharingAcceptSharesToRoot/acceptShares.feature:54
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by kiranparajuli589** [comment]
hmm...most of the scenarios passed on retry [build](https://drone.owncloud.com/owncloud/web/20781/8/20 "CI BUILD")

one failed too.

problem is the same: after unsharing, `simple-folder` is not found on the files page but somehow `testimage.png` is still there.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/20800/8/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:120
- webUISharingAcceptSharesToRoot/acceptShares.feature:644
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by kiranparajuli589** [comment]
by changing the order of assertions, flakiness is reduced but the problem seems to be still there

this time, 2 scenarios failed and only  2 scenarios need retry.

[build](https://drone.owncloud.com/owncloud/web/20800/8/20)

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/20862/8/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:120
- webUISharingAcceptSharesToRoot/acceptShares.feature:267
- webUISharingAcceptSharesToRoot/acceptShares.feature:1064
- webUISharingAcceptSharesToRoot/acceptShares.feature:686
- webUISharingAcceptSharesToRoot/acceptShares.feature:1085
- webUISharingAcceptSharesToRoot/acceptShares.feature:1211
- webUISharingAcceptSharesToRoot/acceptShares.feature:1379
- webUISharingAcceptSharesToRoot/acceptShares.feature:393
- webUISharingAcceptSharesToRoot/acceptShares.feature:288
- webUISharingAcceptSharesToRoot/acceptShares.feature:770
- webUISharingAcceptSharesToRoot/acceptShares.feature:36
- webUISharingAcceptSharesToRoot/acceptShares.feature:833
- webUISharingAcceptSharesToRoot/acceptShares.feature:749

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/20865/8/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21016/8/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21018/8/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21099/7/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:155
- webUISharingAcceptSharesToRoot/acceptShares.feature:575
- webUISharingAcceptSharesToRoot/acceptShares.feature:735
- webUISharingAcceptSharesToRoot/acceptShares.feature:275
- webUISharingAcceptSharesToRoot/acceptShares.feature:475
- webUISharingAcceptSharesToRoot/acceptShares.feature:135
- webUISharingAcceptSharesToRoot/acceptShares.feature:255

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21141/7/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:374
- webUISharingAcceptSharesToRoot/acceptShares.feature:174
- webUISharingAcceptSharesToRoot/acceptShares.feature:534
- webUISharingAcceptSharesToRoot/acceptShares.feature:474
- webUISharingAcceptSharesToRoot/acceptShares.feature:254

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21150/7/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:434
- webUISharingAcceptSharesToRoot/acceptShares.feature:894
- webUISharingAcceptSharesToRoot/acceptShares.feature:114
- webUISharingAcceptSharesToRoot/acceptShares.feature:354
- webUISharingAcceptSharesToRoot/acceptShares.feature:754
- webUISharingAcceptSharesToRoot/acceptShares.feature:134

**Comment by pascalwengerter** [comment]
@kiranparajuli589 @phil-davis what's the strategy & next move here? :)

**Comment by phil-davis** [comment]
@kiranparajuli589 please follow-up on Monday. What is the status of this? Can it be closed?

**Comment by kiranparajuli589** [comment]
i've tried with some workarounds but so far it's not stable. I'll give a another try...let's see how the ci behaves after 10 days ;)

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21415/7/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:554

**Comment by kiranparajuli589** [comment]
success at https://drone.owncloud.com/owncloud/web/21415

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21417/7/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:394
- webUISharingAcceptSharesToRoot/acceptShares.feature:414

**Comment by kiranparajuli589** [comment]
passed without wait too..

**Comment by kiranparajuli589** [comment]
let's try one more time

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21420/7/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:34

**Comment by kiranparajuli589** [comment]
flaky tests are running fine in the ci now. seem like the flakiness is not present anymore

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/22768/7/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingAcceptSharesToRoot-acceptShares_feature-L14.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/22880/9/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:1422
- webUISharingAcceptSharesToRoot/acceptShares.feature:1800
- webUISharingAcceptSharesToRoot/acceptShares.feature:855
- webUISharingAcceptSharesToRoot/acceptShares.feature:1401

**Comment by kiranparajuli589** [comment]
```console
112 scenarios (112 passed)
2016 steps (2016 passed)
65m17.527s (executing steps: 65m11.984s)
```
https://drone.owncloud.com/owncloud/web/22880/9/21

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/22884/9/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingAcceptSharesToRoot-acceptShares_feature-L15.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/22894/9/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingAcceptSharesToRoot-acceptShares_feature-L15.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by kiranparajuli589** [comment]
> 

hmm the drawer has an `active` indicator in the `All Files` section rather in `Shared with me`
seems like the user is still in the files page, after browsing the the shared-with-me page.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/22919/9/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingAcceptSharesToRoot-acceptShares_feature-L15.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by kiranparajuli589** [comment]
> > 
> 
> hmm the drawer has an `active` indicator in the `All Files` section rather in `Shared with me` seems like the user is still in the files page, after browsing the the shared-with-me page.

this info is not correct. the test here actually failed to assert at the files page.

**Comment by kiranparajuli589** [comment]
@pascalwengerter is this change reasonable. if we assert for `unshared` items first at the `files-page` the mentioned test is flaky. but somehow if we assert at the `shared-with-me` page first and then come back to the `files-page` then, the flakiness seems not an issue.

**Pull request closed without merging**
