### PR TITLE
[tests-only] [full-ci] Bump commit ids for testing

### PR DESCRIPTION
**Pull request by phil-davis**

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/19120/24/1
The following scenarios passed on retry:
- webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:114

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/19122/11/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:252

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/19122/12/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:15

**Comment by phil-davis** [comment]
Note: issue https://github.com/owncloud/ocis/issues/1231 - there is special test code for small differences in behavior between oC10 and oCIS for accepting shares. I am removing the diffferences because oC10 now behaves like oCIS since core PR https://github.com/owncloud/core/pull/39241

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/19123/12/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:15

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/19134/52/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:311

**Comment by phil-davis** [comment]
Closing - someone else will take this over. I need time for other things.

**Pull request closed without merging**
