### PR TITLE
[Tests-Only] Refactor `sharingPublic` tests to not use skeleton files

### PR DESCRIPTION
**Pull request by saw-jan**
## Description
Refactor `sharingPublic` tests to not use skeleton files:
- webUISharingPublicBasic
- webUISharingPublicDifferentRoles
- webUISharingPublicExpire
- webUISharingPublicManagement

## Related Issue
https://github.com/owncloud/QA/issues/659

## How Has This Been Tested?
- test environment:

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by Talank — COMMENTED** [review]
LGTM

**Comment by Talank** [comment]
please do rebase and squash.

**Review by swoichha — COMMENTED** [review]
lgtm :+1:

**Review by individual-it — APPROVED** [review]

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublicManagement</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14590/

<p>




</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Move</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14619/

<p>










</p></details>

**Review by individual-it — APPROVED** [review]

**Pull request merged**
