### PR TITLE
[full-ci] Prepare 5.2.0 release

### PR DESCRIPTION
**Pull request by fschade**
* Fixes https://github.com/owncloud/web/issues/6491
* Fixes https://github.com/owncloud/web/issues/6479
* Fixes https://github.com/owncloud/ocis/issues/3237

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles3</strong> https://drone.owncloud.com/owncloud/web/23186/57/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
`webUILogin/openidLogin.feature:29` fails with `Timed out while waiting for element <//span[@data-msgid="Login Error"]> to be present for 10000 milliseconds` - can reproduce, reloading the page after deleting the logged-in user leads me to `https://localhost:9200/oidc-callback?error=server_error&error_description=user%20not%20found&state=7ec783c5c18a40b1904e6f28774c9fe1` with `Authentication failed - Please contact the administrator if this error persists.`

**Comment by pascalwengerter** [comment]
> `webUILogin/openidLogin.feature:29` fails with `Timed out while waiting for element <//span[@data-msgid="Login Error"]> to be present for 10000 milliseconds` - can reproduce, reloading the page after deleting the logged-in user leads me to `https://localhost:9200/oidc-callback?error=server_error&error_description=user%20not%20found&state=7ec783c5c18a40b1904e6f28774c9fe1` with `Authentication failed - Please contact the administrator if this error persists.`

Nevermind, these were _unexpected passes_ - added `[full-ci]`, rebased since master has changed in the meantime, updated expected failures and restarted CI

**Comment by ownclouders** [comment]
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/23225/69/1
The following scenarios passed on retry:
- webUITrashbinRestore/trashbinRestore.feature:46

**Comment by ownclouders** [comment]
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/23226/69/1
The following scenarios passed on retry:
- webUITrashbinRestore/trashbinRestore.feature:46

**Review by pascalwengerter — APPROVED** [review]
🥳

**Pull request merged**
