### PR TITLE
fix: use a tag in context menu instead of button for editors in ctx menu

### LINKED ISSUE #11853: Context-menu "Open in new tab" is broken
## Describe the bug
cmd+click in the file list opens a file in the default editor in a new tab, as expected. The right-click context-menu doesn't seem to hold a link anymore, but a button for viewers/editors.

## Steps to reproduce
1. Create a markdown file
2. Close it again (-> back to file list)
3. Cmd+click on it in the file (-> opens in new tab, as expected)
4. Right-click on it to show the context menu
5. Cmd+click on `Open in Text Editor` (which claims that Cmd+click will open the file in the text editor in a new tab via subtitle below the editor label in the context menu)

## Expected behavior
Text editor opens the file in a new tab

## Actual behavior
Text editor opens the file in the same tab :-(

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Related Issue

- Fixes #11853 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by kulmann — CHANGES_REQUESTED** [review]
please add a changelog item, as this bug was part of a release.

**Comment by AlexAndBear** [comment]
> please add a changelog item, as this bug was part of a release.

Please have a little patience with old ppl like me :(

**Comment by AlexAndBear** [comment]
Let's see if the e2e test are happy, they might check for button and not for a tag

**Review by kulmann — APPROVED** [review]
Thanks for the speedy fix! 🏎️

**Pull request merged**
