### PR TITLE
[full-ci] [Tests-Only] Update commit id

### PR DESCRIPTION
**Pull request by jasson99**
## Description
This PR updates the core and ocis commit id in web.

## Related Issue
- https://github.com/owncloud/QA/issues/688

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10Files2</strong> https://drone.owncloud.com/owncloud/web/18780/13/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10MoveUpload</strong> https://drone.owncloud.com/owncloud/web/18785/14/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by phil-davis** [comment]
@jasson99 PR #5725 was just merged. That has significant changes to the web app.

Please rebase this PR to make sure that we get up-to-date CI.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18788/28/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Locks</strong> https://drone.owncloud.com/owncloud/web/18788/8/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsers</strong> https://drone.owncloud.com/owncloud/web/18788/25/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
Superseded by #5675

**Comment by phil-davis** [comment]
Need to demonstrate-test how to make the commit id update work.

**Comment by pascalwengerter** [comment]
You can see in https://drone.owncloud.com/owncloud/web/18813/9/1 that my changes regarding core+node14 have worked, failures were because of a different topic

**Pull request closed without merging**
