### PR TITLE
Fix loading previews in the right sidebar

### PR DESCRIPTION
**Pull request by kulmann**
## Description
Fix loading previews in the details accordion in the right sidebar

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternalUsers2</strong> https://drone.owncloud.com/owncloud/web/17246/55/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublicExpireAndRoles</strong> https://drone.owncloud.com/owncloud/web/17245/61/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by fschade** [comment]
@pascalwengerter small change done to get sure promise.all won't fail even if one of the promises fails. Fine for now.

We need to come back on the topic later. We are also using loadPreviews from store here to get a higher resolution preview which also mutates the resource by adding a higher resolution preview image. This results on a second unnecessary update of the resource (reactivity), some flickering in the ui and the table then also holds the bigger thumbnail.

not a huge problem atm because the image cache handles this pretty nice for now.

**Review by pascalwengerter — APPROVED** [review]
LGTM, thanks for taking care!

**Pull request merged**
