### PR TITLE
[full-ci] [tests-only] Refactored promise on deleting resource

### PR DESCRIPTION
**Pull request by grgprarup**
## Description
This PR refactors:
```console
await page.locator(actionConfirmationButton).click()
  await page.waitForResponse(
    (resp) => resp.url().includes(encodeURIComponent(resourceName)) && resp.status() === 204
  )
``` 
to 
```console
await Promise.all([
    page.waitForResponse(
      (resp) =>
        resp.url().includes(encodeURIComponent(resourceName)) &&
        resp.status() === 204 &&
        resp.request().method() === 'DELETE'
    ),
    page.locator(actionConfirmationButton).click()
  ])
```

## Related Issue

- Part of https://github.com/owncloud/web/issues/7276

## Motivation and Context
Deleting resources step is failing sometimes on CI and most of the time locally. This PR might fix that issue.

## How Has This Been Tested?

- CI
- Locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by SagarGi — COMMENTED** [review]
@grgprarup  see https://github.com/owncloud/web/issues/7244#issuecomment-1184442866. This is related to delete.

**Comment by grgprarup** [comment]
> @grgprarup see [#7244 (comment)](https://github.com/owncloud/web/issues/7244#issuecomment-1184442866). This is related to delete.

That comment is not related to this PR's issue.

**Review by SwikritiT — COMMENTED** [review]
LGTM

**Review by ScharfViktor — APPROVED** [review]
LGTM

**Pull request merged**
