### PR TITLE
[tests-only] [full-ci] Adjust GitHub comments flow

### PR DESCRIPTION
**Pull request by phil-davis**
First try and see why the VRT directory does not exist.

### CODE REVIEW

**Comment by xoxys** [comment]
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15906/

<p>


### webUIFavorites-unfavoriteFile-feature-13.png
  


</p></details>

**Comment by xoxys** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15906/

<p>


### webUIAccount-accountInformation-feature-20.png
  

### webUILogin-adminBlocksUser-feature-20.png
  


</p></details>

**Comment by xoxys** [comment]
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15906/

<p>


### webUIFavorites-unfavoriteFile-feature-13.png
  


</p></details>

**Comment by xoxys** [comment]
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15909/

<p>


### webUIFavorites-unfavoriteFile-feature-13.png
  


</p></details>

**Comment by xoxys** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15909/

<p>


### webUIAccount-accountInformation-feature-20.png
  

### webUILogin-adminBlocksUser-feature-20.png
  


</p></details>

**Comment by xoxys** [comment]
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15909/

<p>


### webUIFavorites-unfavoriteFile-feature-13.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15910/

<p>


### webUIAccount-accountInformation-feature-20.png
  

### webUILogin-adminBlocksUser-feature-20.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15911/

<p>


### webUIFavorites-unfavoriteFile-feature-13.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15910/

<p>


### webUIFavorites-unfavoriteFile-feature-13.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15911/

<p>


### webUIAccount-accountInformation-feature-20.png
  

### webUILogin-adminBlocksUser-feature-20.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15910/

<p>


### webUIFavorites-unfavoriteFile-feature-13.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15911/

<p>


### webUIFavorites-unfavoriteFile-feature-13.png
  


</p></details>

**Comment by phil-davis** [comment]
See #5191

**Pull request closed without merging**
