### PR TITLE
[full-ci] Switch to PNPM

### PR DESCRIPTION
**Pull request by dschmidt**
## Description
Switch to PNPM.

This is a follow up for https://github.com/owncloud/web/pull/7833

It prepares a bunch of things we need for publishing `web-client` and `web-pkg`:
- add `@ownclouders` prefix to packages
- mark all packages private or public correctly

Unfortunately `yarn` does not support the alias syntax I've used to avoid having to adjust imports in 200 files, so I've done the switch now 🤷🏻  

## Motivation and Context
Use pnpm for better isolation and nifty monorepo publishing features.

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Using `.pnpm-store` seems to work between `cache-pnpm` and `cache-web`. For unit, e2e and acceptance tests packages are downloaded again, let's be fair and fix this. I suspect this might be because of different drone workspace directories. (`/drone/src` vs `/var/www/owncloud/`)

### CODE REVIEW

**Review by pascalwengerter — COMMENTED** [review]
U good over there m8?

**Comment by ownclouders** [comment]
Results for <strong>oCISBasic</strong> https://drone.owncloud.com/owncloud/web/29230/52/1
:boom: The oCISBasic tests pipeline failed. The build has been cancelled.

**Comment by dschmidt** [comment]
We'll see, when/if CI turns green ... or not :trollface:

**Review by kulmann — COMMENTED** [review]
Reviewed and love it. I can't approve right now, because we need to wait for the code freeze in another branch. Can be merged early next week probably.

cc / fyi @individual-it @phil-davis @fschade @wkloucek  this PR will switch over from `yarn` to `pnpm` some time next week after experimental code freeze.

**Comment by individual-it** [comment]
I guess the ocis CI will also have to change

**Comment by kulmann** [comment]
> I guess the ocis CI will also have to change

Not for web itself. I don't know if the acceptance tests need to change in ocis. Could you check? I'd consider this PR blocked until confirmed / until we know a solution.

**Comment by dschmidt** [comment]
I've started working on that here: https://github.com/owncloud/ocis/pull/4878

I would continue to work on that next week but if anyone else wants to look into it, feel free to pick it up. Just let me know if you start working on it. Feedback is of course appreciated as well.

**Comment by fschade** [comment]
pnpm 🤩!!!!!!
Feel free to merge @kulmann it, we had codeFreeze in experimental today 🥳 …. If we need something we can 🍒 pick it. Thx @dschmidt

**Comment by kulmann** [comment]
> pnpm 🤩!!!!!!
> Feel free to merge @kulmann, we had codeFreeze in experimental today 🥳 …. If we need something we can 🍒 pick it. Thx @dschmidt

Cool, thanks for the green light 😎 
However, we'll still wait until CI in ocis is ready to go. And maybe someone else raises concerns that we didn't hear, yet.

**Comment by saw-jan** [comment]
I will check the oCIS CI in PR https://github.com/owncloud/ocis/pull/4878

**Comment by saw-jan** [comment]
The oCIS CI  [build](https://drone.owncloud.com/owncloud/ocis/16355) for PR  https://github.com/owncloud/ocis/pull/4878 is almost :heavy_check_mark: except for one e2e test that needs current latest web.
See https://github.com/owncloud/ocis/pull/4878

CC @kulmann @dschmidt

**Review by kulmann — APPROVED** [review]
Awesome stuff 💪

**Pull request merged**
