### PR TITLE
[full-ci] [tests-only] Refactored inter scenarios space

### PR DESCRIPTION
**Pull request by grgprarup**
## Description
Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines

## Related Issue

- Part of https://github.com/owncloud/QA/issues/769

## How Has This Been Tested?

- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingAutocompletionResharing</strong> https://drone.owncloud.com/owncloud/web/29504/64/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIResharing1-reshareUsers_feature-L177.png
  

### webUISharingAutocompletion-shareAutocompletionSpecialChars_feature-L36.png
  


</p></details>

**Review by kiranparajuli589 — APPROVED** [review]
looks good :+1:

**Comment by kulmann** [comment]
Hey, I'm currently working on bumping a web release candidate in ocis, and as part of that the commit id for web in the .drone.env file. Would like to ask you guys for a favour in that context: could you please try to keep line numbers in feature files unchanged if possible? e.g. don't delete blank lines, if you delete a test scenario or a test step make sure that the following scenario in the file has the same line number as before, even if that means that a feature file is bloated with empty lines. It is really hard to keep track of changes for the expected failures file in ocis. If the line numbers in feature files stay stable it is much easier to handle. Thank you 🤗

**Comment by phil-davis** [comment]
@kulmann yes, agree - after these changes to standardize to having 2 lines between every scenario (blank line, and line for tags) there should not be any need to mess with the line numbers in future. New scenarios can be added to the end of feature files. If and existing scenario needs to be edited and gets shorter, we can leave more blank space after it to keep the line numbers the same. The line numbers will only get messed up if we are forced to add a new line to an existing scenario.

**Comment by kulmann** [comment]
> @kulmann yes, agree - after these changes to standardize to having 2 lines between every scenario (blank line, and line for tags) there should not be any need to mess with the line numbers in future. New scenarios can be added to the end of feature files. If and existing scenario needs to be edited and gets shorter, we can leave more blank space after it to keep the line numbers the same. The line numbers will only get messed up if we are forced to add a new line to an existing scenario.

Awesome, thank you! 🥳

**Pull request merged**
