### PR TITLE
[docs-only] Document oC web as default app with oC 10

### PR DESCRIPTION
**Pull request by pmaier1**

### CODE REVIEW

**Review by kulmann — CHANGES_REQUESTED** [review]
Can you please add a line that the new web ui comes with a limited feature set and users will need to switch back to the classic ui for features that are still missing in the new web ui?

**Comment by pmaier1** [comment]
> Can you please add a line that the new web ui comes with a limited feature set and users will need to switch back to the classic ui for features that are still missing in the new web ui?

Thanks, done.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/16813/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/16814/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Review by kulmann — APPROVED** [review]
LGTM 👍

**Pull request merged**
