### PR TITLE
Analyze change

### PR DESCRIPTION
**Pull request by ScharfViktor**
how to run: 

- `make generate-qa-activity-report MONTH=06 YEAR=2024`
or
- `pnpm exec node analyzeChanges.js --month 7 --year 2024`
- `pnpm exec node analyzeChanges.js --days 10`

report should be generated to `QA_Activity_Report.md`

example: 

[QA_Activity_report-07.24.md](https://github.com/user-attachments/files/16503128/QA_Activity_report-07.24.md)

image

### CODE REVIEW

**Comment by ScharfViktor** [comment]
@tbsbdr could you please choose report format what you like:
1 example:
image

2 example: 
image

**Comment by ScharfViktor** [comment]
@dragotin please choose report format what you like 👆️

**Comment by ScharfViktor** [comment]
generating report to the `.csv` file according to https://github.com/owncloud/ocis/issues/9730#issuecomment-2275442657

image

[QA_Activity_Report_07_2024.csv](https://github.com/user-attachments/files/16549047/QA_Activity_Report_07_2024.csv)

**Comment by ScharfViktor** [comment]
If all is well -> I will create a generating report for other types of tests

**Review by dragotin — APPROVED** [review]
Thanks a lot, looks good!

**Pull request merged**
