### PR TITLE
[CI] Run cache ocis pipeline before tests and increase test timeout

### PR DESCRIPTION
**Pull request by dpakach**
## Description

currently, cache ocis waits for the lint tests to complete, this changes it so that ocis tests can start a bit faster, and while build will complete a bit faster.
Also increase test timeout as sometimes it takes longer to start the ocis server.

## Related Issue

- Fixes slow ocis tests

## How Has This Been Tested?

:robot:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by dpakach** [comment]
this change is only related to CI so should be ok to merge.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15637/

<p>


### webUISharingAcceptShares-acceptShares-feature-100.png
  

### webUISharingAcceptShares-acceptShares-feature-116.png
  

### webUISharingAcceptShares-acceptShares-feature-135.png
  

### webUISharingAcceptShares-acceptShares-feature-16.png
  

### webUISharingAcceptShares-acceptShares-feature-203.png
  

### webUISharingAcceptShares-acceptShares-feature-218.png
  

### webUISharingAcceptShares-acceptShares-feature-235.png
  

### webUISharingAcceptShares-acceptShares-feature-78.png
  

### webUISharingAcceptShares-acceptShares-feature-89.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-110.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-131.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-143.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-15.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-158.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-235.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-245.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-255.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-267.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-282.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-299.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-31.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-315.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-357.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-366.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-379.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-397.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-50.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-72.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-90.png
  


</p></details>

**Review by individual-it — COMMENTED** [review]
LGTM

**Review by LukasHirt — APPROVED** [review]
LGTM 👍

**Review by kulmann — APPROVED** [review]

**Pull request merged**
