### PR TITLE
Refactor modal description message

### PR DESCRIPTION
**Pull request by JanAckermann**
Something is not alright, color should be red 

image

### CODE REVIEW

**Review by pascalwengerter — APPROVED** [review]
LGTM (hope changing the target branch was correct?)

**Comment by JanAckermann** [comment]
> (hope changing the target branch was correct?)

What do you mean? :)

**Comment by pascalwengerter** [comment]
> > (hope changing the target branch was correct?)
> 
> What do you mean? :)

`pascalwengerter changed the base branch from master to 25032021_bump_ODS_to_4_0_0 4 minutes ago` ^^

just checked the `bump_ODS` branch with ODS 4.1.0 and error messages are red (again) 🤔

**Comment by JanAckermann** [comment]
@pascalwengerter I merged it to 25032021_bump_ODS_to_4_0_0, pulled and did a yarn install -> still not red for me ? but maybe the modal errors won't set correct in web

**Comment by pascalwengerter** [comment]
Seems like I missed something, shipping an ODS bugfix now to fix this issue 🙈

**Pull request merged**
