### PR TITLE
Add search nav item

### PR DESCRIPTION
**Pull request by JanAckermann**
## Related Issue

- Fixes https://github.com/owncloud/web/issues/7190

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by pascalwengerter — APPROVED** [review]
Love the simplification, and works nicely. Let's get this through CI and squash-merge 🕵🏽

**Comment by tbsbdr** [comment]
I don't get the userstory for this feature (new Item "Search" appears). I'd expect that there is no active sidebar item at all - first proposal of @kulmann s comment: https://github.com/owncloud/web/issues/7190#issuecomment-1173499037

**Comment by JanAckermann** [comment]
Well this was spoken with @kulmann which we found a good idea, easy to remove anyways if you wish so.

**Comment by JanAckermann** [comment]
Let's remove it, but the issue is not solved then, nav highlighter is still behaving strange

**Comment by JanAckermann** [comment]
https://github.com/owncloud/web/pull/7270

**Pull request merged**
