### PR TITLE
feat: remove internal link type

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
Removes the internal link type since the permanent link makes it obsolete. Existing internal links still resolve correctly to ensure backwards compatibility.

Also removes the action in favor of the new action for copying permanent links.

## Related Issue

- Closes https://github.com/owncloud/web/issues/11544

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

### CODE REVIEW

**Comment by JammingBen** [comment]
@tbsbdr @kulmann There is one edge case when the user doesn't have the permission to create public links. In the past, creating internal links was still possible. With this change though, those users can't create links at all, which is a bit tricky because of the "Copy link" quick action. We can easily check if the resource as a link share and then decide whether to display the quick action or not. But we can't check if the resource has a *quick link*. And since the quick action is designed to only copy quick links, this results in an issue when a resource has a normal link, but not a quick link.

We could change to quick action to factor in regular links as well. Or simply ignore this edge case.

**Comment by tbsbdr** [comment]
I'd opt to make the permalink the default quickaction link

**Comment by kulmann** [comment]
> I'd opt to make the permalink the default quickaction link. we already talked about it some time ago. what do you think @kulmann ?

default was in always use the permalink?!

If I remember correctly I advocated to kill the quick link concept entirely and instead just use any first link that can be found on the resource. If there is none -> permalink.

Since this PR is about removing the internal link type, a good step in between is to copy the permalink when the user isn't allowed to create a public link. Not so sure about always copying the permalink as the only option for the quick action. 🤔

**Comment by tbsbdr** [comment]
Lets always use the perma link in the quickaction. ok @JammingBen @AlexAndBear @kulmann ?

**Comment by JammingBen** [comment]
> Lets always use the perma link in the quickaction. ok @JammingBen @AlexAndBear @kulmann ?

What about the action in the right-click context menu? We have the same problem here. Should it also just copy the permanent link?

**Comment by kulmann** [comment]
> > Lets always use the perma link in the quickaction. ok @JammingBen @AlexAndBear @kulmann ?
> 
> What about the action in the right-click context menu? We have the same problem here. Should it also just copy the permanent link?

IMO yes. Maybe it makes sense to rename the `Share` menu item to `Share or link` or something like that, because everything is in the same panel anyway.

**Comment by kulmann** [comment]
> Okay, so to get this straight: The only way to create a public link will be via the sidebar in the future - no more (quick-) action for that, right? I like that, in fact that's what I was suggesting a few week ago. I just want to make sure we are all on the same page here, because I can certainly imagine that some users won't like it.

Yep, discussed with Tobi yesterday, that  we want to try exactly what you're describing. 👍

**Review by AlexAndBear — APPROVED** [review]
Absolutely stunning 🤩

**Pull request merged**
