### PR TITLE
Fix text editor appearance

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
The text editor now looks normal again after its appearance had changed due to the inclusion of the ODS in the web repository.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

### CODE REVIEW

**Review by kulmann — CHANGES_REQUESTED** [review]
Vertical sizing seems to be broken, see screenshot (that's the lower left corner).

Screenshot 2022-11-25 at 16 24 13

**Comment by JammingBen** [comment]
@kulmann Do you mean there should be a margin-bottom because of the rounded corners? The inner container doesn't have a padding, so the textarea takes its full height - that was the same before.

**Comment by kulmann** [comment]
> @kulmann Do you mean there should be a margin-bottom because of the rounded corners? The inner container doesn't have a padding, so the textarea takes its full height - that was the same before.

The crisp edge of the text editor should be centered both horizontally and vertically in the rounded corner of the app content container.

**Comment by JammingBen** [comment]
Should be fine now:
image

**Review by kulmann — APPROVED** [review]

**Pull request merged**
