### PR TITLE
[full-ci] Search improvements 2

### PR DESCRIPTION
**Pull request by JanAckermann**
## Description
image

- [x] Change architecture, so multiple providers are possible
- [x] Add mark.js
- [x] Redesign preview
- [x] Show 'No results found' with lupe icon in search list 
- [x] Decrease search time out to 100ms  

## Related Issue

- Part of https://github.com/owncloud/web/issues/7591

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by fschade** [comment]
Haven’t had time to review it… just wanna react to the provided screenshot… holy molly, that’s 🔥 thank you ❤️

**Comment by JanAckermann** [comment]
> Haven’t had time to review it… just wanna react to the provided screenshot… holy molly, that’s fire thank you heart

<3

**Comment by JanAckermann** [comment]
TBD in follow up pr:
- [ ] Enable keyboard navigation
- [ ] Rewrite unit tests

**Review by kulmann — APPROVED** [review]
Don't know if you want to include the PR link in an existing changelog item. In any case, this PR is a **massive** improvement. Both visually and technically. WOW dude! :heart:

**Comment by JanAckermann** [comment]
@kulmann Search improvement was kind of a moving target. I like to add a changelog item with all the recent PRs with the final PR

**Pull request merged**
