### PR TITLE
3.5.0 Release

### LINKED ISSUE #5581: Release v4.0.0
## Release checklist
- [x] Merge https://github.com/owncloud/web/pull/5415
- [x] create a branch `release-4.0.0`
- [x] prepare release rc:
  - [x] update the version to `4.0.0` in `packages/web-integration-oc10/appinfo/info.xml`
  - [x] update the version to `4.0.0` in `package.json`
  - [x] update the version to `4.0.0` in `sonar-project.properties`
  - [x] move changelog/unreleased/* to changelog/4.0.0_YYYY-MM-DD
  - [x] update the ocis commit id in `.drone.env` to the most recent one from ocis master (i.e. let the web UI tests run on most recent ocis master)
- [x] create a **draft** pr `release-4.0.0`
- [x] create pre release tag `v4.0.0-rc1` from the release branch
- [x] smoke test
  - [x] against oCIS @fschade
  - [x] against oc10 standalone @pascalwengerter 
- [ ] if needed, fix issues or write down known issues
- [ ] update `YYYY-MM-DD` to current date in `changelog/4.0.0_YYYY-MM-DD`
- [x] Make sure translations are up to date @pascalwengerter
- repeat above steps if a new rc is needed
- [x] Run translations sync job @kulmann 
- [ ] go to the releases section and click `Draft a new Release`. Use `v4.0.0` as a tag (the v prefix is important) and publish it
- [ ] ping in internal #btr channel to create a signed marketplace release
- [ ] merge release branch back to master (CI must be green)

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Closes #5581

### CODE REVIEW

**Review by kulmann — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/17794/38/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:363

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/17849/23/1
The following scenarios passed on retry:
- webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:114

**Comment by phil-davis** [comment]
`Automatic merge failed; fix conflicts and then commit the result.` https://drone.owncloud.com/owncloud/web/17890

Hmmmm - CI won't even run with the conflicts

**Comment by kulmann** [comment]
> `Automatic merge failed; fix conflicts and then commit the result.` https://drone.owncloud.com/owncloud/web/17890
> 
> Hmmmm - CI won't even run with the conflicts

We will rebase and resolve conflicts after the release is done. For now this is fine, because CI runs on tags. I can live with that.

**Comment by kulmann** [comment]
Superseded by https://github.com/owncloud/web/pull/5602 as it turned out that this release requires config changes to prevent a regression in search, making it breaking.

**Pull request closed without merging**
