### PR TITLE
[tests-only] Refactor step definitions

### PR DESCRIPTION
**Pull request by saw-jan**
## Description
Refactored step definitions:
- to use simpler expression (cucumber expression)
- remove unwanted word/character match
- remove unnecessary await

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/36040/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36040/tracing/file-alice-2023-5-25-11-51-11.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/36040/tracing/file-brian-2023-5-25-11-51-40.zip 


</p></details>
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/36041/11/1
:boom: The e2e-oc10 tests pipeline failed. The build has been cancelled.

**Review by SagarGi — COMMENTED** [review]
LGTM :+1:

**Review by SwikritiT — APPROVED** [review]
LGTM

**Review by ScharfViktor — APPROVED** [review]
LGTM

**Pull request merged**
