### PR TITLE
[tests-only][full-ci]Move report generator from acceptance to e2e tests

### PR DESCRIPTION
**Pull request by ScharfViktor**
First, idea was to run all tests with smoke tag, generate a report and attach it to the release issue. Previously, the report was for acceptance tests

now I moved the report to the e2e tests. 

https://github.com/owncloud/web/issues/6224

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/21745/16/1
The following scenarios passed on retry:
- webUIMarkdownEditor/markdownFile.feature:29

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp1</strong> https://drone.owncloud.com/owncloud/web/21745/68/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublic1</strong> https://drone.owncloud.com/owncloud/web/21747/37/1
The following scenarios passed on retry:
- webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:11

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic1</strong> https://drone.owncloud.com/owncloud/web/21747/64/1
The following scenarios passed on retry:
- webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:11

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp1</strong> https://drone.owncloud.com/owncloud/web/21747/68/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
