### PR TITLE
Update minor deps

### PR DESCRIPTION
**Pull request by pascalwengerter**
Updates ODS to showcase new resource-type icons and supersedes some dependabot PRs

### CODE REVIEW

**Review by kulmann — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/23670/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23670/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2022-3-15-10-58-48.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23670/tracing/alice-creates-public-link-to-a-folder-alice-2022-3-15-10-59-50.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23670/tracing/alice-shares-file-to-brian-alice-2022-3-15-11-00-53.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23670/tracing/alice-shares-folder-with-file-to-brian-alice-2022-3-15-11-01-55.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/23670/10/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23670/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2022-3-15-10-59-50.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23670/tracing/alice-creates-public-link-to-a-folder-alice-2022-3-15-11-00-52.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23670/tracing/alice-shares-file-to-brian-alice-2022-3-15-11-01-56.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23670/tracing/alice-shares-folder-with-file-to-brian-alice-2022-3-15-11-03-00.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/23673/10/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23673/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2022-3-15-11-49-08.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23673/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-brian-2022-3-15-11-49-24.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23673/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-carol-2022-3-15-11-49-30.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23673/tracing/alice-shares-file-to-brian-alice-2022-3-15-11-50-47.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/23676/10/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23676/tracing/alice-shares-file-to-brian-alice-2022-3-15-12-08-19.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23676/tracing/alice-shares-folder-with-file-to-brian-alice-2022-3-15-12-09-36.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23676/tracing/alice-shares-folder-with-file-to-brian-brian-2022-3-15-12-09-44.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/23680/41/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:387

**Pull request merged**
