### PR TITLE
Add tooltips to expandSidebar & showViewOptions

### LINKED ISSUE #5723: Some tooltips are missing
Just noticed in 4.1.0 that some of the actions miss tooltips:
- "Expand/collapse right sidebar" button
- "View options" button (e.g. "show hidden files")
- "Details" quick action

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Related Issue
- Fixes #5723

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18529/24/1
The following scenarios passed on retry:
- webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature:104

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/18529/39/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
@kulmann can I get a force-merge here? CI is flaky and I didn't change anything business-logic-y (the `data` prop was a linter complaint)

**Comment by pascalwengerter** [comment]
Supersedes #5648 (which seems to fail randomly in CI and it's not worth re-running it over and over to get a pass)

**Review by kulmann — APPROVED** [review]
👍

**Pull request merged**
