### PR TITLE
Add livereload plugin to rollup

### PR DESCRIPTION
**Pull request by dschmidt**
## Description
This adds the livereload plugin to the rollup config.

I understand that this is a feature maybe not everyone likes. So we might want to make it optional if we add it at all.
Just sending a PR to further discuss it here.

What do you think?

## Related Issue

- Fixes <issue_link>

## Motivation and Context
Unfortunately this is not a true module hot reload like webpack offers, but at least I have to press F5 less often 😇 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by kulmann** [comment]
I'd happily merge it. Other opinions?

**Comment by dschmidt** [comment]
If someone is annoyed, making it optional is fairly trivial and also the plugin can  just be commented out in a local checkout - that's less annoying than dealing with lock file conflicts, so I guess we should just merge...

**Comment by dschmidt** [comment]
Any objections?

**Review by LukasHirt — APPROVED** [review]
LGTM 🚀

**Review by kulmann — APPROVED** [review]

**Pull request merged**
