### PR TITLE
[tests-only][full-ci] Fix space share expiration test

### PR DESCRIPTION
**Pull request by saw-jan**
## Description
Wait for responses that hit after adding sharees

## Related Issue
https://github.com/owncloud/web/issues/8648#issuecomment-1482614610

## How Has This Been Tested?
- test environment:

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/34381/5/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34381/tracing/space-members-can-be-invited-with-an-expiration-date-alice-2023-3-30-11-08-18.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34381/tracing/space-members-can-be-invited-with-an-expiration-date-alice-2023-3-30-11-09-47.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34381/tracing/space-members-can-be-invited-with-an-expiration-date-brian-2023-3-30-11-08-23.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34381/tracing/space-members-can-be-invited-with-an-expiration-date-brian-2023-3-30-11-09-53.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/34516/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2023-4-5-04-37-48.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2023-4-5-04-38-58.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/copy-and-move-resources-in-personal-space-alice-2023-4-5-04-40-04.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/file-alice-2023-4-5-04-46-57.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/file-alice-2023-4-5-04-47-40.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/folder-alice-2023-4-5-04-45-30.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/folder-alice-2023-4-5-04-46-13.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/public-link-alice-2023-4-5-04-40-35.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/public-link-anonymous-2023-4-5-04-40-58.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/quick-link-alice-2023-4-5-04-41-16.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/quick-link-anonymous-2023-4-5-04-41-25.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/re-sharing-brian-2023-4-5-04-42-51.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/re-sharing-brian-2023-4-5-04-43-33.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/search-in-personal-spaces-brian-2023-4-5-04-44-12.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/search-in-personal-spaces-brian-2023-4-5-04-44-51.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/upload-resources-in-personal-space-alice-2023-4-5-04-48-21.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/user-should-be-able-to-read-and-dismiss-notifications-alice-2023-4-5-04-41-31.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34516/tracing/user-should-be-able-to-read-and-dismiss-notifications-alice-2023-4-5-04-42-11.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/34520/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34520/tracing/participant-management-alice-2023-4-5-05-20-51.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34520/tracing/re-sharing-brian-2023-4-5-05-15-52.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34520/tracing/user-should-be-able-to-read-and-dismiss-notifications-alice-2023-4-5-05-14-37.zip 


</p></details>

**Review by SwikritiT — APPROVED** [review]
LGTM

**Review by SagarGi — COMMENTED** [review]
LGTM :+1:

**Pull request merged**
