### PR TITLE
Enable toggleable side bar

### PR DESCRIPTION
**Pull request by rpocklin**
## Description
This change is similar to another one submitted and merged which allows each route to control the visibility of the left-hand sidebar menu.  Along with this, because it assumes more of a full-screen mode, a convenient back button is added to the Top Bar to aid navigating to the previous route.

The flag, defined in the `meta` parameters for any given route, gives the developer the ability to hide the side bar when setting the property `hideSideBar: true`.  There are other conditions in which the sidebar is hidden (eg. width limits) but this flag would take precedence, although preserve these checks on all other routes, ie. if `hideSideBar` is not defined in the `meta` of any route it preserves existing behaviour.

## Related Issue
None.

## Motivation and Context
In developing the app integration for Only Office, we found users prefer it to open within the existing Tab (rather than a new one, as implemented here: https://github.com/owncloud/web/pull/4837) but it made sense to prefer to hide the side bar.  Doing this however, can confuse users without having an explicit back button at the top so they can go to the previous page (typically a file listing page).

## How Has This Been Tested?
I initially included a test for `window.history.length > 1` to be a pre-condition in order to hide the side bar / show the back button, but in my testing I was unable to find a situation where that would be possible in the session, given you have to login.  Happy to amend if there is such a use-case for this.

The hiding of the side-bar does seem a little janky so open to your input on the best approach here (perhaps using a transition to make it more seamless).

I added unit tests for `TopBar.vue`, I would have liked to add tests for `App.vue` but given this is the App Container it became quite challenging to stub / mock all the dependencies, you may have better insight on how to achieve this if desired.

## Screenshots (if appropriate):
**Video**
demo

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Visual regression tests <strong>webUIOCISFiles3</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15194/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Visual regression tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15194/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15194/

<p>









</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Visual regression tests <strong>webUIOCISFiles3</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15195/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>

**Comment by rpocklin** [comment]
I have updated the PR to remove the empty `div` tag if the back button should not be shown, this should fix the visual regression as it now renders like this: 
image

Can you please re-trigger the build, i'm not sure if re-ran properly the second time.

**Comment by ownclouders** [comment]
<details><summary>:boom: Visual regression tests <strong>webUIOCISFiles3</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15253/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Visual regression tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15253/

<p>


Diff Image: </br>


Actual Image: </br>


Comparing Against: </br>



</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15253/

<p>











</p></details>

**Comment by kulmann** [comment]
Hey, UX-wise I think I don't fully get the reasoning. Only having a "back" button when the left sidebar is hidden feels incomplete / inconsistent. We can already go to a view with left sidebar by clicking the `Files` app in the app switcher (top right). That's not ideal, but IMO more consistent.

**Comment by rpocklin** [comment]
Closing due to lack of feedback.

**Comment by kulmann** [comment]
We're currently in the process of rethinking the left sidebar and application menu (in the topbar). Your solution here is much appreciated but doesn't go into the direction how we think this should be solved. However, you uncovered here that the current UX can be improved. 😉 Thanks for taking the time!

**Pull request closed without merging**
