### PR TITLE
Prepare 5.1.0 release

### PR DESCRIPTION
**Pull request by kulmann**
Fixes https://github.com/owncloud/web/issues/6452

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingAndUpload</strong> https://drone.owncloud.com/owncloud/web/22875/66/1
The following scenarios passed on retry:
- webUIUpload/upload.feature:94

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublic1</strong> https://drone.owncloud.com/owncloud/web/22899/36/1
The following scenarios passed on retry:
- webUISharingPublicBasic/publicLinkEdit.feature:145

**Review by pascalwengerter — APPROVED** [review]
LGTM. There was a merge conflict regarding translations, resolved it so should be good to merge

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/23035/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/23035/alice-shares-file-to-brian-alice-2022-2-24-10-42-40.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/23035/alice-shares-file-to-brian-brian-2022-2-24-10-42-47.zip 


</p></details>

**Pull request merged**
