### PR TITLE
[tests-only][full-ci]E2E failure in upload resource in `oc10`

### PR DESCRIPTION
**Pull request by SagarGi**
### Description
This PR is the fix for the fail in the `upload.feature` which was seen in nightly and also in most of the PRs specially in `oc10`. The details or finding or reason behind the failure can be found in this issue. https://github.com/owncloud/web/issues/8189
This issue is faling mostly in `stable-6.0` and also sometimes in `master` branch

### Part of :
https://github.com/owncloud/web/issues/8189

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/31227/10/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-37-55.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-39-26.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-41-02.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-42-02.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-43-03.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-43-56.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-45-18.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-46-11.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-47-41.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-49-02.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-50-04.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-51-25.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-52-26.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-53-57.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-55-27.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-56-47.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-57-47.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-04-59-16.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-00-46.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-02-08.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-03-37.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-04-59.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-06-43.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-08-05.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-09-36.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-10-27.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-11-58.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-12-51.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-14-26.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-15-18.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-16-48.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-17-49.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-19-19.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-20-20.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-21-27.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-22-38.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31227/tracing/upload-resources-in-personal-space-alice-2023-1-6-05-23-39.zip 


</p></details>

**Comment by SagarGi** [comment]
Successfull Drone debug after refactor: https://drone.owncloud.com/owncloud/web/31284/6/16
```
39 scenarios (39 passed)
273 steps (273 passed)
10m37.090s (executing steps: 10m34.547s)
```

**Review by saw-jan — COMMENTED** [review]
LGTM :+1:

**Review by individual-it — APPROVED** [review]

**Review by individual-it — APPROVED** [review]

**Review by ScharfViktor — APPROVED** [review]
More confidence in the test. I like it.

**Pull request merged**
