### PR TITLE
Added announcer for selected files in files app bar

### PR DESCRIPTION
**Pull request by JanAckermann**
## Related Issue

- Fixes https://github.com/owncloud/web/issues/4786

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by JanAckermann** [comment]
@marcus-herrmann Feedback is welcome :)

**Review by marcus-herrmann — APPROVED** [review]
As far as I see this is the first permanent polite live region, right? I only discovered an assertive one in FilesUploadProgress so far,  but haven't checked everything/every state

**Comment by JanAckermann** [comment]
@marcus-herrmann we also have the permanent live region for the route changes

**Comment by marcus-herrmann** [comment]
> are more than one bad design?

Can't really tell at the moment without testing, but I read none of the like.

**Review by kulmann — APPROVED** [review]

**Pull request merged**
