### PR TITLE
Remove image preview when switching to folder

### PR DESCRIPTION
**Pull request by jacob-nv**
## Description

Image preview visible in detail after selecting folder.
Fixed by setting preview to undefined (default value for preview) if recognized as folder

## Related Issue

- Fixes https://github.com/owncloud/web/issues/9713

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by JanAckermann — CHANGES_REQUESTED** [review]
would that also work with a watcher? like this code pattern more

**Comment by jacob-nv** [comment]
> would that also work with a watcher? like this code pattern more

Pushed commit, did you mean something like that?

**Review by JanAckermann — APPROVED** [review]
👍

**Review by JammingBen — COMMENTED** [review]
Hmm tbh I don't like that we lost the task now. We used a task here specifically for 2 reasons:

1. We don't need to care about setting a loading state manually like you now do in the PR.
2. The task is restartable. That means when a preview request is ongoing and a preview for another image is being requested, it automatically cancels ongoing tasks and only performs the latest one.

**Comment by jacob-nv** [comment]
@jacob-nv @JanAckermann What is the final decision on this then? Keeping this or going back one commit?

**Review by JanAckermann — COMMENTED** [review]
Hmmm couldn't you just watch the new resource and decide in the watcher then how to handle the preview? 

I just try to avoid having to much business logic in the tasks but it's rather a loose opinion

**Comment by jacob-nv** [comment]
> Hmmm couldn't you just watch the new resource and decide in the watcher then how to handle the preview?
> 
> I just try to avoid having to much business logic in the tasks but it's rather a loose opinion

So.. if I revert commit I can do something like this.
Remove the check for folder
image
Use already existing watch and check if resource is folder. If it's folder it can just skip the whole task
image

**Comment by JanAckermann** [comment]
Wonderful 👋

**Comment by JammingBen** [comment]
That's still an issue, sorry, we need to set `preview.value` in the task. Imagine this scenario: You select an image, preview starts to load. While loading, you select a folder -> preview image will be set to `undefined`. After the image preview has finished loading, it will set the image for the folder. You can easily reproduce that by simulating a slow network connection in your browser.

**Comment by jacob-nv** [comment]
> That's still an issue, sorry, we need to set `preview.value` in the task. Imagine this scenario: You select an image, preview starts to load. While loading, you select a folder -> preview image will be set to `undefined`. After the image preview has finished loading, it will set the image for the folder. You can easily reproduce that by simulating a slow network connection in your browser. Your first solution handled that perfectly.

Alright then, reverted commit.

**Review by JammingBen — APPROVED** [review]

**Pull request merged**
