### PR TITLE
Prepare release 3.4.0

### PR DESCRIPTION
**Pull request by kulmann**
Version bump for release 3.4.0

Fixes https://github.com/owncloud/web/issues/5486

Only merge back to master after release processes are done. Draft PR until then.

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17209/49/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oC10CreateDelete</strong> https://drone.owncloud.com/owncloud/web/17209/8/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:272

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/17209/39/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:32

**Review by pascalwengerter — APPROVED** [review]
LGTM 🥳

**Comment by ownclouders** [comment]
Results for <strong>oC10XGAPortrait1</strong> https://drone.owncloud.com/owncloud/web/17225/41/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10XGAPortrait1</strong> https://drone.owncloud.com/owncloud/web/17228/41/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:59

**Pull request merged**
