### PR TITLE
[docs-only] Add technology preview info to info.xml

### PR DESCRIPTION
**Pull request by pmaier1**
as discussed

### CODE REVIEW

**Review by kulmann — APPROVED** [review]
👍🏻

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14057/

<p>




</p></details>

**Review by phil-davis — APPROVED** [review]

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRootSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14059/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14059/

<p>







</p></details>

**Pull request merged**
