### PR TITLE
icon and color definitions for dicom-viewer .dcm filetype

### PR DESCRIPTION
**Pull request by koebel**
## Description
[web-app-dicom-viewer](https://github.com/owncloud/web-app-dicom-viewer) is an extension to preview DICOM files (medical images) and their corresponding metadata in the browser. In order to display these .dcm files with a suitable icon in the file list, I've added a new icon. ~~Also added two icons for the flip image function in the dicom-viewer (flip-vertical, flip-horizontal).~~ In addition, color definitions have been added for the .dcm filetype icon.

## Related Issue
- Relates to https://github.com/owncloud/web/issues/9215

## Motivation and Context
I suggest to add these icons and color definitions to web's design system package in order to have all icons in one place. For all other icons used in the dicom-viewer, I reused other icons that are already part of the design system package, but for these particular cases, I couldn't find any suitable icons in the current collection. The new icons match the other icon set (same style, line type, etc.)

## How Has This Been Tested?
icons and color definitions have been tested manually/visually in the browser :)

## Screenshots (if appropriate):
suggested icon & color for .dcm filetype in file list
dicom-viewer-file-list

suggested icon for flip function in the dicom viewer
dicom-viewer-dcm-preview-flip-icon

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:
- [x] Code changes
- [x] Assets added
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] follow up with RemixDesign about flip icon

### CODE REVIEW

**Review by kulmann — CHANGES_REQUESTED** [review]
In general this is ready to merge. Just one question: where do the `flip` icons come from? Did you create them yourself? We need to be clear about licenses. For the FontAwesome icons we have the attribution within the .svg source and in the browser console. If you made the icons yourself, then please add something like this in the svg files:
```
<!-- MIT License: https://opensource.org/licenses/MIT -->
<!-- author: https://github.com/koebel -->
```
(of course with whatever license you want to have...)

**Comment by koebel** [comment]
@kulmann I took some existing icons from your icon set (split-cells-horizontal.svg and split-cells-vertical.svg) as baseline for the flip icon and modified them myself to better fit the context of the dicom viewer functionalities. For the medical data icon, I took a font awesome icon as baseline.

**Comment by koebel** [comment]
@kulmann the SVGs above (split-cells-horizontal.svg and split-cells-vertical.svg) that I took as a baseline for the two flip icons from the [assets](https://github.com/owncloud/web/tree/master/packages/design-system/src/assets/icons) provided in oc web's design-system package, however they don't have any attribution. Do you know anything about their source? I couldn't find them in [font awesome](https://fontawesome.com/search). It looks very much like it's from [this source](https://www.svgrepo.com/svg/347477/split-cells-horizontal) which would have the following credentials: LICENSE: [Apache License](https://www.svgrepo.com/page/licensing/#Apache), AUTHOR: [Remix Design](https://www.svgrepo.com/author/Remix%20Design/)
The Apache Licence states that you are free to remix and to adapt and so does the [author](https://github.com/Remix-Design/RemixIcon/blob/master/README.md#License). Since I just made some minor modifications, I don't feel like I'm really the author of these icons... would the following attribution be ok?

```
<!-- Apache License, Version 2.0: https://opensource.org/license/apache-2-0/ -->
<!-- author: Remix Icon https://github.com/Remix-Design/RemixIcon/, modified by https://github.com/koebel -->
```

**Comment by kulmann** [comment]
@koebel can't you just use the two icons that we already have? `split-cells-horizontal` and `split-cells-vertical`? They look ok to me for your use case.

All our icons which are not prefixed with `resource-` in the file name come from https://remixicon.com - we just imported the full icon set. We still want to put an attribution in the UI (e.g. via an `About` page, which doesn't exist, yet). Remixicon state on their github page that attribution is not required, but I'm not happy that we don't have an attribution for those, yet. Still, we don't need to put the attribution into the `.svg` files.

Again, I'd prefer if you would only add the fontawesome icon for the medical files, that makes sense. But for the remixicons I'd be more happy if we wouldn't add custom icons.

Another option would be to try to get your icons upstream into remixicons, with a PR to https://github.com/Remix-Design/RemixIcon and use the cell icons for now, until remixicons (hopefully) accepts your contribution.

**Comment by koebel** [comment]
Thanks for the feedback. I don't think that the original split cell icon would be suitable, however there was already an issue about this in Remix Icon and I've just created a [PR](https://github.com/Remix-Design/RemixIcon/pull/710) with the proposed solution for these icons to be added to Remix Icons.

**Comment by koebel** [comment]
I've removed the flip icon here while we're waiting for RemixDesign to approve the upstream PR. 
@kulmann is it possible to merge this so that the icon for medical images becomes available through web?

**Review by kulmann — APPROVED** [review]

**Comment by phil-davis** [comment]
@koebel I restarted CI. The previous run last week had some error when building stuff in one of the pipelines, probably unrelated to this PR.
Maybe it will pass now.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/42123/7/4
It failed again in a similar way. Maybe rebase and force-push the branch.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
