### PR TITLE
Truncate tags

### PR DESCRIPTION
**Pull request by JanAckermann**
## Description
Add tag icon and text truncation.

## Screenshots (if appropriate):
Clipboard - August 12, 2022 11_45 AM

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10Upload</strong> https://drone.owncloud.com/owncloud/web/27517/39/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIUpload-upload_feature-L94.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by JanAckermann** [comment]
WHYYYYYYYYYYYYYYYYYY

**Review by fschade — APPROVED** [review]
LGTM

**Comment by phil-davis** [comment]
> WHYYYYYYYYYYYYYYYYYY

@JanAckermann can you share what was the problem/fix with the XGAportrait test pipelines? It might be helpful for others to be aware of whatever are the design/layout/screen-rendering tricks to be aware of.

**Comment by fschade** [comment]
@phil-davis , we've added one additional column `tags` in the files table, this way the total table width was larger than the available viewport width.... and selenium wasnt able to find `open sidebar` CTA and boom...

**Pull request merged**
