### PR TITLE
[tests-only][full-ci]Fix download intermittent test failure

### PR DESCRIPTION
**Pull request by amrita-shrestha**
## Description

While users accept share and navigate to **personal page**, Personal page doesn't load properly.
That leads e2e tests on oc10 to fail while downloading resource (share-by-others)

## Related Issue

- https://github.com/owncloud/web/issues/6610

- Fixes https://github.com/owncloud/web/issues/6596#issuecomment-1070327895

## How Has This Been Tested?

- test environment: CI
- Locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPerm3</strong> https://drone.owncloud.com/owncloud/web/23802/65/1
The following scenarios passed on retry:
- webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:64

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp1</strong> https://drone.owncloud.com/owncloud/web/23802/71/1
The following scenarios passed on retry:
- webUIPrivateLinks/accessingPrivateLinks.feature:17
- webUIPrivateLinks/accessingPrivateLinks.feature:9

**Comment by fschade** [comment]
@amrita-shrestha please don't use page.reload to fix the problem, web is an spa and should be able to handle cases like that without forcing the user to reload.

**Comment by fschade** [comment]
i close this pr here for now, fix will be provided in another pr. Thanks for investigating @amrita-shrestha

**Pull request closed without merging**
