### PR TITLE
Shared with me: Show / Hide shares (#9531)

### LINKED ISSUE #9531: [web] Shared with me: Show / Hide shares
# Description

## User Stories

* > As a user I want to hide unwanted shares so that I can keep an overview over my shares.

* > As a user I want to unsync shares so that my local disk space does not get full. 

* > As a user I want to sync selected shares so that I can access these files on my devices.

## Acceptance Criteria
- All incoming shares are initally shown in "Shared with me" (no more "Accepted- Pending- and Declined shares sections")
- All shares have a new status "visible" or "hidden" (so that users can tidy up unwanted shares); default is "visible"
- ~~oc10: status visible/hidden is not existent and all accepted/declined shares are shown in a single view.~~
- click on "hide" on a share hides the share
- click on "unhide" shows the share
- Button group "Shares" and "Hidden Shares"
  - Click on the respective button shows either shares with the status "hidden" or "unhidden"
- If autoaccept is serverside 
  - enabled, all shares are synced with the mobile& desktop clients
  - disabled, all shares are not automatically available in the mobile and desktop clients
- New button per share: "Enable sync" / "Disable sync" syncs/unsync the share with mobile & desktop clients
  - If a share is "hidden", it still can get get enabled/disabled for syncing (cc @elizavetaRa @diocas @pascalwengerter )
  - "Enable sync" = ~ "Accept share"
  - "Disable sync" = ~ "Pending" for initial incoming shares
  - "Disable sync" = ~ "Decline" if share is not in initial pending state

## Definition of ready
[ ] everybody needs to understand the value written in the user story
[ ] acceptance criteria has to be defined
[ ] all dependencies of the user story need to be identified
[ ] feature should be seen from an end user perspective
[ ] user story has to be estimated
[ ] story points need to be less then 20

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] code review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

### Initial View
- Shows visible shares
- quickaction to `Hide shares`
- Status column shows, if Sync with devices is enabled
- enable sync via batch action or context menu

image

### Hidden Shares
- Toggle button shows hidden shares
- If a share gets hidden, it can still get snyced/unsynced. 
image

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Related Issue
- Fixes #9531

~Waiting for https://github.com/cs3org/reva/pull/4194 to make its way into oCIS~ needs https://github.com/owncloud/owncloud-sdk/pull/1246 merged and published (as well as potential another update to the SDK)

image

### CODE REVIEW

**Comment by JammingBen** [comment]
Pipeline is green and everything works for now.

However, the server is currently reworking some things, so this needs another iteration once https://github.com/cs3org/reva/pull/4256 is resolved. The only thing that needs to change is probably the request for hiding shares, which will be a `PUT`. Also, the param `hide` will be renamed to `hidden`.

**Comment by JanAckermann** [comment]
So good so far,
I noticed that the 'No shares' dialog is not centered on y axis 

image

**Review by JanAckermann — CHANGES_REQUESTED** [review]
Center no item message

**Comment by JanAckermann** [comment]
image
Hide action not in context menu, is this on purpose?

**Comment by JanAckermann** [comment]
If I have a hidden share and click disabled sync, it moves from hidden shares to (visible) shares, is this on purpose? Feels somehow weird to me

**Comment by JanAckermann** [comment]
Is it possible to have a small sync icon `loop-right-fill`next to the (sync) status, because otherwise I feel the cloud icon on its own is not descriptive enough

**Comment by JammingBen** [comment]
@JanAckermann Thx for the feedback, I implemented all your suggestions, except for:

> If I have a hidden share and click disabled sync, it moves from hidden shares to (visible) shares, is this on purpose? Feels somehow weird to me (as I can move disabled sync shares to hidden anyways)

That is a known backend limitation currently. 

> Is it possible to have a small sync icon loop-right-fill next to the (sync) status, because otherwise I feel the cloud icon on its own is not descriptive enough (similar to the postprocessing indicator, next to the file icon)

I agree, also Tobi and CERN suggested to use a different icon here, which I totally forgot about. So it is `loop-right´ now.

**Review by JanAckermann — APPROVED** [review]
😍

**Pull request merged**
