### PR TITLE
feat: enable default autosave in editors

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
As per title.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/11090

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

### CODE REVIEW

**Comment by kulmann** [comment]
cherry pick to stable-8.0?

**Comment by JammingBen** [comment]
> cherry pick to stable-8.0?

Thought about it, it's a feature though... if we want to play by the rules 😂

**Review by AlexAndBear — APPROVED** [review]

**Comment by AlexAndBear** [comment]
IHMO we should add an auto-save icon with a tooltip if this feature is enabled, anyways.

**Comment by kulmann** [comment]
> > cherry pick to stable-8.0?
> 
> Thought about it, it's a feature though... if we want to play by the rules 😂

True 🙈 then let's play by the rules and don't add it to stable-8.0. 👍

**Comment by kulmann** [comment]
> IHMO we should add an auto-save icon with a tooltip if this feature is enabled (as an indicator), anyways.

Can you provide a mockup for this?

**Comment by AlexAndBear** [comment]
> > IHMO we should add an auto-save icon with a tooltip if this feature is enabled (as an indicator), anyways.
> 
> Can you provide a mockup for this?

I don't have a high IQ in figma but putting a refresh-line remix icon with the tooltip next to the save button in the AppTopBar might help

I can fiddle around later and provide a screenshot if wished

**Comment by JammingBen** [comment]
Alright, then I'm going to merge this as the spinner would be a separate task.

**Pull request merged**
