### PR TITLE
Hide new public link share button if user lacks permissions

### LINKED ISSUE #5080: Sharing permission not respected consistently
If I click the share icon on a resource I don't have the right to share the following happens:

1) the collaborators panel shows that I don't have permissions to share
Screenshot 2021-05-07 at 07 44 29

2) the public link button is still available:
Screenshot 2021-05-07 at 07 44 34

3) When you click it fails:
Screenshot 2021-05-07 at 07 44 41

The expected behaviour is that the public links should be disabled as well.

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Hides "Create public link" button if user has insufficient share permissions. Debatable if we should only hide the "Create" button and if users with e.g. view/edit rights should be at least displayed links (even if they can't edit/create/delete them)

## Related Issue
- Fixes #5080

### CODE REVIEW

**Review by fschade — COMMENTED** [review]
LGTM 🚀

**Review by fschade — APPROVED** [review]

**Review by kulmann — CHANGES_REQUESTED** [review]
You're right that we're changing it anyway. But could you do the same approach as in the `FileSharingSidebar.vue` component? That one has a `noResharePermsMessage` computed prop which is displayed instead of the button when resharing is not allowed.

**Comment by pascalwengerter** [comment]
> You're right that we're changing it anyway. But could you do the same approach as in the `FileSharingSidebar.vue` component? That one has a `noResharePermsMessage` computed prop which is displayed instead of the button when resharing is not allowed.

Good idea. I'll however pause this PR in favor of the swarming branch since both touch the `FileLinkSidebar.vue` and I want to avoid merge conflics 🥴

**Comment by pascalwengerter** [comment]
> > You're right that we're changing it anyway. But could you do the same approach as in the `FileSharingSidebar.vue` component? That one has a `noResharePermsMessage` computed prop which is displayed instead of the button when resharing is not allowed.
> 
> Good idea. I'll however pause this PR in favor of the swarming branch since both touch the `FileLinkSidebar.vue` and I want to avoid merge conflics 🥴

We'll rebase this one to `a11y-swarming` and change the merge target to avoid conflicts and have this upstream soon anyways, discussed it with @fschade

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUINotificationBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUINotifications-displayNotificationsOnWebUI-feature-18.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Visual regression tests <strong>webUIOCISFiles3</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>TrashbinDelete</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUITrashbinDelete-trashbinDelete-feature-113.png
  

### webUITrashbinDelete-trashbinDelete-feature-29.png
  

### webUITrashbinDelete-trashbinDelete-feature-42.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>MarkdownEditor</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUIMarkdownEditor-markdownFile-feature-62.png
  

### webUIMarkdownEditor-markdownFile-feature-63.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>TrashbinFilesFolders</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUITrashbinFilesFolders-trashbinFilesFolders-feature-23.png
  

### webUITrashbinFilesFolders-trashbinFilesFolders-feature-38.png
  

### webUITrashbinFilesFolders-trashbinFilesFolders-feature-82.png
  

### webUITrashbinFilesFolders-trashbinFilesFolders-feature-97.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublicDifferentRoles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-114.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-93.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublicExpire</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-106.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-11.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-147.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-24.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-86.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>oc10-integration-notifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUISharingNotifications-shareWithUsers-feature-21.png
  

### webUISharingNotifications-shareWithUsers-feature-32.png
  

### webUISharingNotifications-shareWithUsers-feature-40.png
  

### webUISharingNotifications-shareWithUsers-feature-53.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-19.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-31.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-40.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-53.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>TrashbinRestore</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUITrashbinRestore-trashbinRestore-feature-138.png
  

### webUITrashbinRestore-trashbinRestore-feature-14.png
  

### webUITrashbinRestore-trashbinRestore-feature-181.png
  

### webUITrashbinRestore-trashbinRestore-feature-222.png
  

### webUITrashbinRestore-trashbinRestore-feature-241.png
  

### webUITrashbinRestore-trashbinRestore-feature-260.png
  

### webUITrashbinRestore-trashbinRestore-feature-30.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Upload</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUIUpload-upload-feature-130.png
  

### webUIUpload-upload-feature-151.png
  

### webUIUpload-upload-feature-89.png
  

### webUIUpload-upload-feature-98.png
  

### webUIUpload-uploadEdgecases-feature-109.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>ResharingToRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUIResharingToRoot-reshareUsers-feature-227.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersExpire</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-104.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-105.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-108.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-134.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-211.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-240.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-34.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersExpireToRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-100.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-126.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-203.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-232.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-30.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-96.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-97.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublicManagement</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUISharingPublicManagement-publicLinkIndicator-feature-110.png
  

### webUISharingPublicManagement-shareByPublicLink-feature-102.png
  

### webUISharingPublicManagement-shareByPublicLink-feature-12.png
  

### webUISharingPublicManagement-shareByPublicLink-feature-146.png
  

### webUISharingPublicManagement-shareByPublicLink-feature-201.png
  

### webUISharingPublicManagement-shareByPublicLink-feature-64.png
  

### webUISharingPublicManagement-shareByPublicLink-feature-90.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIResharing</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUIResharing1-reshareUsers-feature-230.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingNotifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUISharingNotifications-shareWithGroups-feature-24.png
  

### webUISharingNotifications-shareWithUsers-feature-21.png
  

### webUISharingNotifications-shareWithUsers-feature-32.png
  

### webUISharingNotifications-shareWithUsers-feature-40.png
  

### webUISharingNotifications-shareWithUsers-feature-53.png
  

### webUISharingNotificationsToRoot-shareWithGroups-feature-24.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-19.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-31.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-40.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-53.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsersRoot2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-109.png
  

### webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-26.png
  

### webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-52.png
  

### webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-61.png
  

### webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-70.png
  

### webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-79.png
  

### webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-96.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsersRoot1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15729/

<p>


### webUISharingInternalUsersToRoot-shareWithUsers-feature-103.png
  

### webUISharingInternalUsersToRoot-shareWithUsers-feature-275.png
  

### webUISharingInternalUsersToRoot-shareWithUsers-feature-57.png
  

### webUISharingInternalUsersToRoot-shareWithUsers-feature-74.png
  


</p></details>

**Review by kulmann — APPROVED** [review]
LGTM 👍

**Pull request merged**
