### PR TITLE
Fix yarn build:w auto reload with docker crashing docker completly

### PR DESCRIPTION
**Pull request by lookacat**
## Description
As you may noticed our workflow with docker was completly broken and unusable sadly.
This should finally fix it :) :)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingAndUpload</strong> https://drone.owncloud.com/owncloud/web/22523/66/1
The following scenarios passed on retry:
- webUIUpload/upload.feature:94

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/22523/55/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:253

**Review by fschade — DISMISSED** [review]
🤩 LGTM

**Review by kulmann — COMMENTED** [review]
For me it doesn't 😞 Can someone else also try it out?

Edit: at least I still see the `Oops. Something went wrong.` error page of hell. If that fix was not about that I can't review because I never experienced "total crash" issues with docker. Might be M1 related.

**Comment by kulmann** [comment]
> For me it doesn't 😞 Can someone else also try it out?
> 
> Edit: at least I still see the `Oops. Something went wrong.` error page of hell. If that fix was not about that I can't review because I never experienced "total crash" issues with docker. Might be M1 related - I'm on Intel.

Checked it again. Still broken for me. The change to the rollup config is good, but it doesn't solve the issue, at least for me, so the changelog item is not appropriate.

For me, steps to reproduce:
- wipe everything-docker (system prune and volume prune), restart docker engine completely
- `yarn build:w`
- `docker-compose up -d`
- check browser, oc10 and ocis work with web
- kill `yarn build:w`
- run `yarn build:w`
- check browser, oc10 and ocis show `Opps. something went wrong` error page.
- 💥

**Comment by lookacat** [comment]
fuck, for me its working i dont know why, will look into this

**Comment by kulmann** [comment]
Superseded by https://github.com/owncloud/web/pull/6855

**Pull request closed without merging**
