### PR TITLE
[full-ci] Warn when using incompatible browser

### PR DESCRIPTION
**Pull request by diocas**
Screenshot 2022-11-09 at 16 39 36

We had many users complaining that things were not working and there was no clear reason why... So we decided to warn them.

There's a new compilation env variable to set a link to documentation, in case you have it.
Also, in case the browser still somewhat supports most of the code, users can still force launch it to check it.

I've opened the PR to see your comments, suggestions and interest, but @elizavetaRa is still going to confirm with our users that it displays the error properly (e.g maybe the css will not be well formatted or the regex won't match?)
If there are necessary changes, we'll update the PR.

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublic1</strong> https://drone.owncloud.com/owncloud/web/29706/36/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicBasic-publicLinkEdit_feature-L89.png
  

### webUISharingPublicBasic-publicLinkPublicActions_feature-L19.png
  


</p></details>
:boom: The oC10SharingPublic1 tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
@diocas why not reuse https://github.com/owncloud/web/blob/83d136ccbab3ef28b30e30e727f6da9249c4c82f/packages/web-runtime/src/layouts/Application.vue#L100 (the way you're doing it now may bring problems in terms of a11y because it can never be translated the way translations are currently handled)?

**Comment by diocas** [comment]
As far as I understood from @elizavetaRa , who is handling our user tickets, they never reach that point.. But, if we do, yes, we could re-use that (but I would suggest maybe to still use the regex)
Our users are reporting issues mainly in 2y old Safari's, if I understood correctly.

The error is not translated, just like the generic error is not translated. Not very user friendly, but not sure we want to spend much effort now in doing that.

**Review by kulmann — APPROVED** [review]
Really nice, thank you for the contribution! 🤩

**Comment by kulmann** [comment]
@diocas could you please rebase to current master? Or should I take over myself?

**Comment by diocas** [comment]
Done

**Comment by kulmann** [comment]
I've added `[full-ci]` to the PR title. Could you amend the last commit and force-push @diocas ? Or trigger CI again with another commit. Would like to see a full CI run for being able to tell what fails in CI. (we have 2 flaky tests related to the datepicker today... if only those were failing I'd force-merge this PR).

**Comment by kulmann** [comment]
Looks like there were only datepicker-related issues in tests, which had nothing to do with this PR (see https://github.com/owncloud/web/pull/8058 ) - could you rebase to most current master again? Sorry 🙈

**Comment by diocas** [comment]
Looks like it stopped in smth unrelated again, no?

**Comment by kulmann** [comment]
> Looks like it stopped in smth unrelated again, no?

Yes, a flaky unit test -.- I restarted the CI, that's sufficient in this case.

**Comment by kulmann** [comment]
I looked into the failing acceptance tests. A test selector for the `publicLinkPasswordPage` is not specific enough. Please apply the following patch to make the tests pass:

```diff
diff --git a/tests/acceptance/pageObjects/publicLinkPasswordPage.js b/tests/acceptance/pageObjects/publicLinkPasswordPage.js
index f9280ca05..bd3f21132 100644
--- a/tests/acceptance/pageObjects/publicLinkPasswordPage.js
+++ b/tests/acceptance/pageObjects/publicLinkPasswordPage.js
@@ -54,14 +54,15 @@ module.exports = {
       selector: '.oc-login-authorize-button'
     },
     resourceProtectedText: {
-      selector: '//*[@class="oc-card-header"]',
+      selector: '//*[contains(@class, "oc-link-resolve")]//*[@class="oc-card-header"]',
       locateStrategy: 'xpath'
     },
     linkResolveErrorTitle: {
       selector: '.oc-link-resolve-error-title'
     },
     publicLinkPasswordSection: {
-      selector: '//*[@class="oc-card-header"]//*[text()="This resource is password-protected"]',
+      selector:
+        '//*[contains(@class, "oc-link-resolve")]//*[@class="oc-card-header"]//*[text()="This resource is password-protected"]',
       locateStrategy: 'xpath'
     }
   }
```

(reason why it failed: `//*[@class="oc-card-header"]` also exists in your browser not supported element and is the first one that is found in the DOM)

**Pull request merged**
