### PR TITLE
[tests-only] [full-ci] Bump CORE_COMMITID

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Bump the core commit id. (I did this mainly because I needed to check that CI is running fine)

## Related Issue
https://github.com/owncloud/QA/issues/688

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/18885/63/1
The following scenarios passed on retry:
- webUIMoveFilesFolders/moveFolders.feature:68

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/18885/52/1
The following scenarios passed on retry:
- webUIFilesCopy/copy.feature:87

**Review by pascalwengerter — APPROVED** [review]
LGTM, can you open another one bumping the ocis-id too? Tried updating web in oCIS (https://github.com/owncloud/ocis/pull/2472) and would like to adjust/figure out expect failures

**Comment by phil-davis** [comment]
> LGTM, can you open another one bumping the ocis-id too?

#5787

**Pull request merged**
