### PR TITLE
[full-ci] [tests-only] Fix ocis login page error message selector in tests

### PR DESCRIPTION
**Pull request by phil-davis**
## Related Issue
https://github.com/owncloud/ocis/issues/2350

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by kulmann — APPROVED** [review]

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/17958/25/14
```
runsh: Total unexpected failed scenarios throughout the test run:
webUISharingInternalUsersShareWithPage/shareWithUsers.feature:91
runsh: There were no unexpected success.
```

That has failed in a few PRs this morning. It seems to be an intermittent test that is now failing a lot.

I restarted CI.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsers</strong> https://drone.owncloud.com/owncloud/web/17965/25/1
The following scenarios passed on retry:
- webUISharingInternalUsersShareWithPage/shareWithUsers.feature:91

**Comment by phil-davis** [comment]
If someone needs to merge this, then feel free to merge. But probably this will happen in PR #5602 for release 4.0.0 and that will sort out the problem.

**Comment by pascalwengerter** [comment]
Closed as already fixed

**Pull request closed without merging**
