### PR TITLE
[full-ci] Web 858 show sharees full list

### LINKED ISSUE #5763: Show sharees as full list
## Acceptance Criteria
- [x] possibility to show displayname + email e.g. like: Tobias Baader (tbaader@owncloud.com)
- [X] truncate name if it gets too long
- [ ] display whole name in a tooltip if truncated
- [x] **wording** ~~invited people~~ display: "Shared with"
- [x] display additional info (share type, expiration date) below sharee name
- [x] don't show the `via` tag and the owner/resharer info in this list - they get moved to the file details in another ticket
- N.a. **resend invite:** implement only, if endpoint is already available. if not, dont implement it.
- [x] context menu:
    - [x] change role on click
    - [x] change custom rights in sub-menu
    - [x] edit expiration date in submenu
        - [x] can't add/edit expiration date after share has been created
    - [x] remove share on click, no confirmation dialog needed
    - [x] when creating share with custom rights (e.g. view&delete), delete permissions don't show up after page reload (possibly oCIS-only, needs investigation if backend/frontend issue)
- [ ] accepatance test: coordinate with JanKariTech
- [ ] (check if keyboard navigation is possible)

### PR DESCRIPTION
**Pull request by paulcod3**
## Related Issue
- Fixes #5763 

## Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [x] Tests

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [  ] Fix Acceptance tests

## Open tasks:
- [ ] https://github.com/owncloud/web/issues/5975 (acceptance tests)

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublicExpireAndRoles</strong> https://drone.owncloud.com/owncloud/web/20022/37/1
The following scenarios passed on retry:
- webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:11

**Comment by ownclouders** [comment]
Results for <strong>oC10iPhone1</strong> https://drone.owncloud.com/owncloud/web/20241/47/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:59

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/20248/15/1
The following scenarios passed on retry:
- webUIFavorites/favoritesFile.feature:111

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/20357/16/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by pascalwengerter** [comment]
Closing this one and superseding it by #6039 as discussed with @fschade

**Pull request closed without merging**
