### PR TITLE
Bump version for release 3.3.1

### PR DESCRIPTION
**Pull request by kulmann**
Bump version for release 3.3.1

### CODE REVIEW

**Review by dschmidt — APPROVED** [review]
Hooray 🎉

**Review by pascalwengerter — APPROVED** [review]
LGTM

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/16897/22/1
The following scenarios passed on retry:
- webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:114

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/16897/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic</strong> https://drone.owncloud.com/owncloud/web/16897/58/1
The following scenarios passed on retry:
- webUISharingPublicManagement/shareByPublicLink.feature:119

**Pull request merged**
