### PR TITLE
[full-ci] feat(public-links): archive downloads in public links

### LINKED ISSUE #2479: Add acceptance tests for Public link Sharing
### Acceptance tests for public link sharing
Inside phoenix, test scenarios inside public link feature are left copied and unimplemented from core.
Implement tests for public link sharing in phoenix:
- [x] Implement the skipped tests for public link sharing as per the feature file:
https://github.com/owncloud/phoenix/blob/master/tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature

### LINKED ISSUE #5776: Open files via public link in associated App (Collabora, OnlyOffice, Word etc.)
**Needed for Cern Stage 1 in Sept 2021**

## Acceptance Criteria
- show shared file(s) in files list
- click on file executes standard action
- context menu (via rightclick or 3-dots) offers alternative open-with ... apps
- ~~download is in the quickactions permanently visible as call-to-action~~

## Context
In order to deliver the feature for cern until the end of September 2021, we need to focus on a solution that meets the minimum requirements. A more sophisticated solution (but not feasible in September) could be to open files directly in the associated app and provide "download" and "open with ..." from here. But such a solution would require a Full-screen view (see https://github.com/owncloud/web/issues/5786).

# Examples
### Example oc10:
check it out: https://cloud.owncloud.com/index.php/s/VtY8JeMjKjtxj8F
image

### Example Google Drive
check it out: https://docs.google.com/document/d/1WrkFjgioofvYe2uLsVdCW6zRvBb6qPp7/edit?usp=sharing&ouid=112080943748993282565&rtpof=true&sd=true

image

### Example One Drive
check it out: https://1drv.ms/w/s!AmFv-ruebwpFkBX6BvqNLz3zRxAA?e=ky6BHQ

view mode:
image

edit mode:
image

### Example Dropbox
check it out: https://www.dropbox.com/scl/fi/bco1nmvm9i8cp0ptujo77/Document.docx?dl=0&rlkey=pjwoqlyqdmxji4skh0tzoyrkk
image

### Example Box.com
check it out: https://app.box.com/s/w0s97nf92wjrmj78oedlda73007c3tya

image

### LINKED ISSUE #5884: Archive download for public links
## Acceptance Criteria
- select multiple files
- download those files as archive.tar

## Context
it is important that also files that are shared publicly can be downloaded as archive, this is a requirement for Cern Stage 1 rollout. This is a addition to the existing implementation  of archive downloads https://github.com/owncloud/web/pull/5832 Currently archive downloads are only available for authenticated contexts.

### LINKED ISSUE #5901: Flicker on boot after OAuth2 redirect
### Steps to reproduce
1. Open browser in incognito mode to make sure no tokens are in local storage and you are not logged in anywhere
2. Go to demo.owncloud.com and login with demo // demo
3. Choose new design

### Expected behaviour
web.owncloud.com opens, I am redirected back to demo.owncloud.com for OAuth2 and then again redirected to web.owncloud.com.

oC Web boots without flickering.

### Actual behaviour
Redirects happen as expected, but oC Web first shows, then the viewport becomes blank and only then oC Web shows permanently. 

This does not seem to happen on regular reloads or when switching to oC Web when it was logged in already, i.e. it seems to be related to OAuth2 token retrieval or something like that.

Not an issue functionality wise but it's a kind of tiny detail that makes software seem less polished to me, so I'd love to see this fixed :) 

https://user-images.githubusercontent.com/448487/137101269-8ae37cdc-74eb-4765-8393-dd7a1ec13b8b.mp4

### PR DESCRIPTION
**Pull request by fschade**
## Description
We introduced archive downloads and app providers in the last weeks, in perspective of getting this out fast we decided to ship those features in small units. 

Currently it is not possible to retrieve capabilities from public links which is problematic and prevents usage of features like archiving and app providers.

This is included and now loads the capabilities in public links with password protection and without.
After that was done it was needed to update the launch process of web which now also have a new livecycle hook (`userReady`).

This also works if the runtime user provisioning step is skipped and another application takes care, in our case the files app.
This shifts responsibility to the individual app and for now is a highly experimental api which should not be used outside of this scope.

some hacky parts are included which needs a refactoring & new design of how applications get loaded, provisioned and rendered. Different topic.

Following features benefit from it:
- create archive from an public link
- create archive from an password protected public link (currently disabled because ocis implications)
- open a file with an app provider from an public link
- open a file with an app provider from an password protected public link
- retrieving capabilities for public links 

it also fixes a bug where the capabilities where not available right after a fresh login, we had to do a hard reload before this to work around it.

## Related Issue
- Fixes #5884
- Fixes #2479
- Fixes #5901
- Fixes #5776

## Motivation and Context
be able to use new features for public links also

## How Has This Been Tested?
- local ocis installation

## Screenshots (if appropriate):
-
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [X] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] write tests
- [ ] test more
- [ ] changelog, TODO is probbally not the best idea ;)

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/19809/11/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternalUsers2</strong> https://drone.owncloud.com/owncloud/web/20042/58/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternalUsers2</strong> https://drone.owncloud.com/owncloud/web/20048/58/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles2</strong> https://drone.owncloud.com/owncloud/web/20049/55/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Review by kulmann — APPROVED** [review]
LGTM, hacky parts are ok for now

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/20109/15/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:15

**Comment by wkloucek** [comment]
> > Nothing related to Web, but I am currently able to edit and save changes to files I received with a "viewer" public link. This needs to be fixed Reva.
> 
> @C0rby can you look into this one?

Will be fixed in https://github.com/cs3org/reva/pull/2214

**Comment by ownclouders** [comment]
Results for <strong>oC10Sharing1</strong> https://drone.owncloud.com/owncloud/web/20122/19/1
The following scenarios passed on retry:
- webUISharingExpirationDate/shareWithExpirationDate.feature:14

**Comment by diocas** [comment]
With this PR merges, does that mean that all the others (#5863 #2479) can be closed?
Does this require anything special from the backend? What I'm seeing from a quick test, is a call to capabilities without any token (which in our case falls back to basic auth). I cancel the auth and the page loads, but then I don't see any call to the apps provider, hence no apps.

**Comment by wkloucek** [comment]
> With this PR merges, does that mean that all the others (#5863 #2479) can be closed? Does this require anything special from the backend? What I'm seeing from a quick test, is a call to capabilities without any token (which in our case falls back to basic auth). I cancel the auth and the page loads, but then I don't see any call to the apps provider, hence no apps. (using my text-editor app it redirects me to the idp, I guess I need to set the route as non authenticated? I already have a special route for public-links)

https://github.com/cs3org/reva/pull/2143 and https://github.com/owncloud/ocis/pull/2536 needs to be there. The authentication for the capabilities request is done with the `public-token` header. A curl example would be `curl 'https://ocis.ocis-traefik.latest.owncloud.works/ocs/v1.php/cloud/capabilities?format=json' -H 'PUBLIC-TOKEN:KvhXJieGpENGXgQ'` but `KvhXJieGpENGXgQ` needs to be a valid / existing public link token

**Comment by diocas** [comment]
@ishank011

**Comment by wkloucek** [comment]
@ishank011 please consider using it in combination with https://github.com/cs3org/reva/pull/2214 only

**Comment by ishank011** [comment]
Thanks @wkloucek! I'll review that PR asap

**Comment by fschade** [comment]
@diocas please note this only works for public links without password, https://github.com/owncloud/web/issues/5863 is used as tracking for public links with password

**Comment by rizu1234565** [comment]
https://zelvirals.com/

**Pull request merged**
