### PR TITLE
[full-ci] Fix 6123 & bump ocis commitid

### LINKED ISSUE #6123: Context menu broken on public links
### Steps to reproduce
1. open public link with Web 

### Expected behaviour
- When I left-click on a file, I see the context menu.
- When I click the three dots menu, I see all available file actions

### Actual behaviour

https://user-images.githubusercontent.com/34452982/145535601-7278d982-3105-452a-b87d-399ac5c74926.mp4

- left-click selects the file row
- clicking the three dots doesn't do anything

### Environment
- oC Web 4.6.0
- oCIS 1.16.0-rc1

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
See changelog & PR title 😃 

## Related Issue
- Fixes #6123 

This is for bringing the fix for #6123 upstream, it's being released as a backported v4.6.1 too for the v1.16 oCIS release

### CODE REVIEW

**Review by lookacat — APPROVED** [review]
LGTM 👍

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic</strong> https://drone.owncloud.com/owncloud/web/20875/65/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Review by fschade — APPROVED** [review]
🚀

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/20882/56/1
The following scenarios passed on retry:
- webUIMarkdownEditor/markdownFile.feature:21

**Comment by pascalwengerter** [comment]
Closed after cherry-picking all relevant commits on #6114 since that contains a fix to avoid adding files to expected failures 😵

**Pull request closed without merging**
