### PR TITLE
[full-ci] Release 4.0.0

### LINKED ISSUE #5581: Release v4.0.0
## Release checklist
- [x] Merge https://github.com/owncloud/web/pull/5415
- [x] create a branch `release-4.0.0`
- [x] prepare release rc:
  - [x] update the version to `4.0.0` in `packages/web-integration-oc10/appinfo/info.xml`
  - [x] update the version to `4.0.0` in `package.json`
  - [x] update the version to `4.0.0` in `sonar-project.properties`
  - [x] move changelog/unreleased/* to changelog/4.0.0_YYYY-MM-DD
  - [x] update the ocis commit id in `.drone.env` to the most recent one from ocis master (i.e. let the web UI tests run on most recent ocis master)
- [x] create a **draft** pr `release-4.0.0`
- [x] create pre release tag `v4.0.0-rc1` from the release branch
- [x] smoke test
  - [x] against oCIS @fschade
  - [x] against oc10 standalone @pascalwengerter 
- [ ] if needed, fix issues or write down known issues
- [ ] update `YYYY-MM-DD` to current date in `changelog/4.0.0_YYYY-MM-DD`
- [x] Make sure translations are up to date @pascalwengerter
- repeat above steps if a new rc is needed
- [x] Run translations sync job @kulmann 
- [ ] go to the releases section and click `Draft a new Release`. Use `v4.0.0` as a tag (the v prefix is important) and publish it
- [ ] ping in internal #btr channel to create a signed marketplace release
- [ ] merge release branch back to master (CI must be green)

### PR DESCRIPTION
**Pull request by kulmann**
Fixes #5581

### CODE REVIEW

**Comment by kulmann** [comment]
Rebased to current master, as we anyway have to start from scratch with smoke testing.

**Comment by ownclouders** [comment]
Results for <strong>oCISBasic</strong> https://drone.owncloud.com/owncloud/web/17926/47/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by phil-davis** [comment]
@kulmann I added `full-ci` to the PR title. Next time you push a change the test pipelines will all run to completion. That should help to see what are all the failing test suites.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/17942/39/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:363

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsers</strong> https://drone.owncloud.com/owncloud/web/17942/25/1
The following scenarios passed on retry:
- webUISharingInternalUsersShareWithPage/shareWithUsers.feature:91

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/17953/11/1
The following scenarios passed on retry:
- webUISharingAcceptShares/acceptShares.feature:93

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsersExpire</strong> https://drone.owncloud.com/owncloud/web/17953/27/1
The following scenarios passed on retry:
- webUISharingInternalUsersExpireToRoot/shareWithUsersExpiringShares.feature:100

**Comment by phil-davis** [comment]
What happened? 
The build was killed after 9 seconds: https://drone.owncloud.com/owncloud/web/17979
Was that done manually, or it killed itself somehow?

**Comment by kulmann** [comment]
> What happened? 
> 
> The build was killed after 9 seconds: https://drone.owncloud.com/owncloud/web/17979
> 
> Was that done manually, or it killed itself somehow?

I killed it manually because the branch will be rebased any minute now

**Comment by ownclouders** [comment]
Results for <strong>oC10XGAPortrait1</strong> https://drone.owncloud.com/owncloud/web/17985/42/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:59

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/17985/12/1
The following scenarios passed on retry:
- webUIFavorites/unfavoriteFile.feature:13

**Pull request merged**
