### PR TITLE
[full-ci][Tests-Only]Bump web commit ID 2021-06-14

### PR DESCRIPTION
**Pull request by Talank**
Bumped commit IDs of ocis and core in web.
part of issue https://github.com/owncloud/QA/issues/662

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsToRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16234/

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups-feature-245.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-265.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-315.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-316.png
  


</p></details>
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsToRoot</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsToRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16245/

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups-feature-245.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-265.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-315.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-316.png
  


</p></details>
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsToRoot</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublicExpireAndRoles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16246/

<p>


### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-106.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-130.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-147.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-51.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-52.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-71.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-72.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-86.png
  


</p></details>
<details><summary>:boom: Acceptance tests <strong>SharingPublicExpireAndRoles</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16331/

<p>


### webUISharingInternalGroups-shareWithGroups-feature-271.png
  

### webUISharingInternalGroups-shareWithGroups-feature-293.png
  

### webUISharingInternalGroups-shareWithGroups-feature-349.png
  

### webUISharingInternalGroups-shareWithGroups-feature-350.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublicExpireAndRoles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16331/

<p>


### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-106.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-130.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-147.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-51.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-52.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-71.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-72.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-86.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsToRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16331/

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups-feature-245.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-265.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-315.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-316.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersExpire</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16331/

<p>


### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-104.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-105.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-108.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-134.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-16.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-211.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-24.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-34.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-54.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-100.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-126.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-14.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-203.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-21.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-30.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-48.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-96.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-97.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsToRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16344/

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups-feature-245.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-265.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-315.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-316.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16344/

<p>


### webUISharingInternalGroups-shareWithGroups-feature-271.png
  

### webUISharingInternalGroups-shareWithGroups-feature-293.png
  

### webUISharingInternalGroups-shareWithGroups-feature-349.png
  

### webUISharingInternalGroups-shareWithGroups-feature-350.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIFiles1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16344/

<p>


### webUIMarkdownEditor-markdownFile-feature-26.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersExpire</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16344/

<p>


### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-104.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-105.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-16.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-211.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-24.png
  

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-34.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-14.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-203.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-21.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-30.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-96.png
  

### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-97.png
  


</p></details>

**Review by phil-davis — APPROVED** [review]
LGTM if CI passes this easily.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/16368/10/8
error An unexpected error occurred: "https://registry.yarnpkg.com/underscore/-/underscore-1.9.1.tgz: Request failed \"502 Bad Gateway\"".

I will restart CI

**Comment by phil-davis** [comment]
Again "error An unexpected error occurred: "https://registry.yarnpkg.com/@babel/generator/-/generator-7.12.15.tgz: Request failed \"502 Bad Gateway\""." https://drone.owncloud.com/owncloud/web/16375/6/6

Not a happy time for the drone agents. I will restart.

**Pull request merged**
