### PR TITLE
Enable capability-based avatar img loading

### LINKED ISSUE #5077: Disable avatar requests
It is not possible to change avatar in OCIS.
Disable this feature until is available to avoid network latencies.

### PR DESCRIPTION
**Pull request by pascalwengerter**
Can only be used with oCIS >= v1.6.0 and OC10 >= 10.7 (otherwise avatar imgs won't load)

## Description
See changelog item

## Related Issue
- Fixes #5077

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17200/49/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/17200/51/1
<details><summary>:boom: Visual regression tests failed. Please find the screenshots inside ...</summary>

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
Failes in the VRT even though the capability is in the `core` master https://github.com/owncloud/core/search?q=profile_picture and it works locally when running against one of the beta Docker images

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17524/49/1
The following scenarios passed on retry:
- webUISharingAcceptShares/acceptShares.feature:93

**Review by kulmann — APPROVED** [review]
LGTM 🖼️

**Pull request merged**
