### PR TITLE
[tests-only] Reduce unnecessary waits

### PR DESCRIPTION
**Pull request by saw-jan**
## Description
Reducing unnecessary waits from the e2e tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by pascalwengerter** [comment]
@saw-jan is this still being worked on?

**Comment by saw-jan** [comment]
> @saw-jan is this still being worked on?

I thought it would be useful for the tests but haven't talked with @ScharfViktor yet.

@ScharfViktor What do you think? Would it be good to have it or not bother at all?
This will clear popup dialogs using Playwright evaluate method (runs js in browser) so that tests don't have to wait for the popup dialogs timeout.

**Comment by ScharfViktor** [comment]
> @ScharfViktor What do you think? Would it be good to have it or not bother at all? This will clear popup dialogs using Playwright evaluate method (runs js in browser) so that tests don't have to wait for the popup dialogs timeout.

I would like to have this to skip waiting for the "link popup creation"

**Comment by saw-jan** [comment]
> I would like to have this to skip waiting for the "link popup creation"

Then I will work on this PR soon.

**Review by ScharfViktor — APPROVED** [review]

**Pull request merged**
