### PR TITLE
Fix avatar url

### PR DESCRIPTION
**Pull request by dschmidt**
## Related Issue

- Fixes https://github.com/owncloud/web/issues/4610

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13752/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>

**Comment by dschmidt** [comment]
Looks to me as if the test is asserting the broken behavior and should be updated. I have no idea how to do that :innocent:

**Comment by kulmann** [comment]
True. ;-) could you check if this helps? https://owncloud.github.io/clients/web/testing/#updating-the-snapshots

**Comment by kulmann** [comment]
Also, could you please add a bugfix changelog item to the changelog/unreleased folder? You can copy an old one from the previous release folder and adapt to your content.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13827/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>

**Comment by individual-it** [comment]
- [ ] TODO QA:team update the base line image for ocis - note: ocis shows the person icon, oc10 the letters

**Comment by individual-it** [comment]
updated the baseline image and rebased on current master, lets see ...

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14012/

<p>




</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRootSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14021/

<p>




</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14112/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>OCISFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14115/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>

**Comment by individual-it** [comment]
how comes the search-bar is suddenly there?

**Comment by individual-it** [comment]
`"hideSearchBar": true` is not set in the config for ocis

**Review by kulmann — APPROVED** [review]
👍🏻

**Pull request merged**
