### PR TITLE
[test-only] Fix re-sharing flaky

### PR DESCRIPTION
**Pull request by ScharfViktor**
#7566
fix flaky: So far, I've disabled this check for oc10 to stabilize CI 

As soon as we find a better solution, we'll enable it

### CODE REVIEW

**Comment by ScharfViktor** [comment]
although flacks are not only in oс10 https://drone.owncloud.com/owncloud/web/27992/12/13

**Comment by ScharfViktor** [comment]
how user do share in test:
- user clicks "show context menu" on the resource
- press "Details" btn
- chooses "Shares" in sidebar (here check transition to shares panel)
- do share

It works well for sharing from personal/project space (let it go on working - let's not interfere). For shares jail it works flaky

I added more easy workflow for sharing from shares jail:
- user clicks "show context menu"
- press "Share" btn
- do share

**Comment by ScharfViktor** [comment]
PR is ready to review. CI is without flaky

**Review by grgprarup — COMMENTED** [review]
LGTM :+1:

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
