### PR TITLE
fix TUS uploading #6651

### PR DESCRIPTION
**Pull request by ScharfViktor**
related https://github.com/owncloud/enterprise/issues/6651#issuecomment-2107052192

@butonic I changed `OCIS_CORS_ALLOW_ORIGINS` and now TUS upload works again

CC @dschmidt @JammingBen

### CODE REVIEW

**Comment by butonic** [comment]
Some more explanation:
1. The first POST request works because the tus.go handlar implementation in ocdav internally makes an InitiateUpload request and then directly a PATCH request without setting an origin header. As a result the tus handler does not check the origin / no CORS check needs to be made (the request is not made by a browser)
2. The next PATCH request then fails because the origin header sent by the browser is forwardet to the datahandler where the tus handler now fails the origin check.

IMO the datagateway should not swallow that error ... may it does not, but that is only visible when enabling prefilight requests in the devtools. Maybe we can automatically add the OCIS_URL to the allowed domains? And use an OCIS_CORS_ADDITIONAL_DOMAINS?

**Review by dschmidt — CHANGES_REQUESTED** [review]
This will most likely break uploads in Vite (our development server). imho it's an ocis bug if uploading from the same host and port requires cors settings... and even if it's considered wontfix, I'm still against breaking our dev server

**Comment by ScharfViktor** [comment]
Do you mean we can implement new `OCIS_CORS_ADDITIONAL_DOMAINS`? because I didn't find this env in docs

I see that OCIS_CORS_ALLOW_ORIGINS  can be used as list: https://doc.owncloud.com/ocis/next/deployment/services/s-list/webdav.html so we can add more url to the CORS origins like: `OCIS_CORS_ALLOW_ORIGINS: https://host.docker.internal:9200,https://host.docker.internal:9201`

**Comment by dschmidt** [comment]
@ScharfViktor have you checked this works? on 9200 and on 9201 with vite?

**Comment by ScharfViktor** [comment]
> @ScharfViktor have you checked this works? on 9200 and on 9201 with vite?

I don't know much about how work with vite, but seems that works

- pnpm install
- pnpm buld
- docker-compose up -d
- pnpm vite

Result: https://host.docker.internal:9201/ and https://host.docker.internal:9200 work. (TUS upload works fine)

Screenshot 2024-05-13 at 14 12 43

**Review by dschmidt — APPROVED** [review]
LGTM, thanks for figuring this out! <3

**Pull request merged**
