### PR TITLE
[Tests-Only] Convert phoenix to web in visual regression

### PR DESCRIPTION
**Pull request by HariBhandari07**
## Description

Convert `phoenix` to `web`.
## Related Issue

- Fixes https://github.com/owncloud/web/issues/4620
## How Has This Been Tested?

- CI
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by dpakach — CHANGES_REQUESTED** [review]
the s3 bucket is still named `phoenix`. someone with the authority needs to rename that. The PR will pass for now but this will not work when we have a VRT failure. I would suggest waiting till the bucket name gets sorted out in s3

**Comment by phil-davis** [comment]
1) @dpakach who is asking and following up to get the bucket name sorted out?

2) when the bucket is ready, we can easily to a test-demonstration PR on top of this one to force a VRT failure.

**Comment by phil-davis** [comment]
I sent email to sysadmin to get the S3 bucket renamed.

**Comment by pascalwengerter** [comment]
@phil-davis any update from the sysadmin? :)

**Comment by dpakach** [comment]
The bucket has been renamed and already updated

**Pull request closed without merging**
