### PR TITLE
Draft: CERNBox/Web - status of web fork - Don't merge

### PR DESCRIPTION
**Pull request by labkode**
This issue keeps track of status of fork between cernbox/web (cernbox branch) and owncloud/web (master branch)

### CODE REVIEW

**Comment by pascalwengerter** [comment]
@labkode @elizavetaRa this looks like a rebase-gone-wrong, or you picked the wrong `cernbox` branch or maybe I'm missing something? 
Quite a couple of commits are superfluous from my understanding (some since mid February actually), ping me if you need assistance in figuring out the exact ones

**Comment by diocas** [comment]
@pascalwengerter as Hugo says, this is just to keep track of the changes. It's out of date because we haven't updated since you were here (we wanted to have everything merged so that we could clean and merge on our side)

**Comment by diocas** [comment]
As mentioned yesterday, the link to branch were lisa was doing the OCM app is this: https://github.com/cernbox/web/commits/ocm (on top of our prod, so not up to date and with our fork commits)

**Comment by pascalwengerter** [comment]
> @pascalwengerter as Hugo says, this is just to keep track of the changes. It's out of date because we haven't updated since you were here (we wanted to have everything merged so that we could clean and merge on our side)

While I get the appeal of doing one big rebase once "everything" is "done", I want to point out that this approach
- paints a very inaccurate picture of the current situation to all decisionmakers and stakeholders since "nothing is happening, after all"
- makes you miss out on all the features (and bugs, but let's assume the ratio is worth the effort in the first place 😅 😉) that have been implemented in the meantime
- keeps you from testing the (already available) upstream solutions to your problems, which may differ from your current workarounds and anyhow need a quick review or even tiny adjustment which you're delaying by not having rebased
- makes *the final, big* rebase a gnarly and exhausting task, which just keeps growing

Ideally if your workload allows, and let me know if we (@kulmann or someone else from ownCloud's web team or me) can support you in doing that, we can aim for a timely, intermittent rebase to give everyone a better picture of the current state (as pointed out, this PR in its current state isn't very valuable) and reduce the "final" workload

**Comment by diocas** [comment]
Don't worry, I made that point very clear to the decision makers. And I made clear that this should only be used to know what were the extra things we needed in CERNBox and not the work that was missing.

About the rebase not being more consistent, I can just say that they were, but the last months were not _exceptionally_ (many other things in parallel and this took less priority).

To test the new features we might use just upstream, so it's not a holder for testing them (lack of time on the other hand...)

**Comment by kulmann** [comment]
Can we close this PR since you have opened https://github.com/owncloud/web/pull/9159 ?

**Pull request closed without merging**
