### PR TITLE
emit files in dev mode

### PR DESCRIPTION
**Pull request by fschade**
right now no changes in main app get written to disk. This is a problem if you start to develop ocis with custom asset path (PHOENIX_ASSET_PATH). This PR fixes this

### CODE REVIEW

**Comment by LukasHirt** [comment]
Could we make this optional? Sometimes we're developing against oC10 backend where this is not needed. I'd still love to see the `watch-all-ocis` command to spawn a dev server on ocis-phoenix port so we can develop without that service running. That's something for a separate PR though 🙂

**Comment by LukasHirt** [comment]
Rebasing PR should btw help with the node error. We are using now different nodejs images with version 12.

**Comment by fschade** [comment]
let's discuss the watch-all-ocis idea today. I think i have time to do it today

**Comment by fschade** [comment]
I close this in fav to the experimental rollup switch

**Pull request closed without merging**
