### PR TITLE
Provide and document dockerized backend for development & testing

### LINKED ISSUE #936: add docker-compose for ownCloud + Phoenix dev environment
maybe bit like https://github.com/owncloud/nexus/blob/master/deploy/core.yml

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
As a developer/potential contributor, I'd like to test the web frontend with OC10 and oCIS with minimal overhead in terms of installing programming languages, dependencies etc. Docker perhaps is the way to go here

## Related Issue
- Fixes #936

## Motivation and Context
Thank you @fschade for the initiative 💟 

## Types of changes
- [X] Developer ergonomics

## Open tasks:
- [ ] Make sure it works on Windows
- [ ] Make sure it works on Ubuntu
- [ ] Move related files from `tests/acceptance/docker` to `docker` since it's not limited to running tests
- [ ] Update testing documentation

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10iPhone2</strong> https://drone.owncloud.com/owncloud/web/17041/44/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17040/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17145/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by pascalwengerter** [comment]
@fschade after two `Docker Desktop for Mac` updates I see the same problems about default ENV vars we've seen on Windows 🤔 could you take another look?

**Comment by ownclouders** [comment]
Results for <strong>oC10Basic</strong> https://drone.owncloud.com/owncloud/web/17601/6/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/17601/10/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10CreateDelete</strong> https://drone.owncloud.com/owncloud/web/17601/8/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Locks</strong> https://drone.owncloud.com/owncloud/web/17601/7/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Rename</strong> https://drone.owncloud.com/owncloud/web/17601/9/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPermissions1</strong> https://drone.owncloud.com/owncloud/web/17601/56/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Locks</strong> https://drone.owncloud.com/owncloud/web/17603/7/1
The following scenarios passed on retry:
- webUIWebdavLockProtection/move.feature:123
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUIWebdavLockProtection-delete-feature-75.png
  

### webUIWebdavLockProtection-delete-feature-76.png
  

### webUIWebdavLockProtection-move-feature-124.png
  

### webUIWebdavLockProtection-move-feature-145.png
  

### webUIWebdavLockProtection-move-feature-146.png
  

### webUIWebdavLockProtection-upload-feature-90.png
  

### webUIWebdavLockProtection-upload-feature-91.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublicManagement</strong> https://drone.owncloud.com/owncloud/web/17683/33/1
The following scenarios passed on retry:
- webUISharingPublicManagement/publicLinkIndicator.feature:27

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/17683/39/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:356

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/17683/38/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:363

**Review by fschade — APPROVED** [review]
LGTM 🤖 Thanks ❤️

**Pull request merged**
