### PR TITLE
[Tests-Only] add webui tests for viewing mp3 file in media viewer

### PR DESCRIPTION
**Pull request by swoichha**
## Description
Added webUI tests for viewing mp3 files in media viewer

## Related Issue
- https://github.com/owncloud/ocis/issues/1106

## How Has This Been Tested?
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by Talank — COMMENTED** [review]
LGTM

**Review by individual-it — APPROVED** [review]
don't we have the

**Review by jasson99 — APPROVED** [review]

**Review by individual-it — CHANGES_REQUESTED** [review]
please change the tests so that the pass in the current situation and add commented out lines how it should work

**Review by dpakach — COMMENTED** [review]
tests are skipped on oc10 and ocis, make a version that passes for at least one of those backends

**Review by dpakach — COMMENTED** [review]
LGTM

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/12452/48/20
https://drone.owncloud.com/owncloud/web/12452/50/20

```
runsh: There were no unexpected failures.
runsh: Total unexpected passed scenarios throughout the test run:
webUIPreview/imageMediaViewer.feature:70
webUIPreview/imageMediaViewer.feature:76
runsh: Exit code: 1
```

That happens because the XGAPortrait and iPhone pipelines only run smokeTest scenarios. So these new scenarios do not actually get run, so `run.sh` thinks that they are "unexpected passes".

I will think about how to make `run.sh` smarter!

**Comment by phil-davis** [comment]
> I will think about how to make `run.sh` smarter

Not needed just yet. The XGA and iPhone pipelines only run `smokeTest` and currently (and probably in the future) the smoke-test scenarios are all ones that pass. So I added a commit that removes the `EXPECTED_FAILURES_FILE` environment variable from those pipelines.

**Comment by phil-davis** [comment]
@individual-it we have `EXPECTED_FAILURES_FILE` now, so do we also make bug-demo scenarios to show how it currently mis-behaves?

**Comment by phil-davis** [comment]
@swoichha my commit is gone. You can remove `EXPECTED_FAILURES_FILE` from the XGA and iPhone pipelines.

**Review by individual-it — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
