### PR TITLE
update yarn, improve caching

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
- update Yarn
- disable Yarn install scripts and allow for specific packages where needed (see package.json, `vue-concurrency` does weird stuff)
- add purge cache pipelines
- move playwright browsers to `.playwright` and cache them between pipelines
- cache artifacts from `yarn install` in `/tests/acceptance/.yarn`

## Related Issue

- -
## How Has This Been Tested?

- CI / locally

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/20087/14/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/20087/54/1
The following scenarios passed on retry:
- webUIFilesList/fileList.feature:15

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/20087/15/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
CI failed with Sonarcloud hickup, restarted

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/20147/14/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by ownclouders** [comment]
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/20147/65/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by wkloucek** [comment]
> CI failed with Sonarcloud hickup, restarted

@pascalwengerter Is now green

**Review by pascalwengerter — APPROVED** [review]
Changes lgtm, thanks for taking care!

**Pull request merged**
