### PR TITLE
[full-ci] Version bump for release v3.3.0

### PR DESCRIPTION
**Pull request by kulmann**
Version bump for release v3.3.0
Fixes https://github.com/owncloud/web/issues/5318

### CODE REVIEW

**Review by pascalwengerter — APPROVED** [review]
LGTM 🔥

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIOCISSharingBasic</strong> failed. The build is cancelled...</summary>

**Comment by micbar** [comment]
please also bump the version in sonar-project.properties

**Comment by pascalwengerter** [comment]
> please also bump the version in sonar-project.properties

Maybe it's too obvious but where exactly? Both oCIS and web only have a `sonar.projectVersion=1.0` and no other properties I find applicable without digging further

**Comment by micbar** [comment]
> > please also bump the version in sonar-project.properties
> 
> Maybe it's too obvious but where exactly? Both oCIS and web only have a `sonar.projectVersion=1.0` and no other properties I find applicable without digging further

yes. 1.0 was just a placeholder

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong>
The following scenarios passed on retry:
- webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:155

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong>
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternalRoot</strong>
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:353

**Pull request merged**
