### PR TITLE
[not-for-merge][tests-only] Trace link to GitHub

### PR DESCRIPTION
**Pull request by ScharfViktor**
## Description
What I want:

When e2e failed, we get message: 
`Result for smoke-test-OCIS https://drone.owncloud.com/owncloud/web/21254/10/1`
`💥 The acceptance tests pipeline failed. The build has been cancelled.`
`You can see the error trace here: https://drone.owncloud.com/owncloud/web/2021-12-21-12-55-00-Alice.zip`
`or download reports`

like:

image

What to do:

- [x] add notification to github if e2e test was failed
- [ ] upload reports to github comments like screenshots
- [ ] generate link `https://drone.owncloud.com/owncloud/web/2021-12-21-12-55-00-Alice.zip` to open trace

1. ### For notification to github we need to add into steps `def smokeTests ` two steps. I did this for OC10 (for example)):
- `buildGithubCommentForBuildStopped(name)` - stop build, add notification to comments.file
- `githubComment(name)` - make notification to github with droneBuildLink + coments.file

2. ### Add error trace or video to github. After failed tests it creates in "reports/e2e/playwright/"
- add `def uploadsErrorTrace()` like uploadScreenshots. Use S3 plugin and upload files to your bucket
```
def uploadsErrorTrace():
		    return [{
		        "name": "upload-errorTrace",
		        "image": "plugins/s3",
		        "pull": "if-not-exists",
		        "settings": {
		            "bucket": "owncloud",
		            "endpoint": {
		                "from_secret": "cache_s3_endpoint",
		            },
		            "path_style": True,
		            "source": "%s/tests/reports/e2e/playwright/tracing" % dir["web"],
		            "strip_prefix": "%s/tests/reports/e2e/playwright/tracing" % dir["web"],
		            "target": "/web/screenshots/${DRONE_BUILD_NUMBER}",  
		        },
		        "environment": {
		            "AWS_ACCESS_KEY_ID": {
		                "from_secret": "cache_s3_access_key",
		            },
		            "AWS_SECRET_ACCESS_KEY": {
		                "from_secret": "cache_s3_secret_key",
		            },
		        },
		        "when": {
		            "status": [
		                "failure",
		            ],
		            "event": [
		                "pull_request",
		            ],
		        },
		    }] 

```
- add `def buildGithubComment` - add comment to github

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>smoke-tests</strong> https://drone.owncloud.com/owncloud/web/21271/11/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>smoke-tests</strong> https://drone.owncloud.com/owncloud/web/21288/11/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>smoke-tests</strong> https://drone.owncloud.com/owncloud/web/21288/10/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>smoke-tests</strong> https://drone.owncloud.com/owncloud/web/21291/11/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>smoke-tests</strong> https://drone.owncloud.com/owncloud/web/21291/10/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>smoke-tests</strong> https://drone.owncloud.com/owncloud/web/21292/11/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>smoke-tests</strong> https://drone.owncloud.com/owncloud/web/21292/10/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>smoke-tests</strong> https://drone.owncloud.com/owncloud/web/21354/10/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>smoke-tests</strong> https://drone.owncloud.com/owncloud/web/21354/11/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>smoke-tests</strong> https://drone.owncloud.com/owncloud/web/21356/11/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>smoke-tests</strong> https://drone.owncloud.com/owncloud/web/21356/10/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>smoke-tests</strong> https://drone.owncloud.com/owncloud/web/21357/11/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>smoke-tests</strong> https://drone.owncloud.com/owncloud/web/21357/10/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by fschade** [comment]
@ScharfViktor we had some last minute changes in #6166, please rebase and build the notifications based on that.

**Comment by ScharfViktor** [comment]
I opened a new PR because there were troubles with rebase: https://github.com/owncloud/web/pull/6206

**Pull request closed without merging**
