### PR TITLE
Fix debounced search

### PR DESCRIPTION
**Pull request by JanAckermann**
## Related Issue

- Fixes https://github.com/owncloud/web/issues/7723

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by JammingBen — APPROVED** [review]

**Review by JammingBen — APPROVED** [review]

**Comment by ScharfViktor** [comment]
tests fails here: https://github.com/owncloud/web/blob/master/tests/e2e/support/objects/app-files/resource/actions.ts#L517 
strange that `allInnerTexts()` returns empty array although the selector has not changed and `locator.innerText()` for one locator works correctly (returns new-lorem\n.txt) @SwikritiT do you have ideas what is wrong?

**Review by kulmann — APPROVED** [review]
👍

**Comment by kulmann** [comment]
> tests fails here: https://github.com/owncloud/web/blob/master/tests/e2e/support/objects/app-files/resource/actions.ts#L517
> strange that `allInnerTexts()` returns empty array although the selector has not changed and `locator.innerText()` for one locator works correctly (returns new-lorem\n.txt) @SwikritiT do you have ideas what is wrong?

The change in this PR is that the network request gets send after no keyboard search input happened for 200ms. Maybe there is some waiting period needed in the tests?

**Comment by JanAckermann** [comment]
Probable true, same error applied to unit tests, this is why I mocked the denounce there.

**Comment by ScharfViktor** [comment]
> The change in this PR is that the network request gets send after no keyboard search input happened for 200ms. Maybe there is some waiting period needed in the tests?

Fixed, can I do commit here?

**Comment by kulmann** [comment]
> > The change in this PR is that the network request gets send after no keyboard search input happened for 200ms. Maybe there is some waiting period needed in the tests?
> 
> Fixed, can I do commit here?

Of course, please go ahead!

**Comment by ScharfViktor** [comment]
as far as I remember, search in current folder call method "PROPFIND" ?

- create `folder1/file1`
- try to find `file1` in personal space - REPORT request
- open folder `folder1` and try to find `file1` Expected- PROPFIND request??

I don't know at what point it stopped working, probably not here

**Comment by JanAckermann** [comment]
@ScharfViktor No, we removed the propfind and always call the report

**Pull request merged**
