### PR TITLE
[tests-only][full-ci]Bump latest ocis commit to web master

### PR DESCRIPTION
**Pull request by SagarGi**
### Description
Bump ocis latest commit to web-master

for generating ocis we need to provide this environment but did not work with node 16 but if we use node 18 then this variable is not required.

```json

            "environment": {
                "NODE_OPTION": "--openssl-legacy-provider",
            },
```

### Related Issue:
https://github.com/owncloud/QA/issues/805

### CODE REVIEW

**Comment by SagarGi** [comment]
CC @saw-jan @individual-it

**Review by individual-it — COMMENTED** [review]
@kulmann any reason not to use node18?

**Comment by ScharfViktor** [comment]
I wanted to bump ocis commit after merging https://github.com/owncloud/ocis/pull/5531
maybe could we combine?

**Comment by saw-jan** [comment]
> I wanted to bump ocis commit after merging [owncloud/ocis#5531](https://github.com/owncloud/ocis/pull/5531) maybe could we combine?

Yeah, we can close this one here and do the bump in PR https://github.com/owncloud/web/pull/8779

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/34601/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34601/tracing/file-alice-2023-4-11-04-01-22.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34601/tracing/file-brian-2023-4-11-04-01-47.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34601/tracing/folder-alice-2023-4-11-03-59-48.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34601/tracing/folder-brian-2023-4-11-04-00-01.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34601/tracing/unstructured-collection-of-testable-space-interactions-alice-2023-4-11-04-05-38.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34601/tracing/unstructured-collection-of-testable-space-interactions-anonymous-2023-4-11-04-06-25.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34601/tracing/unstructured-collection-of-testable-space-interactions-brian-2023-4-11-04-06-26.zip 


</p></details>

**Comment by SagarGi** [comment]
The can be closed since the bump is done in this PR https://github.com/owncloud/web/pull/8779

**Pull request closed without merging**
