### PR TITLE
Prevent self deletion

### PR DESCRIPTION
**Pull request by JanAckermann**
## Related Issue

- Fixes https://github.com/owncloud/web/issues/7955

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by kulmann — COMMENTED** [review]
Could you cover the differentiation in unit tests?

**Comment by JanAckermann** [comment]
@dschmidt sure, can you ping me after its done?

**Comment by JanAckermann** [comment]
@kulmann sure! Done

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublic2</strong> https://drone.owncloud.com/owncloud/web/29889/37/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicExpire-shareByPublicLinkExpiringLinks_feature-L62.png
  


</p></details>
:boom: The oC10SharingPublic2 tests pipeline failed. The build has been cancelled.

**Comment by JanAckermann** [comment]
> Results for **oC10SharingPublic2** https://drone.owncloud.com/owncloud/web/29889/37/1
> 
>  The acceptance tests failed on retry. Please find the screenshots inside ...
>  The oC10SharingPublic2 tests pipeline failed. The build has been cancelled.

Ughhh

**Review by kulmann — CHANGES_REQUESTED** [review]
Please add a `bugfix` changelog item. Otherwise good to go 👍

**Review by kulmann — APPROVED** [review]
👍

**Pull request merged**
