### PR TITLE
[full-ci] Pass folderLink and parentFolderLink to OCResource component

### PR DESCRIPTION
**Pull request by JanAckermann**
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingFolderPermissions</strong> https://drone.owncloud.com/owncloud/web/22430/26/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers_feature-L61.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers_feature-L62.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers_feature-L63.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers_feature-L64.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers_feature-L65.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers_feature-L66.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingFolderPermissions</strong> https://drone.owncloud.com/owncloud/web/22432/26/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers_feature-L61.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers_feature-L62.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers_feature-L63.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers_feature-L64.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers_feature-L65.png
  

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers_feature-L66.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Sharing2</strong> https://drone.owncloud.com/owncloud/web/22432/24/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIResharingToRoot-reshareUsers_feature-L178.png
  

### webUIResharingToRoot-reshareUsers_feature-L88.png
  

### webUIResharingToRoot-reshareUsers_feature-L89.png
  

### webUIResharingToRoot-reshareUsers_feature-L90.png
  

### webUIResharingToRoot-reshareUsers_feature-L91.png
  

### webUIResharingToRoot-reshareUsers_feature-L92.png
  

### webUIResharingToRoot-reshareUsers_feature-L95.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPermToRoot</strong> https://drone.owncloud.com/owncloud/web/22432/35/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPermissionToRoot-sharePermissionsUsers_feature-L112.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers_feature-L113.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers_feature-L17.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers_feature-L32.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers_feature-L47.png
  

### webUISharingPermissionToRoot-sharePermissionsUsers_feature-L62.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPerm3</strong> https://drone.owncloud.com/owncloud/web/22432/65/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L60.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L61.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L62.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L63.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L64.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L65.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPermission</strong> https://drone.owncloud.com/owncloud/web/22432/34/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L60.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L61.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L62.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L63.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L64.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L65.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L66.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L67.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L68.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L69.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L70.png
  

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L71.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers_feature-L121.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers_feature-L122.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers_feature-L21.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers_feature-L36.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers_feature-L52.png
  

### webUISharingPermissionsUsers-sharePermissionsUsers_feature-L68.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Resharing</strong> https://drone.owncloud.com/owncloud/web/22432/22/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIResharing1-reshareUsers_feature-L166.png
  

### webUIResharing1-reshareUsers_feature-L18.png
  

### webUIResharing2-reshareUsers_feature-L130.png
  

### webUIResharing2-reshareUsers_feature-L131.png
  

### webUIResharing2-reshareUsers_feature-L132.png
  

### webUIResharing2-reshareUsers_feature-L133.png
  

### webUIResharing2-reshareUsers_feature-L134.png
  


</p></details>

**Review by pascalwengerter — APPROVED** [review]
Happy if Drone is 🥸

**Comment by ownclouders** [comment]
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/22435/69/1
The following scenarios passed on retry:
- webUIUserJourney/journey1.feature:11

**Pull request merged**
