### PR TITLE
[full-ci] Design polishing

### PR DESCRIPTION
**Pull request by JammingBen**
## Related Issue
- Fixes https://github.com/owncloud/web/issues/7676
- Fixes https://github.com/owncloud/web/issues/6705
- Works towards https://github.com/owncloud/web/issues/7693
- Fixes https://github.com/owncloud/web/issues/7694
- Fixes https://github.com/owncloud/web/issues/7685
- Addresses several issues reported in https://github.com/owncloud/web/issues/7525

## Screenshots:

* Redesign spaces overview
  * Remove text and border line
  * Fix breadcrumb alignment
  * Show icon for sidebar
  * Use fixed width for cards
  * Align "Create Space"-button with "New" button in Personal Space
  * Use `file-type="line"` for members icon
  
image

---

* Align spacing in left sidebar & breadcrumbs:
  * Horizontally align breadcrumbs with chevron in the left sidebar
  * Horizontally align the entries of the left sidebar with "Create"-Actions
  * Fix horizontal alignment of breadcrumbs and chevrons within
  
image

---

* Reduce spacing between actions above file list

image

---

* Space front page
  * Show default image on space overview
  * Give image a fixed width
  * Change default description to "Here you can add a description for this Space."
  * Make subtitle bold

image

---

* Fix vertical height of the "There are no resources in this folder"-message (there was a vertical scrollbar before)
* Adjust texts for enabling/disabling spaces (see https://github.com/owncloud/web/issues/7685)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/28582/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/28582/tracing/unstructured-collection-of-testable-space-interactions-alice-2022-9-23-12-26-32.zip 


</p></details>
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.

**Comment by tbsbdr** [comment]
Please note: the Space name gets truncated too early imo. if there is enough space, it should not get truncated

**Comment by kulmann** [comment]
Does it also fix https://github.com/owncloud/web/issues/7694  ?

**Comment by kulmann** [comment]
and https://github.com/owncloud/web/issues/7693 ?

**Review by kulmann — APPROVED** [review]
Nice, looks much better. Thank you!
The no content message still is not ideal. E.g. in a project space with an image and a long description I get a quite long scrollbar. But that can be solved in a separate PR... I changed the PR description to not claim to fix https://github.com/owncloud/web/issues/7693 anymore.

**Pull request merged**
