### PR TITLE
[full-ci] Prepare v4.8.0 release

### LINKED ISSUE #6178: Release 4.8.0
## Waiting for
- #6136
- #6176

## Release checklist
- [x] pin release issue @pascalwengerter 
- [X] prepare release rc: @pascalwengerter
  - [X] create a branch `release-4.8.0` @pascalwengerter
  - [X] update the version in `packages/web-integration-oc10/appinfo/info.xml` @pascalwengerter
  - [X] update the version in `package.json` @pascalwengerter
  - [X] update the version in `sonar-project.properties` @pascalwengerter 
  - [X] move changelog/unreleased/* to changelog/VERSION_YYYY-MM-DD @pascalwengerter
  - [X] update the ocis commit id in `.drone.env` to the most recent one from ocis master (let's see how it goes)
  - [X]  commit, push and create **draft** PR (#6180) for this branch @pascalwengerter
- [x] create pre release tag `v4.8.0-rc1` from the release branch @pascalwengerter 
- [x] smoke test 
  - [x] against oCIS @pascalwengerter 
  - [x] against oc10 standalone @pascalwengerter 
  - [x] against oc10 as app installation @kulmann 
  - [x] against oCIS wopi example / app provider @kulmann 
- [ ] if needed, fix issues or write down known issues 
- [x] update `YYYY-MM-DD` to current date in `changelog/VERSION_YYYY-MM-DD`
- [x] Make sure translations are up to date by updating them in Transifex and restarting translation sync job https://drone.owncloud.com/owncloud/translation-sync/ @pascalwengerter
- repeat above steps if a new rc is needed
- [x] Run translations sync job once again
- [x] go to the releases section and click `Draft a new Release`. Use `v4.8.0` as a tag (the v prefix is important) and `4.8.0` as name and publish it
- [ ] ping in internal #btr channel to create a signed release and ask them to upload it to a) the github release page, b) marketplace.owncloud.com, c) portal.owncloud.com, d) customer.owncloud.com
- [ ] merge release branch https://github.com/owncloud/web/pull/6180 back to master (CI must be green)

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Related Issue
- Fixes #6178

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/21244/53/1
The following scenarios passed on retry:
- webUISharingAcceptShares/acceptShares.feature:111

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21322/15/1
The following scenarios passed on retry:
- webUISharingAcceptShares/acceptShares.feature:94

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/21329/53/1
The following scenarios passed on retry:
- webUISharingAcceptShares/acceptShares.feature:94

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21350/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Review by kulmann — APPROVED** [review]
LGTM 👍

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21359/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Pull request merged**
