### PR TITLE
[Tests-Only][full-ci]Adjust the previously "not-implemented" test steps in feature files

### PR DESCRIPTION
**Pull request by jasson99**
## Description
This PR adjusts the tests steps in the feature files which were not implemented previously.

## Related Issue
- https://github.com/owncloud/web/issues/5411

## Motivation and Context
Some of the test scenarios which were either skipped or in the expected failures file, had some unimplemented test steps. It could be mainly because the test steps were edited or adjusted for the unskipped tests, but were left as they were for the ones which were skipped or anyway expected to fial. Leaving these steps as they were currently will never check the true behaviour of the product.

## How Has This Been Tested?
- CI
- In ocis: https://github.com/owncloud/ocis/pull/2257

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17058/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/17058/49/1
The following scenarios passed on retry:
- webUICreateFilesFolders/createFolders.feature:22

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/17065/9/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:110

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17065/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/17065/38/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17068/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oCISRename</strong> https://drone.owncloud.com/owncloud/web/17073/46/1
The following scenarios passed on retry:
- webUIRenameFiles/renameFiles.feature:43

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17073/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17118/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oC10XGAPortrait1</strong> https://drone.owncloud.com/owncloud/web/17118/40/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:59

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17126/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by phil-davis** [comment]
@jasson99 in PR #5469 I removed the admin-settings scenarios, and split the "Basic" test pipelines into "Basic" and :Locks" to reduce the CI run time.

That has made conflicts for you!

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17170/49/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17181/49/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Review by dpakach — APPROVED** [review]
lgtm!

**Review by phil-davis — APPROVED** [review]
LGTM - when comments and/or tags are implmented, we can write the scenarios to test those.

**Pull request merged**
