### PR TITLE
[tests-only] [full-ci] Adjust GitHub comments flow 2 force fails

### PR DESCRIPTION
**Pull request by phil-davis**
This is on top of PR #5191 to demonstrate what happens when some test scenario(s) fails.

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15916/

<p>


### webUIFavorites-unfavoriteFile-feature-13.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15916/

<p>


### webUIFavorites-unfavoriteFile-feature-13.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15916/

<p>


### webUIAccount-accountInformation-feature-20.png
  

### webUILogin-adminBlocksUser-feature-20.png
  

### webUIPreview-imageMediaViewer-feature-140.png
  

### webUIPreview-imageMediaViewer-feature-158.png
  

### webUIPreview-imageMediaViewer-feature-83.png
  

### webUIPreview-imageMediaViewer-feature-90.png
  


</p></details>

**Comment by phil-davis** [comment]
Looks correct - https://drone.owncloud.com/owncloud/web/15916/6/18
The step to build the VRT test comment now exits early correctly, because there are no Visual Regression Test diffs to process.

**Pull request closed without merging**
