### PR TITLE
ods bump and theming docfix

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Fixes a typo in the theme template & bumps ODS to `v6.0.2`, bringing lazily loaded avatar images & themable row heights

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>oc10-integration-notifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15367/

<p>


### webUISharingNotifications-shareWithUsers-feature-40.png
  

### webUISharingNotifications-shareWithUsers-feature-53.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-40.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-53.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Visual regression tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15367/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15367/

<p>


### webUIFilesList-fileList-feature-15.png
  

### webUIFilesList-sort-feature-51.png
  

### webUIFilesList-sort-feature-72.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15367/

<p>


### webUISharingInternalGroups-shareWithGroups-feature-260.png
  

### webUISharingInternalGroups-shareWithGroups-feature-72.png
  

### webUISharingInternalGroups-shareWithGroups-feature-73.png
  

### webUISharingInternalGroups-shareWithGroups-feature-74.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15367/

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups-feature-234.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-69.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-70.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-71.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsers</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15367/

<p>


### webUISharingInternalUsersShareWithPage-shareWithUsers-feature-31.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15367/

<p>


### webUISharingAcceptShares-acceptShares-feature-100.png
  

### webUISharingAcceptShares-acceptShares-feature-116.png
  

### webUISharingAcceptShares-acceptShares-feature-135.png
  

### webUISharingAcceptShares-acceptShares-feature-16.png
  

### webUISharingAcceptShares-acceptShares-feature-203.png
  

### webUISharingAcceptShares-acceptShares-feature-218.png
  

### webUISharingAcceptShares-acceptShares-feature-235.png
  

### webUISharingAcceptShares-acceptShares-feature-78.png
  

### webUISharingAcceptShares-acceptShares-feature-89.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-110.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-131.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-143.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-15.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-158.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-235.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-245.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-255.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-267.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-282.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-299.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-31.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-315.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-357.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-366.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-379.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-397.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-50.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-72.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-90.png
  


</p></details>

**Review by kulmann — APPROVED** [review]
LGTM

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15369/

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups-feature-69.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-70.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-71.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15369/

<p>


### webUISharingInternalGroups-shareWithGroups-feature-72.png
  

### webUISharingInternalGroups-shareWithGroups-feature-73.png
  

### webUISharingInternalGroups-shareWithGroups-feature-74.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Visual regression tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15382/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15382/

<p>


### webUIFilesList-fileList-feature-15.png
  

### webUIFilesList-sort-feature-51.png
  

### webUIFilesList-sort-feature-72.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15382/

<p>


### webUISharingInternalGroups-shareWithGroups-feature-72.png
  

### webUISharingInternalGroups-shareWithGroups-feature-73.png
  

### webUISharingInternalGroups-shareWithGroups-feature-74.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15382/

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups-feature-69.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-70.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-71.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15392/

<p>


### webUILogin-adminBlocksUser-feature-20.png
  

### webUIPreview-imageMediaViewer-feature-140.png
  

### webUIPreview-imageMediaViewer-feature-158.png
  

### webUIPreview-imageMediaViewer-feature-83.png
  

### webUIPreview-imageMediaViewer-feature-90.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15392/

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups-feature-69.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-70.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-71.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15401/

<p>


### webUISharingInternalGroups-shareWithGroups-feature-72.png
  

### webUISharingInternalGroups-shareWithGroups-feature-73.png
  

### webUISharingInternalGroups-shareWithGroups-feature-74.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Move</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15414/

<p>


### webUIMoveFilesFolders-moveFiles-feature-105.png
  


</p></details>

**Pull request merged**
