### PR TITLE
refactor: user action modals

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
Move several modal action handlers from `Users.vue` into their own components where they belong. This a) cleans up the component nicely and b) prevents the logic from being spread all over the place.

Affected actions:

* "Create user"-action moved into `useUserActionsCreateUser.ts`. It opens the `CreateUserModal.vue` which holds all the logic
* "Edit login"-action handler move into `EditLoginModal.vue`
* "Add to groups"-action handler move into `AddToGroupsModal.vue`
* "Remove from groups"-action handler move into `RemoveFromGroupsModal.vue`

Also adds unit test for all these things.

This PR is best reviewed by its individual commits.

## Related Issue

- refs https://github.com/owncloud/web/issues/10095

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

### CODE REVIEW

**Review by dschmidt — COMMENTED** [review]
Great!

It can be another iteration, but I would like to get rid of the store actions triggering in the dialog components, I think the modal should handle that automatically based on promises returned from onCancel and onConfirm.

**Comment by JammingBen** [comment]
> Great!
> 
> It can be another iteration, but I would like to get rid of the store actions triggering in the dialog components, I think the modal should handle that automatically based on promises returned from onCancel and onConfirm.

You mean `store.dispatch('hideModal')` right? I agree that this would be nice, probably easy to do as well. I'd rather do in in a follow-up though.

**Comment by dschmidt** [comment]
yep, as I said - can be in another iteration

**Review by JanAckermann — APPROVED** [review]
🤩

**Pull request merged**
