### PR TITLE
[full-ci] Improve app loading

### PR DESCRIPTION
**Pull request by dschmidt**
## Description

BASED ON #9075 

Externalize web-pkg and web-client 
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/35917/12/1
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.

**Review by kulmann — APPROVED** [review]
nice!

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/35943/11/1
:boom: The e2e-oc10 tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS-2</strong> https://drone.owncloud.com/owncloud/web/36395/13/1
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS-1</strong> https://drone.owncloud.com/owncloud/web/36395/12/1
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.

**Pull request merged**
