### PR TITLE
Accommodate sticky sidebar header

### LINKED ISSUE #2019: Header of sidebar needs to be sticky
## Description
When the user scrolls in the sidebar the header containing icon, name, size, mdate and tabs needs to stay on the screen.

## Motivation
If the header stays sticky the user can still easily see what item he's got the sidebar opened for and can easily navigate between different tabs.

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Sticky sidebar header (changes in `web` are minimal and just reflect what has changed in the ODS)

## Related Issue
- Fixes #2019

## Motivation and Context
See changelog item in https://github.com/owncloud/owncloud-design-system/pull/1384 and #2019 

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait2</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>iPhone2</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait1-Notifications</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingExternal</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>oc10-integration-notifications</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingExternalRoot</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>IntegrationApp2</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersBlacklisted</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16297/

<p>


### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-26.png
  

### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-44.png
  

### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-62.png
  

### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-80.png
  

### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-92.png
  


</p></details>
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersBlacklisted</strong> failed. The build is cancelled...</summary>

**Review by fschade — APPROVED** [review]
🤖 nice

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. The build is cancelled...</summary>

**Review by kulmann — APPROVED** [review]

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIFiles1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16471/

<p>


### webUIMarkdownEditor-markdownFile-feature-26.png
  


</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles1</strong> failed. The build is cancelled...</summary>

**Pull request merged**
