### PR TITLE
[tests-only][full-ci] Remove the tests already present in middleware from webdavContext

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description
This PR removes the tests step already present in middleware and reactors the existing test step to use middleware's.

## Related Issue

- Part of https://github.com/owncloud/web/issues/6111

## How Has This Been Tested?

- locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21732/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles2</strong> https://drone.owncloud.com/owncloud/web/21972/56/1
The following scenarios passed on retry:
- webUIMarkdownEditor/markdownFile.feature:21

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp1</strong> https://drone.owncloud.com/owncloud/web/21972/68/1
The following scenarios passed on retry:
- webUICreateFilesFolders/createFolderEdgeCases.feature:60
- webUICreateFilesFolders/createFolderEdgeCases.feature:61

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21977/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingSharingInd</strong> https://drone.owncloud.com/owncloud/web/21977/33/1
The following scenarios passed on retry:
- webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:17

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp1</strong> https://drone.owncloud.com/owncloud/web/21977/68/1
The following scenarios passed on retry:
- webUIPrivateLinks/accessingPrivateLinks.feature:17

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/21977/40/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:106

**Review by phil-davis — APPROVED** [review]
LGTM

**Pull request merged**
