### PR TITLE
[full-ci] Import owncloud-design-system

### PR DESCRIPTION
**Pull request by dschmidt**
This PR imports the owncloud-design-system from https://github.com/owncloud/owncloud-design-system/pull/2367 and renames it to `@ownclouders/design-system`, to be consistent with `@ownclouders/web-pkg` and `@ownclouders/web-client`.
It's built as part of the regular rollup dev server and production builds, so no separate build step is neccessary anymore.

The documentation built is unfortunately broken, but we decided to postpone fixing it a bit, as we still have to sort out publishing separate packages from our monorepo. We probably just need to make vue-styleguidist/webpack aware of TypeScript and everything should work again.

This PR is standing on shoulders of giants, mainly @pascalwengerter and @fschade.
Kudos for preparing https://github.com/owncloud/owncloud-design-system/pull/1888/files, took a lot of inspiration from that one.

# Tasks
- [x] Make ODS build in Rollup with the rest of the application
- [x] Integrate Tests
- [x] Rename to `@ownclouders/design-system`
- [x] Cleanup

# Followup Tasks
- [ ] Check/migrate translations in transifex
- [ ] Add documentation generation to .drone.star
- [ ] Prepare Standalone Builds 
- [ ] Vite :) 
- [ ] Vue 3 :)

# further reference
https://github.com/owncloud/owncloud-design-system/compare/master...migrate-to-vue-3

### CODE REVIEW

**Comment by pascalwengerter** [comment]
@fschade @dschmidt this isn't in a usable state yet I reckon?

**Comment by dschmidt** [comment]
Kind of I guess, give it a try.

You need to run build:system and maybe need to restart rollup... but haven't tested it myself

**Comment by ownclouders** [comment]
Results for <strong>oC10Files5</strong> https://drone.owncloud.com/owncloud/web/29921/21/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIFilesActionMenu-versions_feature-L15.png
  

### webUIFilesActionMenu-versions_feature-L26.png
  

### webUIFilesActionMenu-versions_feature-L46.png
  

### webUIFilesActionMenu-versions_feature-L74.png
  

### webUIFilesActionMenu-versions_feature-L90.png
  


</p></details>
:boom: The oC10Files5 tests pipeline failed. The build has been cancelled.

**Review by kulmann — CHANGES_REQUESTED** [review]
Requesting changes, so that this PR can't be merged accidentally. The design system has contradicting license information in its repo. There is a license file which states Apache2.0, and the package.json claims that its licensed under AGPL-3.0. Needs to be clarified before we can merge.

**Comment by kulmann** [comment]
> Requesting changes, so that this PR can't be merged accidentally. The design system has contradicting license information in its repo. There is a license file which states Apache2.0, and the package.json claims that its licensed under AGPL-3.0. Needs to be clarified before we can merge.

Has been clarified internally with @hodyroff - there was the idea of moving towards Apache2.0 in the design system, but apparently never executed completely/correctly and the CLA bot for the AGPL was always active. Moving the design system over to the web monorepo (= this PR) will revert the incomplete license transition back to AGPL.

**Review by kulmann — APPROVED** [review]

**Pull request merged**
