### PR TITLE
Add robots.txt file

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Add the robots.txt file

## Related Issue
https://github.com/owncloud/ocis/issues/1314

## How Has This Been Tested?
Checked with ocis-web without pulling fresh assets. After generating the embed files and building ocis, the "/robots.txt" is accessible with the contents.
It's expected that a new web release will put everything into the right place.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by kulmann** [comment]
What about an integration into oc10 with the web app? Does the robots.txt of oc10 apply then or do we need to serve this robots.txt there as well? `robots.txt` would need to be added to the array in https://github.com/owncloud/web/blob/05f8735a3210116f0fff0b40170846ee4cdec1d1/packages/web-integration-oc10/lib/Controller/FilesController.php#L81 then.

**Comment by ownclouders** [comment]
Results for <strong>oC10iPhone2</strong> https://drone.owncloud.com/owncloud/web/18756/46/1
The following scenarios passed on retry:
- webUITrashbinRestore/trashbinRestore.feature:14

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/18756/12/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:36

**Comment by fschade** [comment]
Thanks, I think I misses a copy step here 

https://github.com/owncloud/web/blob/94ed5427e90e696d2a573b7720020ac33a427c0c/rollup.config.js#L66

**Comment by jvillafanez** [comment]
I don't think it's needed for the OC10 integration. OC10 already has its own robots.txt file so it's ownCloud the one that should serve the file.
In addition, the robots.txt should be placed in the root of the of the server, so it should be placed in `https://my.server/robots.txt`, and that URL is controlled by OC10, so the web app shouldn't need to bother

**Review by kulmann — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18761/28/1
The following scenarios passed on retry:
- webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:154

**Pull request merged**
