### PR TITLE
[unit-tests] added unit tests for SharedWithMe view

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
- added unit tests for 'SharedWithMe` view
(will be rebased after the dependent branch is merged on master)

## Related Issue
- Part of #5237 

## How Has This Been Tested?

- `yarn test:unit`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- #5697

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10iPhone2</strong> https://drone.owncloud.com/owncloud/web/18528/46/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
@kiranparajuli589 could you split this one up in multiple PRs all covering individual components, please? Otherwise it's really hard to review (and thus will take longer to merge)

**Comment by pascalwengerter** [comment]
@individual-it this seems like @kiranparajuli589 branched it off from other branches that contain different files. Could you take a look and extract the relevant files and either rebase this PR or open a new one? :) Thanks!

**Comment by kiranparajuli589** [comment]
> @individual-it this seems like @kiranparajuli589 branched it off from other branches that contain different files. Could you take a look and extract the relevant files and either rebase this PR or open a new one? :) Thanks!

@pascalwengerter, there was some changed code in `views.setup.js` which was also useful here. Can we chain this PR with `unittest-views-location-picker`. This will be in draft until the base PR is merged to the `master`?

**Comment by pascalwengerter** [comment]
@kiranparajuli589 that's great news! Could I still ask you to split up this PR into separate ones based on the tested views? I'm not really keen on reviewing a ~2.000 line PR 🥴

**Comment by kiranparajuli589** [comment]
> @kiranparajuli589 that's great news! Could I still ask you to split up this PR into separate ones based on the tested views? I'm not really keen on reviewing a ~2.000 line PR woozy_face

yes sure :), actually tests for `SharedWithMe` view is already done, so the PR title is also not correct now.

remaining views to test:
- SharedWithOthers
- Trashbin
- PublicFiles
also see (issue)[https://github.com/owncloud/web/issues/5237] for more details

If it's good to add tests for these views now, I can add them (in separate PRs).

cc @pascalwengerter

**Comment by kiranparajuli589** [comment]
closed because the tests will be splitted for different views

**Comment by pascalwengerter** [comment]
@kiranparajuli589 thanks for updating this PR. Could I ask you to do the splitting and open separate PRs for the applicable views?

**Pull request closed without merging**
