### PR TITLE
Bring back the permissions field in public links editing

### PR DESCRIPTION
**Pull request by kulmann**
## Description
We accidentally removed the `permissions` field in the public links editing form. This PR brings it back.

## How Has This Been Tested?

- drone

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by refs — APPROVED** [review]

**Comment by kulmann** [comment]
@phil-davis @individual-it might be worth to look into this. Since we have a lot of tests regarding different share permissions, I don't get why this bug was not blowing up in CI. 😅

**Comment by kulmann** [comment]
@LukasHirt fyi I placed the changelog item directly in the respective versioned folder so that we can tag a beta4 after this PR is merged, without needing another release preparation PR. Needs fixing in ocis as soon as possible IMO.

**Comment by phil-davis** [comment]
> @phil-davis @individual-it might be worth to look into this. Since we have a lot of tests regarding different share permissions, I don't get why this bug was not blowing up in CI.

Agree - see issue #4426 - my guess is that there is actually not much test coverage of the public links UI. That issue needs looking at.

**Review by micbar — APPROVED** [review]

**Comment by phil-davis** [comment]
Some public link test scenarios failed: https://drone.owncloud.com/owncloud/web/12298/39/20

There are test scenarios that try to delete the password on an existing public link share. They expect to get a message "Passwords are enforced for link shares" But the message is not found.

Maybe the DOM elements have changed now that the `permissions` filed is back, and the tests need to be adjusted to find the expected error text. Or maybe there is a real problem. Needs investigating.

**Comment by kulmann** [comment]
The permissions were not correctly loaded upon creation of the vue component. Fixed now. Good that the test suite caught that 😎

**Review by butonic — APPROVED** [review]

**Pull request merged**
