### PR TITLE
Feature: Visually highlight uploaded/created files

### LINKED ISSUE #5967: Highlighting uploaded or new files
## Acceptance Criterias
Same behavior as in oc10
- **Create new folder**:
  - [ ] insert new folder in current sort order
  - [X] highlight new folder
  - [ ] do NOT add the new folder to the selection model
  - [ ] do NOT scroll to the newly created folder anymore!
  - [ ] show a toast about successful creation of the new folder: "[folder name] successfully created."
- **Upload**: (one or many files, current folder or different folder)
  - [x] highlight uploaded file
  - [ ] don't add the uploaded files to the selection model
  - [ ] don't scroll to highlighted file(s)
  - [ ] show a toast if upload was successful: "[Filename] successfully uploaded."
  - [ ] double check if file info in the list-footer gets updated

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Pragmatically supersedes #5999 since that one had some weird git history stuff that was a paint to rebase. Cherry-picked the relevant commit

## Related Issue
- Fixes #5967

## How Has This Been Tested?
- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes
- [X] New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added

### CODE REVIEW

**Comment by pascalwengerter** [comment]
This needs a new approach. 

- Filtering old&new resources in a watcher doesn't work on initial pageload (since all resources are "new")
- Filtering old&new resources doesn't work when using pagination (since "new" files appear, but not uploaded/created ones)
- Having yet another watcher on the files table fries my browser tab (FF on Ubuntu has issues already, this makes it worse), plus a lot of selector errors in the console

**Comment by fschade** [comment]
@pascalwengerter, i updated the logic a bit,
@kulmann can we have a review on this, im too much involved for an objective review.

**Review by kulmann — CHANGES_REQUESTED** [review]
Same functionality also needed for public files

**Comment by ownclouders** [comment]
Results for <strong>oC10XGAPortrait2</strong> https://drone.owncloud.com/owncloud/web/20258/45/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by fschade** [comment]
closing in favor of #6020

**Pull request closed without merging**
