### PR TITLE
[full-ci] Rework navigation for mobile devices

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
Adds a proper navigation for mobile devices <640px.

Also introduced proper types for nav items:

* `AppNavigationItem`: the type for `navItems` that are being provided by each app.
* `NavItem`: a slight variation of `AppNavigationItem` which is being used by some components in the runtime itself. The difference is that it has an `active` flag and the `name` property is always a `string`.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/8557
- Fixes https://github.com/owncloud/web/issues/7253
- Fixes https://github.com/owncloud/web/issues/3774
- Fixes https://github.com/owncloud/ocis/issues/5289

## Screenshots

image

image

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/34438/48/1
:boom: The oC10iPhone2 tests pipeline failed. The build has been cancelled.

**Comment by JammingBen** [comment]
@kulmann I skipped some oC10 tests that were running on mobile resolution. IMO it's not worth fixing them, particularly because we had them for oC10 only. Do you agree?

**Comment by kulmann** [comment]
> @kulmann I skipped some oC10 tests that were running on mobile resolution. IMO it's not worth fixing them, particularly because we had them for oC10 only. Do you agree?

Yep, fine by me :-)

**Review by dschmidt — APPROVED** [review]
Great, love the feature and that you properly typed everything.

When the back button for single trash bin instances is fixed: :shipit:

**Review by dschmidt — APPROVED** [review]

**Pull request merged**
