### PR TITLE
update lockfile and fix date calculation in acceptance tests

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Update the lockfile and fix the failing test due to the error in date calculation in acceptance tests
```
AssertionError [ERR_ASSERTION]: Expected: Expiration date field with Sept 1, 2021, but found Sep 1, 2021
1888 | + expected - actual
1889 |  
1890 | -Sep 1, 2021
1891 | +Sept 1, 2021
1892
```

## Related Issue

- Fixes Failing CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by individual-it — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublicExpireAndRoles</strong> https://drone.owncloud.com/owncloud/web/18561/35/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18563/24/1
The following scenarios passed on retry:
- webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature:104

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublicExpireAndRoles</strong> https://drone.owncloud.com/owncloud/web/18563/35/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublicExpireAndRoles</strong> https://drone.owncloud.com/owncloud/web/18564/35/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Review by jasson99 — COMMENTED** [review]
LGTM.

**Pull request merged**
