### PR TITLE
Cleanup & fixes

### PR DESCRIPTION
**Pull request by elizavetaRa**
## Description
fix: on table data change update groupedData copy

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] watcher only if grouping activated
- [x] Cleanup

### CODE REVIEW

**Comment by elizavetaRa** [comment]
@fschade please review. CI is failing as it's as well in #6680

**Comment by fschade** [comment]
@elizavetaRa could you rebase after the ci is green (#6680)

**Comment by diocas** [comment]
@elizavetaRa I've rebased and there was a small conflict, can you double check all works well?

**Comment by elizavetaRa** [comment]
@diocas all seems to work fine

**Review by fschade — APPROVED** [review]
🚀  LGTM, THX

**Pull request merged**
