### PR TITLE
Fetch share again via OCS request if it's not in the response

### PR DESCRIPTION
**Pull request by kulmann**
## Description
In oCIS we don't return the share in the response of the accept/decline shares request. Therefore we have to fetch the share again after the action to update the share information on the screen.

## Related Issue

- Mitigates https://github.com/owncloud/web/issues/4946 - the real fix should be in the backend.

## How Has This Been Tested?

- drone

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14886/

<p>







</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Move</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15302/

<p>










</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Move</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15327/

<p>




</p></details>

**Review by C0rby — APPROVED** [review]
Looks good to me.

**Pull request merged**
