### PR TITLE
[tests-only] throw an exception on uhandled exception in unit tests

### PR DESCRIPTION
**Pull request by individual-it**
## Description
- if there is an unhandled rejection throw an exception
  otherwise node 14 will only show a warning
  this leads to many crap tests, see #6337
- mock `@files/src/composables` to make the failing tests pass
 

## Related Issue

- part of #6337
- ~~blocked by #6337~~

## Motivation and Context
don't allow crap tests

## How Has This Been Tested?

- :robot:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by kulmann** [comment]
Uff... good spot. Do you have an idea / a plan how to proceed from here? Skip the respective tests in this PR and fix them in separate PRs? Probably easier than keeping this open until the tests are fixed / modified / deleted / ... ?

**Comment by individual-it** [comment]
@kulmann I have today half a day to work on it, let me see how many of the actual issues I can fix

**Comment by individual-it** [comment]
@kulmann it turned out to be an easy task after I found a place where `@files/src/composables` was mocked, THX to @JanAckermann for that good example

I've put the mock into `jest.init.js`, alternatively we can place it in every file where its needed and would not need `jest.unmock('@files/src/composables')` in `[usePagination.spec.ts](https://github.com/owncloud/web/pull/6415/commits/26b826b11ec85247f4a4d45d98a3c6ac77085292#diff-04163efa678b56879e33803c560c520c412cb0dda7ac0b0e291d134b27a845d8)`

So we can merge this PR, it's not blocked anymore

**Review by kulmann — APPROVED** [review]
🤩

**Pull request merged**
