### PR TITLE
async callback for setCollaboratiorForShare fn

### PR DESCRIPTION
**Pull request by kiranparajuli589**
try to fix https://drone.owncloud.com/owncloud/web/18472/55/10

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18478/28/1
The following scenarios passed on retry:
- webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature:98

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublicManagement</strong> https://drone.owncloud.com/owncloud/web/18478/34/1
The following scenarios passed on retry:
- webUISharingPublicManagement/publicLinkIndicator.feature:27

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternalUsers1</strong> https://drone.owncloud.com/owncloud/web/18478/55/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
Thanks @kiranparajuli589, this was fixed in https://github.com/owncloud/web/pull/5710

**Pull request closed without merging**
