### PR TITLE
[tests-only] [full-ci] Try core latest

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
WIP

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by phil-davis** [comment]
This is strange - https://drone.owncloud.com/owncloud/web/18891 CI ran only the linting and unit tests, not acceptance tests.
ToDo: work out why the loop through "servers" does not happen correctly.

**Comment by pascalwengerter** [comment]
@phil-davis is this one still relevant?:)

**Comment by phil-davis** [comment]
Yes, for now, I need to investigate why this attempt to run CI with core latest (10.8.0) did not run any acceptance tests at all!
https://drone.owncloud.com/owncloud/web/18891

Changing only `.drone.star` like that should not invoke the "unit-tests-only" logic.

**Comment by phil-davis** [comment]
I sorted it out in #5782 - the trouble was that the pipeline names got too long.
```
$ drone starlark --max-execution-steps 200000
Error: generated stage name of length 51 is not supported. The maximum length is 50. oC10SharingFolderAdvancedPermissionMU-chrome-latest
Error: generated stage name of length 55 is not supported. The maximum length is 50. oC10SharingInternalGroupsSharingIndicator-chrome-latest
Error: generated stage name of length 54 is not supported. The maximum length is 50. oC10SharingInternalUsersSharingIndicator-chrome-latest
```

Unfortunately on the online drone server there is no error shown, the starlark code just skips doing any acceptance test pipelines. I need to look at that separately.

**Pull request closed without merging**
