### PR TITLE
Transfer #6447

### PR DESCRIPTION
**Pull request by pascalwengerter**
Transfer https://github.com/owncloud/web/pull/6447 from a stuck CI

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternal2</strong> https://drone.owncloud.com/owncloud/web/23051/60/1
The following scenarios passed on retry:
- webUISharingInternalUsers/shareWithUsers.feature:342

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/23051/16/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIMarkdownEditor-markdownFile_feature-L21.png
  

### webUIMarkdownEditor-markdownFile_feature-L29.png
  

### webUIMarkdownEditor-markdownFile_feature-L44.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Review by lookacat — APPROVED** [review]
LGTM :)

**Comment by pascalwengerter** [comment]
Still confused as to why

```
webUIMarkdownEditor/markdownFile.feature:21
webUIMarkdownEditor/markdownFile.feature:29
webUIMarkdownEditor/markdownFile.feature:44
```

fail for this PR - they work fine locally, both in acceptance tests and when using the UI independently

**Comment by pascalwengerter** [comment]
@phil-davis @individual-it could someone from your team take a look? This works fine locally (both when running acceptance tests and from a user's perspective) but fails in CI, I'm wondering if *either* the parallelized tests *or* the checks from middleware being a notch too fast lead to a test failure?

**Comment by kiranparajuli589** [comment]
I'll try to find out what's causing the failure here.

**Comment by phil-davis** [comment]
> I'll try to find out what's causing the failure here.

@kiranparajuli589 please push any changes/fixes to #6494 - that is rebased to the current web master.

**Comment by kiranparajuli589** [comment]
> > I'll try to find out what's causing the failure here.
> 
> @kiranparajuli589 please push any changes/fixes to #6494 - that is rebased to the current web master.

sure @phil-davis

**Comment by pascalwengerter** [comment]
Closed in favor of #6494

**Pull request closed without merging**
