### PR TITLE
Fix share loading when adding a link via quick action

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
When adding/removing shares while the shares are currently in a loading state, we need to wait for the loading to be finished.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/8894
- Fixes https://github.com/owncloud/web/issues/8896

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/35163/20/1
:boom: The oC10Files3 tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/35163/15/1
:boom: The oC10RenameFolder tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/35163/14/1
:boom: The oC10FileFolderOperations tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/35163/12/1
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.

**Review by kulmann — APPROVED** [review]

**Pull request merged**
