### PR TITLE
Fix app.png path from absolute to relative

### PR DESCRIPTION
**Pull request by kulmann**
## Description
Path to app.png needs to be relative...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by kulmann** [comment]
cc @wkloucek (who stumbled upon this in a production deployment with weird redirects)

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/23531/10/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23531/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2022-3-10-03-38-50.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23531/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-brian-2022-3-10-03-39-12.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23531/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-carol-2022-3-10-03-39-21.zip 


</p></details>

**Review by pascalwengerter — APPROVED** [review]
Is it worth adding a changelog item?

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic1</strong> https://drone.owncloud.com/owncloud/web/23533/67/1
The following scenarios passed on retry:
- webUISharingPublicBasic/publicLinkCreate.feature:190

**Pull request merged**
