### PR TITLE
Injecting versions [WIP]

### PR DESCRIPTION
**Pull request by jacob-nv**
## Description
`SideBar.vue` fetches versions which are provided to `FileVersions.vue` and `FileSideBar.vue`

## Related Issue

- Fixes https://github.com/owncloud/web/issues/10381

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

### CODE REVIEW

**Comment by jacob-nv** [comment]
@JammingBen Any recommendation for how to handle tests? Lots of the testing is based around fetching. Here is everything provided except one instance where restoring old version refreshes versions through provided method

**Comment by JammingBen** [comment]
> @JammingBen Any recommendation for how to handle tests? Lots of the testing is based around fetching. Here is everything provided except one instance where restoring old version refreshes versions through provided method

Hmm I didn't think about the re-fetching, not only from a unit test perspective, but the actual implementation. The fact that the versions panel needs to reload versions after reverting kinda makes me question the provide/inject approach... @kulmann @dschmidt what do you think?

**Comment by kulmann** [comment]
> > @JammingBen Any recommendation for how to handle tests? Lots of the testing is based around fetching. Here is everything provided except one instance where restoring old version refreshes versions through provided method
> 
> Hmm I didn't think about the re-fetching, not only from a unit test perspective, but the actual implementation. The fact that the versions panel needs to reload versions after reverting kinda makes me question the provide/inject approach... @kulmann @dschmidt what do you think?

Sounds to me like a pinia store (similar to the `shares` pinia store implementation) would make sense. 🤔

**Comment by JammingBen** [comment]
Closing here since this approach of fixing it is not really feasible because of the reasons mentioned above.

**Pull request closed without merging**
