### PR TITLE
[tests-only] [full-ci] Adjust CI pipelines to reduce acceptance test elapsed time

### LINKED ISSUE #6356: Split ocis pipelines further
Looking at https://drone.owncloud.com/owncloud/web/22374 it seems that we can reduce the CI runtime by 4 minutes by splitting the `oCISSharingInternal1` pipeline. It takes 23 minutes, while the longest running pipeline before that takes 19 minutes (`oCISRename`).

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Adjust the nightwatch acceptance test suite pipelines to keep the longest pipeline at about 20 minutes.

There are comments below about what I did as I shuffled test suites and pipelines.

## Related Issue
Fixes #6356 

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic1</strong> https://drone.owncloud.com/owncloud/web/22383/65/1
The following scenarios passed on retry:
- webUISharingPublicBasic/publicLinkCreate.feature:190

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/22383/57/15
oCISSharingInternal1 16 minutes 37 seconds

https://drone.owncloud.com/owncloud/web/22383/60/15
oCISSharingAutocompletion 16 minutes 3 seconds

https://drone.owncloud.com/owncloud/web/22383/38/20
oC10SharingFolderAdvPermsGrp 12 minutes 45 seconds 

https://drone.owncloud.com/owncloud/web/22383
Elapsed time of the whole drone CI run: 36m 53s

That seems OK. There are recent runs that are around 40 min and over. But also some runs that are as low as 34 min:
https://drone.owncloud.com/owncloud/web/22381
somehow that finished everything (build pipelines, lint, unit tests, e2e, acceptance) in 34 min. I guess it depends a lot on what pipelines end up on what drone agents, how loaded each drone agent is, what dependency files happen to already be available on the agent, how fast dependencies are pulled from their upstream sources...

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingAndUpload</strong> https://drone.owncloud.com/owncloud/web/22386/64/1
The following scenarios passed on retry:
- webUIUpload/upload.feature:94

**Comment by phil-davis** [comment]
I restarted and this time the full elapsed time was 39m 16s https://drone.owncloud.com/owncloud/web/22386

`oCISSharingInternal1` 12m 39s

`oCISSharingAutocompletion` 18m 56s

`oC10SharingFolderAdvPermsGrp` 13m 1s

https://drone.owncloud.com/owncloud/web/22386/17/1 `oC10Files2` took 25m 23s - that was clearly longer than the next longest pipeline, which was 20m 28s. The previous `oC10Files2` https://drone.owncloud.com/owncloud/web/22383/17/1 took 22m 11s. But in that build `oCISBasic` took 23m 5s and there were other pipelines that took 22m. So there is easily 10% to 15% variability anyway.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/22387/15/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingAcceptSharesToRoot-acceptShares_feature-L108.png
  


</p></details>

**Comment by phil-davis** [comment]
> Results for oC10SharingAccept https://drone.owncloud.com/owncloud/web/22387/15/1

Issue #6097  - I commented there.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/22389/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/22389/57/1
`oCISSharingInternal1` 12m 57s

https://drone.owncloud.com/owncloud/web/22389/60/1
`oCISSharingAutocompletion` 14m 9s

https://drone.owncloud.com/owncloud/web/22389/38/1
`oC10SharingFolderAdvPermsGrp` 11m 51s

total elapsed time 40m 18s

`oC10Files2` took 28m 21s. Other pipelines took only up to about 21 minutes.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingAndUpload</strong> https://drone.owncloud.com/owncloud/web/22390/65/1
The following scenarios passed on retry:
- webUIUpload/upload.feature:94

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/22391
Elapsed time 34m 21s

`oCISBasic` 18m 15s
`oCISFiles1` 15m 22s
`oCISFiles2` 15m 32s
`oCISFiles3` 13m 36s
`oCISFiles4` 11m 17s

The longest were 
`oC10SharingPublic2`20m 15s
`oC10SharingExternal` 19m 43s
`oCISSharingInternal2` 19m 12s

So there would be a fair bit of reshuffling needed to reduce much more.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/22392/8/4
yarn-install in the "lint" pipeline took 6m 24s. 
"Pulling from owncloudci/nodejs" took nearly 277s - 4m 37s. That sort of thing is a nuisance and slows the total elapsed time.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/22392/15/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingAcceptSharesToRoot-acceptShares_feature-L108.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingAndUpload</strong> https://drone.owncloud.com/owncloud/web/22393/66/1
The following scenarios passed on retry:
- webUIUpload/upload.feature:94

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/22393

that was a good run - I guess there were no badly-delayed docker image pulls.

elapsed time 33m 8s

**Review by kulmann — APPROVED** [review]
Thanks for taking care 👍

**Review by individual-it — APPROVED** [review]

**Pull request merged**
