### PR TITLE
[full-ci] Slightly update modal layout

### PR DESCRIPTION
**Pull request by hurradieweltgehtunter**
Slightly update modal layout:
- Separate modal actions from modal body by thin line
- Replace dark header background (light mode) with light header, to better integrate in light mode and to keep contrast ratio (before: title: light text on dark bg, body: dark text on light bg)
- Use same border radius as input fields (Goal: all interactive elements have the same)
- Increase line-height slightly for better readability

Before: 
grafik

grafik

After:
grafik

grafik

### CODE REVIEW

**Comment by ChrisEdS** [comment]
I like the idea in general, can also be a plus in regards of theming! Before the "header" had the same color as the base color. The contrast was bad sometimes.

image

Can you work on the alignment?

**Comment by kulmann** [comment]
Thank you for your efforts. Spawning @tbsbdr here for a second opinion, because you won't like mine.

I think this is a step backwards. Adding a screenshot below so that one can get more context / an impression of the full page.
- modal feels quite big, even cumbersome
- too much whitespace
- the bottom border between body and buttons feels heavy
- I liked the brand background in the modal header

What I do like is that the `Cancel` button is less prominent.

Not sure about the removal of the icon in the header. Yes, the icon was weird / ugly. But I do like our pretty heavy usage of icons - it makes the UI more lively and friendly.


### current implementation
Screenshot 2023-03-14 at 20 41 18


### your proposal
Screenshot 2023-03-14 at 20 33 31

**Comment by hurradieweltgehtunter** [comment]
hey, you were right, I don't like it :D 
But anyways, let's don't argue about personal opinions. I try to avoid working based on my personal opinion. My approach is always not to reinvent the wheel but to take as a basis what is provable by UX studies or how other, established companies implement elements, because I assume that UX studies have already been implemented there.
That's why I looked at many modals, from CSS frameworks to implementations in e.g. OneDrive, etc. My result was that I didn't find one that backgrounds the title with a different color than the body. 
Also, many separate the areas from each other visually: header, body, CTA area, hence the border. But there are also other examples without the border. I found it cleaner that way.

I don't know enough about accessibility but I can imagine that this could also be an issue.
Regarding the size of the modal: The modal has the entire screen size at its disposal and should attract the entire focus of the user. So why keep it unnecessarily small?

Border radius: yeah, I don't really have a preference on that, can be made larger again.

To the whitespace, I also looked at other implementations. Generally I found a bit more whitespace more elegant, but can be reduced again.

About the icon: I totally agree, heavy usage of icons as supportive visual elements is a good thing. In this case it's more about the icon itself, which looks a bit odd IMO. Maybe better use the exclamation mark icon?
grafik

In general, I went for the modals because the previous implementation somehow reminded me of old software á la Windows 98. Sorry :D

Edit: I read about the accessibility topic regarding white text on dark bg in the title. Actually, it can be a good layout for texts users just scan over, like a title (-> https://uxmovement.com/content/when-to-use-white-text-on-a-dark-background/). But since we use our brand color here, what happens in a branded oc if the brand color is a brighter one? Then we have white text on bright bg :/ Keeping it neutral like the body covers that.

In the end, you or @tbsbdr have to decide. This is just to explain my background and thoughts.

**Comment by hurradieweltgehtunter** [comment]
Another thing to consider: We could add a close button in the top right corner which is kind of a standard.

**Comment by kulmann** [comment]
> hey, you were right, I don't like it :D But anyways, let's don't argue about personal opinions. I try to avoid working based on my personal opinion. My approach is always not to reinvent the wheel but to take as a basis what is provable by UX studies or how other, established companies implement elements, because I assume that UX studies have already been implemented there. That's why I looked at many modals, from CSS frameworks to implementations in e.g. OneDrive, etc. My result was that I didn't find one that backgrounds the title with a different color than the body. Also, many separate the areas from each other visually: header, body, CTA area, hence the border. But there are also other examples without the border. I found it cleaner that way.

Please don't take it personal then, that's not my intention. ;-) 
A good mix of copying what others do and trusting your gut feeling should be allowed and is what I'm doing as well...
Depending on your working mode preference, writing in issue with that findings before investing the time in a PR is also a good idea. But again, if you want to fiddle around then the code is already there anyway - moves the discussion from a ticket to the PR then, like now.
In the particular case of modals, I was also taking into account that the current state was the outcome of the professional redesign that was made end of 2021 by a design agency. Here's a screenshot:

Screenshot 2023-03-15 at 10 27 15


> Regarding the size of the modal: The modal has the entire screen size at its disposal and should attract the entire focus of the user. So why keep it unnecessarily small?
> To the whitespace, I also looked at other implementations. Generally I found a bit more whitespace more elegant, but can be reduced again.

That is indeed true. I always have pretty common feedback in mind that the web ui was perceived as "too big / clumsy". So I'm very careful with making things bigger again. Good to play around with the size in any case. The redesign from end of 2021 also had more whitespace and thus was bigger. I think more whitespace in the body is really elegant. The one you had in the header and footer is too much in my opinion.


> About the icon: I totally agree, heavy usage of icons as supportive visual elements is a good thing. In this case it's more about the icon itself, which looks a bit odd IMO. Maybe better use the exclamation mark icon? grafik

Yep, excalamation mark is better. We have a lot to choose from (remixicons). Icon choice should depend on the mode/variation of the modal though. A modal with a warning (`do you really want to delete all your personal files of the last 30 years?`) should have another icon than the one for creating a new folder.

> In general, I went for the modals because the previous implementation somehow reminded me of old software á la Windows 98. Sorry :D

Aaaand there it is, your personal opinion having an impact on your work. 😜 

> Edit: I read about the accessibility topic regarding white text on dark bg in the title. Actually, it can be a good layout for texts users just scan over, like a title (-> https://uxmovement.com/content/when-to-use-white-text-on-a-dark-background/). But since we use our brand color here, what happens in a branded oc if the brand color is a brighter one? Then we have white text on bright bg :/ Keeping it neutral like the body covers that.

That's a theming issue that I try to solve in https://github.com/owncloud/web/pull/8563 by introducing `contrast` color variants for all the color swatches. If you choose a light brand color in your theme you need to be able to provide a dark contrast color for the `brand` swatch. That's simply missing in current master.


> In the end, you or @tbsbdr have to decide. This is just to explain my background and thoughts.

Naah, I don't like to play the boss card. We should find a compromise and not just go with my opinion. If you are willing to invester more time I'd be happy to iterate further on your ideas, because the modal can use some improvements. I do see the point with whitespace in the body and the modal size. See comments above. :-)

**Comment by hurradieweltgehtunter** [comment]
Updated the icon:
grafik

**Comment by hurradieweltgehtunter** [comment]
@kulmann need a decision on how to set the modal title.
# light version
grafik

Pros:
— No need to set a themed font color
— colored icon – based on success, danger, warning variant – looks better on white bg
— looks cleaner

grafik
— light text on dark bg better for texts users` scan over

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/34118/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34118/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2023-3-23-03-28-08.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34118/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-brian-2023-3-23-03-28-37.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34118/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-carol-2023-3-23-03-28-43.zip 


</p></details>
:boom: The e2e-oc10 tests pipeline failed. The build has been cancelled.

**Comment by kulmann** [comment]
Then let's go with the light version / without the brand color. Also makes theming easier by the way. 👍

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/34133/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34133/tracing/admin-deletes-group-admin-2023-3-23-09-31-36.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34133/tracing/unstructured-collection-of-testable-space-interactions-alice-2023-3-23-09-43-11.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34133/tracing/user-group-assignments-can-be-handled-via-batch-actions-admin-2023-3-23-09-33-13.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34133/tracing/user-login-can-be-managed-in-the-admin-settings-admin-2023-3-23-09-32-42.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34133/tracing/user-login-can-be-managed-in-the-admin-settings-admin-2023-3-23-09-32-48.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34133/tracing/user-login-can-be-managed-in-the-admin-settings-alice-2023-3-23-09-32-47.zip 


</p></details>
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.

**Comment by hurradieweltgehtunter** [comment]
done from my side. Not sure why the e2ee test fail :/

**Comment by kulmann** [comment]
> done from my side. Not sure why the e2ee test fail :/

Could you please do another rebase? There was some e2e test flakyness yesterday. Might be the issue here...

**Comment by hurradieweltgehtunter** [comment]
up you go 🚀

**Review by kulmann — APPROVED** [review]
Looks nice! Also loving the default icons based on the variation. That makes sense.

**Pull request merged**
