### PR TITLE
Prepare release 3.1.0

### PR DESCRIPTION
**Pull request by kulmann**
~DO NOT MERGE~ 

## Description
Release v3.1.0

### CODE REVIEW

**Comment by kulmann** [comment]
Blocked by https://github.com/owncloud/web/pull/5073 - otherwise the `Shared with others` page is entirely broken (loading spinner doesn't disappear anymore) when any user has an actual avatar.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Move</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15420/

<p>


### webUIMoveFilesFolders-moveFiles-feature-105.png
  


</p></details>

**Review by pascalwengerter — APPROVED** [review]
LGTM 🎯

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15437/

<p>


### webUILogin-adminBlocksUser-feature-20.png
  

### webUIPreview-imageMediaViewer-feature-140.png
  

### webUIPreview-imageMediaViewer-feature-158.png
  

### webUIPreview-imageMediaViewer-feature-83.png
  

### webUIPreview-imageMediaViewer-feature-90.png
  


</p></details>

**Pull request merged**
