### PR TITLE
Vite: Get rid of Vite specific config files

### PR DESCRIPTION
**Pull request by dschmidt**
## Description
Proxy `config.json` from the underlying ownCloud server.
(and patch it on the fly, so it can be used in Vite)

## Motivation and Context
We have a gazillion `config.json` files and it's utterly confusing.

### Other ownCloud instances
Moreover, by adjusting the server provided config dynamically for Vite, it's much easier to develop against other ownCloud instances.

#### oCIS
Take for example the  [wopi example](https://github.com/owncloud/ocis/tree/85059cfecf0c7ada79f41e8084c495f185465f1a/deployments/examples/ocis_wopi)

Just mount [ocis.idp.config.yaml](https://github.com/owncloud/web/blob/0da97bfebf94e8a41b29765938ae1829a03c71b5/dev/docker/ocis.idp.config.yaml) to `/etc/ocis/idp.yaml` into the oCIS container by adding the following line into the `volumes` section of the `ocis` service in the `docker-compose.yml` file:
```
- /home/youruser/projects/oc-web/dev/docker/ocis.idp.config.yaml:/etc/ocis/idp.yaml
```
and start Vite like this:
```
OWNCLOUD_WEB_CONFIG_URL="https://ocis.owncloud.test/config.json" pnpm vite
```
and you can develop against a wopi enabled oCIS instance.

#### oC 10
For oC 10 it's a bit more complicated because the oAuth app does not allow multiple redirect urls per client. Thus we *always* need to provide a different client id (and possibly secret) than the one which was provided by the server.

```
OWNCLOUD_WEB_CLIENT_ID="AWhZZsxb59ouGg97HsdR7GiN8pnzEYvk1cL6aVJgTQH1Gcdxly1gendLVTZ5zpYC" OWNCLOUD_WEB_CLIENT_SECRET="VsrTbbeTPJ56e93eKpCdb6Wf5IGHD2meadlsDT1M9EpS3k7Y1ywTYgOhTkKZ0QTL" pnpm vite:oc10
``` 

Make sure to provide those or to setup your client with the same values as in [oc10.entrypoint.sh](https://github.com/owncloud/web/blob/0da97bfebf94e8a41b29765938ae1829a03c71b5/dev/docker/oc10.entrypoint.sh#L39).
To make everyday development as easy as possible we fall back to exactly this client id if none is provided via env variable (client secret is optional).

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/34187/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34187/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2023-3-24-05-40-19.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34187/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-brian-2023-3-24-05-40-47.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/34187/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-carol-2023-3-24-05-40-53.zip 


</p></details>
:boom: The e2e-oc10 tests pipeline failed. The build has been cancelled.

**Comment by kulmann** [comment]
Can you imagine a place where documentation about this (basically the "ocis" and "oc10" parts of your PR description) would make sense?

**Comment by kulmann** [comment]
> If we had documented using Vite already ... 😅

:trollface: 


> I looked into it before, but I think documentation needs some love in that area. Otherwise it would turn out to be more confusing than it helps I'm afraid.

What about referencing your PR link in the vite config then? 🤔

**Comment by dschmidt** [comment]
> > If we had documented using Vite already ... 😅
> 
> :trollface:
> 
> > I looked into it before, but I think documentation needs some love in that area. Otherwise it would turn out to be more confusing than it helps I'm afraid.
> 
> What about referencing your PR link in the vite config then? 🤔

Or I just copy what I've written here into the source code...

**Review by kulmann — APPROVED** [review]
This is nice ❤️‍🔥

**Pull request merged**
