### PR TITLE
[full-ci] [tests-only] Open jpeg file in "shared with me page" or "shared with other"

### PR DESCRIPTION
**Pull request by ScharfViktor**
Description here: [5324](https://github.com/owncloud/web/issues/5324)

A test is written that demonstrates the error. The test will work when the bug is fixed

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISBasic</strong> https://drone.owncloud.com/owncloud/web/17537/46/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISBasic</strong> https://drone.owncloud.com/owncloud/web/17543/46/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/17544/23/1
The following scenarios passed on retry:
- webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature:104

**Comment by ownclouders** [comment]
Results for <strong>oCISBasic</strong> https://drone.owncloud.com/owncloud/web/17544/46/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Review by phil-davis — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>oC10XGAPortrait2</strong> https://drone.owncloud.com/owncloud/web/18125/43/1
The following scenarios passed on retry:
- webUIUpload/upload.feature:90

**Comment by ownclouders** [comment]
Results for <strong>oC10MoveUpload</strong> https://drone.owncloud.com/owncloud/web/18125/14/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10iPhone2</strong> https://drone.owncloud.com/owncloud/web/18127/46/1
The following scenarios passed on retry:
- webUIUpload/upload.feature:90

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/18127/12/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:36

**Comment by phil-davis** [comment]
I suggest that we rebase this after https://github.com/owncloud/web/pull/5652 is merged - that PR will provide a known-good green CI to the latest oCIS 1.10.0

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18229/28/1
The following scenarios passed on retry:
- webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature:98

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublicManagement</strong> https://drone.owncloud.com/owncloud/web/18229/34/1
The following scenarios passed on retry:
- webUISharingPublicManagement/publicLinkIndicator.feature:27

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/18229/39/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:363

**Pull request merged**
