### PR TITLE
Allow full screen external apps (i.e presentation mode)

### PR DESCRIPTION
**Pull request by diocas**
This allows for example presentation apps to enter full screen.

### CODE REVIEW

**Comment by diocas** [comment]
Don't see any reason why we don't want to allow this for any app, since many of them require it.
But I think we should check what we needs to be sandboxed, but that's another issue/pr.

**Review by kulmann — CHANGES_REQUESTED** [review]
@diocas Could you run `yarn test:unit -u` to update the unit test snapshots?

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternal2</strong> https://drone.owncloud.com/owncloud/web/24352/60/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingInternalUsers-shareWithUsers_feature-L342.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
> When I updated, there was another test that got updated as well.. I've removed it, since it was out of the scope of this PR, but I guess it's what's failing now.

Acceptance test failure is either random or caused by your branch being out of synch with the acceptance tests on master, I'll merge this branch into a temporary PR and check that

**Pull request merged**
