### PR TITLE
[do-not-merge][tests-only]Run versions test

### PR DESCRIPTION
**Pull request by SwikritiT**
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/20532/9/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:183
- webUIFilesActionMenu/versions.feature:490

**Comment by SwikritiT** [comment]
pause time: `1111` the build passed but few tests are passing in retry
https://drone.owncloud.com/owncloud/web/20532/9/19

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/20533/9/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:183
- webUIFilesActionMenu/versions.feature:383

**Comment by SwikritiT** [comment]
pause time: 1300 the build is passing but again there are some passes on retries. https://drone.owncloud.com/owncloud/web/20533/9/19

**Comment by SwikritiT** [comment]
pause time:1600 the build passes without any retries https://drone.owncloud.com/owncloud/web/20534/9/19

**Pull request closed without merging**
