### PR TITLE
[full-ci] Fix acceptance tests now that public links open in editors by default

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
See code changes

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/35835/71/1
:boom: The oC10IntegrationApp2 tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/35835/69/1
:boom: The oCISTrashbinJourney tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/35835/70/1
:boom: The oC10IntegrationApp1 tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
Closing as cherry-picked to #9046

**Pull request closed without merging**
