### PR TITLE
Do not load files from cache

### PR DESCRIPTION
**Pull request by diocas**
When apps (i.e Drawio) try to load a file, the browser caches the request.
If the file was modified somewhere else, this causes inconsistent results which prevent saving any changes until the cache is properly cleared.

We had observed this is the past in our text editor, hence the `noCache` addition to the SDK. Now we also saw it in Drawio.

### CODE REVIEW

**Review by kulmann — APPROVED** [review]
Makes sense, thank you!

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPerm2</strong> https://drone.owncloud.com/owncloud/web/22851/64/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/22874/16/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIMarkdownEditor-markdownFile_feature-L21.png
  

### webUIMarkdownEditor-markdownFile_feature-L29.png
  

### webUIMarkdownEditor-markdownFile_feature-L44.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Review by pascalwengerter — APPROVED** [review]
Don't get why the markdowneditor failed for this in CI, just ran the acceptance tests locally with the CERN `web` and it worked flawlessly 🤷🏽 restarting CI, let's see!

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/23045/10/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/23045/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2022-2-24-06-52-48.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/23045/alice-creates-public-link-to-a-folder-alice-2022-2-24-06-53-54.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/23045/alice-shares-file-to-brian-alice-2022-2-24-06-55-04.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/23045/alice-shares-folder-with-file-to-brian-alice-2022-2-24-06-56-14.zip 


</p></details>

**Pull request merged**
