### PR TITLE
[full-ci] fix: load folder in media viewer

### LINKED ISSUE #5427: [media-viewer] Reloading does not work
### Steps to reproduce
1. Open an image in the media-viewer
2. Reload the page

### Expected behaviour
The same image that was shown before the reload is shown again

### Actual behaviour
MediaViewer triggers `loadFolder` action which fails because it was removed in https://github.com/owncloud/web/pull/4627, more specifically in https://github.com/owncloud/web/pull/4627/commits/138a492fcce7bee73aba162d1997c30f2229810e.
A broken MediaViewer is shown, but at least it can be closed by clicking the `x`.

Screenshot_20210701_000549

`loadFolder` is still used in
https://github.com/owncloud/web/blob/master/packages/web-app-media-viewer/src/mixins/loader.js#L31
https://github.com/owncloud/web/blob/master/packages/web-runtime/src/components/Notifications.vue#L67

This issue is caused by the former appearance, more issues might be caused by the latter - but I don't know :-)

When we fix it, we should add tests to avoid another regression further down the road...

@LukasHirt (as you replaced the `loadFolder` with new code:) is this a no-brainer for you to fix? 
Then I'd be happy if you could fix it. If not, I'd still be happy for pointers and I can probably take care of it

### PR DESCRIPTION
**Pull request by LukasHirt**
- fixes #5427

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/17790/23/1
The following scenarios passed on retry:
- webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature:104
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Review by pascalwengerter — COMMENTED** [review]
I just did some manual testing and while it works great most of the time, sometimes images don't load properly (esp. when circling through them via the `<` and `>` icons). Investigating now if that was the case before already

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPermissions1</strong> https://drone.owncloud.com/owncloud/web/17796/56/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10CreateDelete</strong> https://drone.owncloud.com/owncloud/web/17798/8/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:59

**Comment by LukasHirt** [comment]
> sometimes images don't load properly (esp. when circling through them via the < and > icons)

What exactly breaks? Requested image is not loading? Other images are not loaded and you cannot navigate? I tried both this PR and master and works fine for me :shrug:

**Review by fschade — APPROVED** [review]
LGTM 🤖

**Comment by pascalwengerter** [comment]
> > sometimes images don't load properly (esp. when circling through them via the < and > icons)
> 
> What exactly breaks? Requested image is not loading? Other images are not loaded and you cannot navigate? I tried both this PR and master and works fine for me (oc10) 🤷

Sorry mate, I quickly checked whilst doing smoke testing, perhaps it had been a caching issue on my side or sth. With the latest fixes today it seems really good 👌🏽 👏🏽

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/17977/11/1
The following scenarios passed on retry:
- webUIMarkdownEditor/markdownFile.feature:26

**Comment by kulmann** [comment]
Force merged with randomly failing CI with same issue as on master. Not related to this PR.

**Pull request merged**
