### PR TITLE
[full-ci] Add pdf-viewer app

### PR DESCRIPTION
**Pull request by dschmidt**
# Supersedes https://github.com/owncloud/web/pull/6575

## Description
This adds a pdf viewer app which uses the native pdf support of the browser.

This cleans up the code of the original PR and makes it to good to merge imho (for a first iteration at least) when the CI is green.

We should discuss `newTab` and should add a way to navigate back (cc @tbsbdr @pascalwengerter @kulmann ) in followup tickets/prs.

## Related Issue

- Fixes <issue_link>

## Motivation and Context
among other reasons: blob urls are not bookmarkable

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10Files2</strong> https://drone.owncloud.com/owncloud/web/24077/17/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIFilesActionMenu-fileFolderActionMenu_feature-L14.png
  


</p></details>

**Comment by pascalwengerter** [comment]
> Results for **oCISFiles2** https://drone.owncloud.com/owncloud/web/24077/56/1
> 💥 The acceptance tests failed on retry. Please find the screenshots inside ...

PDF opening acceptance test now fails with

```
   ✔ Then the app-sidebar for file "lorem.pdf" should be visible on the webUI # stepDefinitions/filesContext.js:1025

   ✖ And only the following items with default items should be visible in the actions menu on the webUI # stepDefinitions/filesContext.js:1365
```

Needs an update, let's quickly discuss this tomorrow!

**Comment by pascalwengerter** [comment]
> > Results for **oCISFiles2** https://drone.owncloud.com/owncloud/web/24077/56/1
> > 💥 The acceptance tests failed on retry. Please find the screenshots inside ...
> 
> PDF opening acceptance test now fails with
> 
> ```
>    ✔ Then the app-sidebar for file "lorem.pdf" should be visible on the webUI # stepDefinitions/filesContext.js:1025
> 
>    ✖ And only the following items with default items should be visible in the actions menu on the webUI # stepDefinitions/filesContext.js:1365
> ```
> 
> Needs an update, let's quickly discuss this tomorrow!
> 
> **Update:** There's two failures in CI,
> 
>     * `webUIFilesActionMenu/fileFolderActionMenu.feature:14` => see text above
> 
>     * `webUIPrivateLinks/accessingPrivateLinks.feature:9` => see [oc10IntegrationApp1 private link acceptance tests flaky #6607](https://github.com/owncloud/web/issues/6607)

Another update: The PDF viewer app wasn't added in any of the configs yet, so CI wouldn't find it in the contextMenu for `.pdf` files. Should be fine now, I've added it as enabled by default to all configs I could find

**Review by pascalwengerter — COMMENTED** [review]
Not an appropriate reviewer since I collaborated on this one, code LGTM though, waiting for @kulmann's final review

**Review by kulmann — CHANGES_REQUESTED** [review]
Small nitpick regarding translations, otherwise awesome! 🚀

**Pull request merged**
