### PR TITLE
[tests-only][full-ci] backport acceptance test code changes from #10392

### PR DESCRIPTION
**Pull request by S-Panta**
This PR backports acceptance test changes from https://github.com/owncloud/web/pull/10392
Part of https://github.com/owncloud/web/issues/10457

### CODE REVIEW

**Comment by saw-jan** [comment]
After https://github.com/owncloud/web/pull/10504

**Comment by saw-jan** [comment]
since stable-8 will not have sharingNG implemented, let's keep the resharing tests in stable-8.0. But we can delete acceptance resharing tests

**Review by saw-jan — APPROVED** [review]

**Comment by ScharfViktor** [comment]
> This PR backports acceptance test changes from #10392 Part of #10457

#10392 seems that wrong link

**Review by ScharfViktor — APPROVED** [review]
please change link)

**Comment by saw-jan** [comment]
>https://github.com/owncloud/web/pull/10392 seems that wrong link

I only copied the acceptance test changes of that PR (no src and no e2e - new feature)

**Comment by ScharfViktor** [comment]
> I only copied the acceptance test changes of that PR (no src and no e2e - new feature)

yes, I was wrong. sorry. I deleted my comment

**Pull request merged**
