### PR TITLE
[full-ci] remove skip scripts

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
Move some simple bash scripts back into the Drone CI definitions, since we don't use the skip mechanism inside the bash script anymore (since https://github.com/owncloud/web/pull/5914)

## Related Issue

- Followup on https://github.com/owncloud/web/pull/5914

## How Has This Been Tested?

- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingFolderAdvPermMU</strong> https://drone.owncloud.com/owncloud/web/20220/22/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingFolderAdvPermsGrp</strong> https://drone.owncloud.com/owncloud/web/20220/23/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/20228/41/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10XGAPortraitNotifications</strong> https://drone.owncloud.com/owncloud/web/20228/43/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublicExpireAndRoles</strong> https://drone.owncloud.com/owncloud/web/20229/64/1
The following scenarios passed on retry:
- webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:11

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingFolderAdvPermMU</strong> https://drone.owncloud.com/owncloud/web/20234/22/1
The following scenarios passed on retry:
- webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:71

**Review by pascalwengerter — APPROVED** [review]
@wkloucek this is in a draft state, but should be good to merge, no?

**Pull request merged**
