### PR TITLE
Fix: click on share-indicator in files list should scroll

### PR DESCRIPTION
**Pull request by JanAckermann**
## Related Issue

- Fixes https://github.com/owncloud/web/issues/6968

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/27012/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/27012/tracing/participant-management-alice-2022-7-25-04-17-52.zip 


</p></details>

**Review by kulmann — APPROVED** [review]
I'm fine with merging this PR without additional acceptance tests. Functionality works as expected. Super happy with the attention to detail you put into this PR, all the file action mixins being changed as well etc. Good job 👍

**Comment by JanAckermann** [comment]
@kulmann can you check again, I think we might be able to delete duplicated share loading

**Comment by kulmann** [comment]
> @kulmann can you check again, I think we might be able to delete duplicated share loading

I checked the code again and removed some dead code. The space member loading inside the `FileShares.vue` component can stay like it is for now. Would be nice to move that into the `SharesPanel.vue` as well, but let's do that in a separate PR.

**Pull request merged**
