### PR TITLE
[full-ci][Tests-Only] Fix intermittent failure on user creation

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Because of a bug in user creation in ocis(https://github.com/owncloud/ocis/issues/2272), few tests fail and only pass on retry.
eg https://github.com/owncloud/web/pull/5463#issuecomment-875304042
This Pr fixes that issue.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/5438

## How Has This Been Tested?

:robot:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternalUsers2</strong> https://drone.owncloud.com/owncloud/web/17062/53/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Review by individual-it — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>oC10iPhone1</strong> https://drone.owncloud.com/owncloud/web/17157/44/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:59

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp2</strong> https://drone.owncloud.com/owncloud/web/17157/65/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUISharingAutocompletion-shareAutocompletion-feature-32.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-44.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Sharing1</strong> https://drone.owncloud.com/owncloud/web/17157/15/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUISharingAutocompletion-shareAutocompletion-feature-115.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-128.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-141.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-154.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-168.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-32.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-44.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-87.png
  

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-36.png
  

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-37.png
  

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-38.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp2</strong> https://drone.owncloud.com/owncloud/web/17158/65/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUISharingAutocompletion-shareAutocompletion-feature-32.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-44.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Sharing1</strong> https://drone.owncloud.com/owncloud/web/17158/15/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUISharingAutocompletion-shareAutocompletion-feature-115.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-128.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-141.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-154.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-168.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-32.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-44.png
  

### webUISharingAutocompletion-shareAutocompletion-feature-87.png
  

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-36.png
  

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-37.png
  

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-38.png
  


</p></details>

**Review by individual-it — APPROVED** [review]
please make the same change in the test-middleware

**Pull request merged**
