### PR TITLE
[full-ci] Release 4.1.0

### LINKED ISSUE #5698: Release v4.1.0
## Release checklist
- [x] Merge https://github.com/owncloud/web/pull/5588 @paulcod3 
- [x] Merge https://github.com/owncloud/web/pull/5678 @paulcod3 
- [x] prepare release rc: @paulcod3 
  - [x] create a branch `release-4.1.0` @paulcod3 
  - [x] update the version in `packages/web-integration-oc10/appinfo/info.xml` @paulcod3 
  - [x] update the version in `package.json` @paulcod3 
  - [x] update the version in `sonar-project.properties` @paulcod3 
  - [x] move changelog/unreleased/* to changelog/VERSION_YYYY-MM-DD @paulcod3 
  - [x] update the ocis commit id in `.drone.env` to the most recent one from ocis master (i.e. let the web UI tests run on most recent ocis master) @paulcod3 
  - [x]  commit, push and create **draft** PR for this branch @paulcod3 
- [x] create pre release tag `v4.1.0-rc1` from the release branch @paulcod3 
- [X] smoke test 
  - [X] against oCIS @ScharfViktor  @kulmann 
  - [X] against oc10 standalone @kulmann 
- [X] if needed, fix issues or write down known issues 
- [x] update `YYYY-MM-DD` to current date in `changelog/VERSION_YYYY-MM-DD` @pascalwengerter 
- [X] Make sure translations are up to date @pascalwengerter  
- repeat above steps if a new rc is needed
- [X] Run translations sync job @pascalwengerter
- [X] go to the releases section and click `Draft a new Release`. Use `v4.1.0` as a tag (the v prefix is important) and `4.1.0` as name and publish it @pascalwengerter 
- [X] ping in internal #btr channel to create a signed marketplace release @pascalwengerter 
- [ ] merge [release branch](https://github.com/owncloud/web/pull/5703) back to master (CI must be green) @pascalwengerter

### PR DESCRIPTION
**Pull request by paulcod3**
Release 4.1.0, closes #5698

### CODE REVIEW

**Comment by pascalwengerter** [comment]
We'll need to update https://github.com/owncloud/web/blob/master/changelog/unreleased/enhancement-update-ods to reflect the ODS 9.2.0 version but that can be done shortly before having the last CI run with this branch

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternalUsers1</strong> https://drone.owncloud.com/owncloud/web/18459/55/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by kulmann** [comment]
> We'll need to update https://github.com/owncloud/web/blob/master/changelog/unreleased/enhancement-update-ods to reflect the ODS 9.2.0 version but that can be done shortly before having the last CI run with this branch

done. translations updated as well.

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/18462/12/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:36

**Comment by kulmann** [comment]
The test `webUISharingInternalUsers/shareWithUsers.feature:337` is passing locally with a dockerized oCIS. Restarted CI to see if it still fails. CI for this PR is running with the latest oCIS master, I was testing locally with a dockerized `owncloud/ocis:latest`, which should be the same.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18484/24/1
The following scenarios passed on retry:
- webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature:104

**Comment by ownclouders** [comment]
Results for <strong>oC10CreateDelete</strong> https://drone.owncloud.com/owncloud/web/18484/9/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:59

**Review by kulmann — APPROVED** [review]
LGTM 👌🏼

**Pull request merged**
