### PR TITLE
[WIP] [full-ci] Add compatibility with Guzzle 7

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
https://github.com/owncloud/core/pull/39368 bumps Guzzle to v7 in core. Use the new `GuzzleHttp\Psr7\MimeType` class to determine mime types.

Also fixed some wrong indentations.

**This is not supposed to be merged yet!**

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## To-Do's:

- [ ] Raise minimum OC version to 10.9 (or whatever OC version the Guzzle update lands in)
- [ ] Changelog

### CODE REVIEW

**Comment by pascalwengerter** [comment]
@JammingBen we had a successful CI run for OC10.9 in #6063 - is this PR still relevant aka is it waiting for the official 10.9 release?

**Comment by JammingBen** [comment]
We decided to wait with this after 10.9 has been released. So still relevant, but "on hold" :)

**Comment by pascalwengerter** [comment]
> We decided to wait with this after 10.9 has been released. So still relevant, but "on hold" :)

Ping for updating this one, should be fine to merge soon I suppose now that 10.9 is out in the wild 🐗

**Comment by phil-davis** [comment]
I rebased this just now. We are still waiting for a decision on when to merge the core Guzzzle7 PR.

core oC 10.9 and 10.10 still use Guzzle5.

**Comment by kulmann** [comment]
> I rebased this just now. We are still waiting for a decision on when to merge the core Guzzzle7 PR.
> 
> core oC 10.9 and 10.10 still use Guzzle5.

For clarification: this means that we need to bump a new major version when this PR is merged, correct? I.e. Immediate incompatibility with ownCloud up to `10.10`, right?

**Comment by phil-davis** [comment]
> For clarification: this means that we need to bump a new major version when this PR is merged, correct? I.e. Immediate incompatibility with ownCloud up to 10.10, right?

core master now has Guzzle7 - that will be 10.11 release when it happens. Nowadays CI only tests against core latest (currently 10.10), which does not have Guzzle7.

`Mimetype::fromFilename` is the main change here.

This PR will need to be merged and a release made for web to work all correctly with oC10.11. And that release won't work with 10.10 and before. So what to do:
- support 2 release streams for a while, releasing web patches/features in 2 release streams?
- change this code so that it checks/discovers which of `GuzzleHttp\Mimetypes` or `GuzzleHttp\Psr7\MimeType` exists at run-time and executes the appropriate code for `private function getMimeType`
- or ?

**Comment by jnweiger** [comment]
Web 5.7.0 on core 10.11.0-alpha.2 fails to start with internal server error. 

The logfile has:

```
{"reqId":"YvOypmH0RNAAl-7XZSJVNAAAAAc","level":3,"time":"2022-08-10T13:29:10+00:00","remoteAddr":"46.114.89.20","user":"admin","app":"index","meth
od":"GET","url":"\/index.php\/apps\/web\/index.html","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'GuzzleHttp\\\\Mimetypes' 
not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps-external\\\/web\\\/lib\\\/Controller\\\/FilesController.php(107): OCA\\\\
Web\\\\Controller\\\\FilesController->getMimeType()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(17
0): OCA\\\\Web\\\\Controller\\\\FilesController->getFile()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher
.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.p
hp(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/Rout
eActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\App
Framework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(914): OC\\\\Route\\\\Router->match()\\n#
7 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps-external\\\/web\\\/
lib\\\/Controller\\\/FilesController.php\",\"Line\":136}"}
```


With files_primary_s3, @phil-davis  did some magic to support both, guzzle7 and guzzle5 simultaenously. Mabye we should do something similar here?

**Comment by phil-davis** [comment]
> With files_primary_s3, @phil-davis did some magic to support both, guzzle7 and guzzle5 simultaenously. Mabye we should do something similar here?

Link to "magic" https://github.com/owncloud/files_primary_s3/pull/583

We can find out at run-time whatg Guzzle is available by checking for the existence and value of `\GuzzleHttp\Client::MAJOR_VERSION`

**Comment by jnweiger** [comment]
Reproduced with web 5.6.1 on core 10.11.0-rc.1

@pmaier1 The web UI cannot be started at all. Is this a blocker?

**Pull request closed without merging**
