### PR TITLE
Redesign contextmenu

### LINKED ISSUE #6212: Redesign "Context Menu"
# Description
## User Stories

* > As a user I want Context Menus to be presented in an appealing and well structured way so that my cognitive costs are low.

## Value
- Reduce cognitive costs
- increase acceptance for the new Web UI

## Acceptance Criteria (Desktop)
- Style context menus according to the design
- reorder actions according to screenshot
- re-apply shadow or some visual hint to distiguish context menu clearly from background
- Cherry on Top 🍰: keylistener for arrow up/down 
- Not part of this story: The "?" on the right of an item.

## Definition of done
- Functional requirements
[ ] functionality described in the user story works
[ ] acceptance criteria are fulfilled
- Quality
[ ] codre review happened
[ ] CI is green
[ ] critical code received unit tests by the developer
[ ] automated tests passed (if automated tests are not available, this test needs to be created and passed
- Non-functional requirements
[ ] no sonar cloud issues

image

## Research (fyi)
checked other context menus; numbers indicate the position in the corresponding contextmenu.
image

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Needs https://github.com/owncloud/owncloud-design-system/releases/tag/v12.0.0-alpha18 (or perhaps an alpha19 *to be released*)

## Related Issue
- Fixes #6212

## Types of changes
- [X] New feature (non-breaking change which adds functionality)

## Checklist:
- [X] Spacing
- [x] Contextmenu sort order
- [ ] ~Raw button hover (via ODS)~
- [ ] ~Change buttons to 'fill' type in contextmenu~

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/22381/55/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:253

**Comment by ownclouders** [comment]
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/22421/69/1
The following scenarios passed on retry:
- webUIUserJourney/journey1.feature:11

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternal2</strong> https://drone.owncloud.com/owncloud/web/22421/60/1
The following scenarios passed on retry:
- webUISharingInternalUsers/shareWithUsers.feature:342

**Review by kulmann — APPROVED** [review]
LGTM 👍

**Pull request merged**
