### PR TITLE
[tests-only][full-ci]Test with middleware for web tests related to `dav.propfind.depth_infinity`

### PR DESCRIPTION
**Pull request by SagarGi**
### Description

This PR is to check if all tests related to `dav.propfind.depth_infinity` when set to 1 passes or not as  OC 10.10 by default does not allow to request depth=infinity in PROPFIND:

Part of: https://github.com/owncloud/web/issues/7029

### CODE REVIEW

**Comment by pascalwengerter** [comment]
Hey @SagarGi, for a quicker feedback loop consider commenting out the unit&E2E tests 😉

**Comment by saw-jan** [comment]
CI uses yarn v3. `yarn install` stuck for middleware. I have used npm instead of yarn.

**Comment by ownclouders** [comment]
Results for <strong>oCISBasic</strong> https://drone.owncloud.com/owncloud/web/25933/44/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIPreview-mediaPreview_feature-L106.png
  

### webUIPreview-mediaPreview_feature-L114.png
  

### webUIPreview-mediaPreview_feature-L122.png
  

### webUIPreview-mediaPreview_feature-L138.png
  

### webUIPreview-mediaPreview_feature-L139.png
  

### webUIPreview-mediaPreview_feature-L14.png
  

### webUIPreview-mediaPreview_feature-L140.png
  

### webUIPreview-mediaPreview_feature-L143.png
  

### webUIPreview-mediaPreview_feature-L15.png
  

### webUIPreview-mediaPreview_feature-L153.png
  

### webUIPreview-mediaPreview_feature-L16.png
  

### webUIPreview-mediaPreview_feature-L18.png
  

### webUIPreview-mediaPreview_feature-L25.png
  

### webUIPreview-mediaPreview_feature-L35.png
  

### webUIPreview-mediaPreview_feature-L56.png
  

### webUIPreview-mediaPreview_feature-L57.png
  

### webUIPreview-mediaPreview_feature-L60.png
  

### webUIPreview-mediaPreview_feature-L68.png
  

### webUIPreview-mediaPreview_feature-L77.png
  

### webUIPreview-mediaPreview_feature-L84.png
  

### webUIPreview-mediaPreview_feature-L91.png
  

### webUIPreview-mediaPreview_feature-L98.png
  


</p></details>

**Comment by saw-jan** [comment]
@SagarGi  Looks like the middleware from docker has some pre-setups. I will suggest making a pre-release of middleware and testing with that tag.

**Comment by saw-jan** [comment]
Tested with `testForDavInfinity` branch of middleware. Looks like the tests are okay with the changes in the middleware.
CI job: https://drone.owncloud.com/owncloud/web/25942/1/1

@SagarGi you can release a tag in the middleware after this (https://github.com/owncloud/owncloud-test-middleware/pull/117) PR is merged and bump the middleware tag here.

**Review by pascalwengerter — APPROVED** [review]
@individual-it @phil-davis can we merge this? :)

**Comment by pascalwengerter** [comment]
And does it close #7065 then?

**Comment by individual-it** [comment]
@pascalwengerter you mean closing #7029?

**Comment by pascalwengerter** [comment]
> @pascalwengerter you mean closing #7029?

Sry yes, that's what I mean

**Pull request merged**
