### PR TITLE
Bump ocis commit id

### PR DESCRIPTION
**Pull request by fschade**
## Description
Bump ocis

## Related Issue
- Needs https://github.com/owncloud/ocis/pull/3228 
- Fixes https://github.com/owncloud/web/issues/6478

### CODE REVIEW

**Review by pascalwengerter — COMMENTED** [review]
Doesn't bump a commit ID? Also would recommend to run as [full-ci] to see all failures!

**Comment by fschade** [comment]
@pascalwengerter as soon as we have the commit id i bump it.
Its still a pending ocis PR!

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles4</strong> https://drone.owncloud.com/owncloud/web/23148/58/1
The following scenarios passed on retry:
- webUIRenameFolders/renameFolders.feature:142

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic2</strong> https://drone.owncloud.com/owncloud/web/23148/68/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicManagement-shareByPublicLink_feature-L78.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Review by pascalwengerter — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic2</strong> https://drone.owncloud.com/owncloud/web/23199/68/1
The following scenarios passed on retry:
- webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:199

**Pull request merged**
