### PR TITLE
Add manager badge to project space overview

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
image

## Related Issue

- Fixes https://github.com/owncloud/web/issues/8640

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by AlexAndBear** [comment]
@tbsbdr @kulmann not 100 percent sure about this feature/implementation, can you check, especially when changing the tile size

**Comment by AlexAndBear** [comment]
@tbsbdr @kulmann I favored for the assigned role icon and updated the screenshot

**Comment by tbsbdr** [comment]
Im not convinced of this solution. It adds too much visual info upfront that always need to be processed vs. i assume the usecase to be quite rare.
Alterative approach could be to add a filter.

**Comment by AlexAndBear** [comment]
@tbsbdr could you comment this into respective issue ticket and close it ? @kulmann was also not convinced

**Pull request closed without merging**
