### PR TITLE
Remove not needed share filtering code

### PR DESCRIPTION
**Pull request by JanAckermann**
## Description
Remove share filtering, due to https://github.com/owncloud/ocis/issues/3592 is fixed 

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublic1</strong> https://drone.owncloud.com/owncloud/web/28372/37/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicExpire-shareByPublicLinkExpiringLinks_feature-L106.png
  


</p></details>
:boom: The oC10SharingPublic1 tests pipeline failed. The build has been cancelled.

**Comment by JanAckermann** [comment]
Oh c'mon

**Comment by phil-davis** [comment]
> Oh c'mon

https://drone.owncloud.com/owncloud/web/28372/37/20
Error: Scenario webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:106 failed but was not expected to fail.'

The test is trying to choose an expiration date +15 days in the future. That is 1 Oct 2022. I suspect that there is some problem with the test code accessing the first day of the next month, or... Navigating the date-picker in tests is painful - there are lots of possibilities depending on which day of the week each month starts on, and how the "5" weeks of a month get displayed...

I have asked for someone to have a look.

**Comment by amrita-shrestha** [comment]
@SwikritiT will be looking in this

**Comment by SwikritiT** [comment]
the issue here is this https://github.com/owncloud/web/issues/7513, the test tries to select `+15` which is next month `oct`, and when the test attempts to select the month oct the scroller scrolls up and the test cannot select the month. 

https://user-images.githubusercontent.com/41103328/190571837-58445199-29a0-4afe-bc53-d27029844450.mp4



I'll add a commit skipping the test to unblock this PR

**Comment by SwikritiT** [comment]
The ci is green

**Review by phil-davis — APPROVED** [review]

**Comment by JanAckermann** [comment]
Thx 👍👍👍

**Pull request merged**
