### PR TITLE
make openidconnect in oC10 possible

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
One can currently not use ownCloud Web with ownCloud 10 and OpenID connect, because proper content policies are missing and calls to the OIDC provider will fail.

## Related Issue

- none

## Motivation and Context
The oCIS migration strategy requires to run ownCloud 10 with OIDC and Web. This is currently not possible.

## How Has This Been Tested?

- https://github.com/owncloud/ocis/pull/2302

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/17477/10/1
The following scenarios passed on retry:
- webUISharingAcceptShares/acceptShares.feature:109

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/17477/39/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:356

**Review by kulmann — APPROVED** [review]
Could you add a bugfix changelog item please? I think I missed that for the onlyoffice and richdocuments CSP rules myself, but would be nice to have one here. :-) code looks good to me, thanks for taking care! 💪🏻

**Review by butonic — APPROVED** [review]
😍

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/17482/39/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:356

**Comment by wkloucek** [comment]
@fschade you're right OIDC should be part of the Documentation https://owncloud.dev/clients/web/deployments/oc10-app/. Only oAuth is mentioned there until now

**Comment by pascalwengerter** [comment]
I'd love to get this merged and would try to release a `v3.4.2` (= bugfix only release) in web early next week and even ship that one with the OC10.8 release if possible?

**Comment by wkloucek** [comment]
> I'd love to get this merged and would try to release a `v3.4.2` (= bugfix only release) in web early next week and even ship that one with the OC10.8 release if possible?

for me that would be fine. But would need coordination with @micbar

**Comment by kulmann** [comment]
@wkloucek do you want to add documentation to this PR or add that in a separate PR?

**Comment by wkloucek** [comment]
I'll open a separate PR.

**Pull request merged**
