### PR TITLE
[Tests-Only] Skip file deletion fail in public share

### PR DESCRIPTION
**Pull request by HariBhandari07**
## Description

Skip failing scenarios for file deletion in public share. Deletion of multiple file fail with file locked error.
Also, scenarios with a batch deletion that are likely to fail have been skipped in order to make CI green.
## Related Issue

- https://github.com/owncloud/web/issues/4878
## How Has This Been Tested?

- CI
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by individual-it — CHANGES_REQUESTED** [review]
lets only use `@skipOnOC10` I think they work fine on ocis

**Review by individual-it — APPROVED** [review]

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14079/

<p>





</p></details>

**Comment by individual-it** [comment]
next failure `webUISharingPublic/shareByPublicLink.feature:825` with the same locking issue

**Comment by dpakach** [comment]
Isn't this issue intermittent, in that case, won't we have the same issue when it passes randomly?

**Pull request merged**
