### PR TITLE
[Tests-Only][full-ci] increase the wait for condition timeout to 10s for acceptance tests

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Fix the wait for condition timeout to reduce flaky tests in CI.
More information in https://github.com/owncloud/web/issues/6053
https://github.com/owncloud/web/issues/6053#issuecomment-978964065

## Related Issue

- Fixes https://github.com/owncloud/web/issues/6053

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/20511/16/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Review by fschade — APPROVED** [review]
🤖

**Review by kulmann — CHANGES_REQUESTED** [review]
Please re-run with `[full-ci]`. I'd like to see the total CI runtime.

**Comment by dpakach** [comment]
@kulmann I ran the tests with [full-ci] and the time is almost the same. Some pipelines took longer because yarn-install step took about 4 minutes on some pipelines which should be done in 15 seconds but that is an unrelated issue.

**Review by kulmann — APPROVED** [review]

**Pull request merged**
