### PR TITLE
Reorder components structure in web-app-files

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Got confused while working on the `Details` section in the sidebar so decided to give this an overhaul

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>oC10iPhone1</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/web/16785/43/1

**Comment by pascalwengerter** [comment]
**Update:**

Rebased on current master and fixed unit test import paths.

The structure and naming could still be improved but let's do this down the road when refactoring/redesigning the whole sidebar

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublicManagement</strong>
The following scenarios passed on retry:
- webUISharingPublicManagement/publicLinkIndicator.feature:27

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong>
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by ownclouders** [comment]
Results for <strong>oC10XGAPortrait1</strong>
:boom: Acceptance tests pipeline <strong>oC10XGAPortrait1</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/web/16790/40/1

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsersRoot2</strong>
<details><summary>:boom: Acceptance tests <strong>oC10SharingInternalUsersRoot2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16792/

<p>


### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-109.png
  


</p></details>
:boom: Acceptance tests pipeline <strong>oC10SharingInternalUsersRoot2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/web/16792/28/1

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong>
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Review by kulmann — CHANGES_REQUESTED** [review]
Hmmm.. while I really like the re-structuring into subfolders (makes it a LOT more easy to get an overview), there is an official vue code style rule "Multi-word component names", which is ~~strongly recommended~~ essential: https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential

What I see a lot in your changes (maybe due to the way you refactored) is that components have a single word filename but are imported with a multi word alias. That's something I'd like to avoid - component aliases should always be the same as their file name. Otherwise it makes it again harder to find stuff.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong>
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Review by kulmann — APPROVED** [review]
Thanks for cleaning this up! Folder structure looks easier to digest. 🚀

**Pull request merged**
