### PR TITLE
feat: add custom date range filter

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
Adds a filter for custom date ranges. This is needed for the soon to come activities app.

The filter stores the custom dates in a query param as milliseconds because that's a nice format for URLs. That means the implementing party might need to convert it to an actual date when working with the filter.

image

image

## Related Issue

- Closes https://github.com/owncloud/web/issues/11546

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

### CODE REVIEW

**Comment by JammingBen** [comment]
I temporarily added the new filter to the search result page for testing. This needs to be reverted before merging though as the search currently can't deal with custom date ranges.

**Comment by AlexAndBear** [comment]
image
The apply button looks deactivated

**Review by AlexAndBear — APPROVED** [review]
LGTM,
look and feel is top notch.

You could use the min-date prop on the from date picker, so a warning will be shown when the from date is after the to date. 

As well I am not too sure about the x button, it's super handy, but we don't have it elsewhere in our drop menus, so it would create an inconsistency 🤔

**Comment by JammingBen** [comment]
> You could use the min-date prop on the from date picker, so a warning will be shown when the from date is after the to date.

Good idea, fixed 👍 

> As well I am not too sure about the x button, it's super handy, but we don't have it elsewhere in our drop menus, so it would create an inconsistency 🤔

Tbh the main reason I did this is because the layout of back button - title - close button looks good (see right sidebar). No strong opinion though.

**Pull request merged**
