### PR TITLE
[tests-only] [full-ci] Bump commit ids for testing

### PR DESCRIPTION
**Pull request by saw-jan**
## Description
This PR bumps core and oCIS commit ids to the latest

## Related Issue
- Part of  https://github.com/owncloud/QA/issues/689

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/19164/40/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:356

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/19164/39/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:363

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/19176/40/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:356

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/19181/24/1
The following scenarios passed on retry:
- webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature:124

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/19181/28/1
The following scenarios passed on retry:
- webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature:98

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/19190/24/1
The following scenarios passed on retry:
- webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature:104

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/19190/47/9
`FetchError: request to https://ocis:9200/ocs/v2.php/cloud/users/Alice?format=json failed, reason: getaddrinfo ENOTFOUND ocis`

Is that some drone agent network error?

I will restart CI.

**Review by phil-davis — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/19191/12/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:36
- webUIFilesActionMenu/versions.feature:15

**Pull request merged**
