### PR TITLE
[Tests-Only]Debugging fail in files rename tests in drone

### PR DESCRIPTION
**Pull request by Talank**

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename10</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13783/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename3</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13783/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename9</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13783/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13783/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename6</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13783/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename4</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13788/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename6</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13788/

<p>





</p></details>

**Comment by Talank** [comment]
Made a new issue to investigate further.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13830/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename10</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13830/

<p>





</p></details>

**Pull request closed without merging**
