### PR TITLE
Update info.xml for release

### PR DESCRIPTION
**Pull request by pmaier1**
Please check @micbar @dragotin @phil-davis

### CODE REVIEW

**Review by LukasHirt — APPROVED** [review]
LGTM :rocket:

**Review by micbar — APPROVED** [review]

**Comment by phil-davis** [comment]
This will need a rebase after #4485 is merged. That will get CI  green.

**Comment by phil-davis** [comment]
@dirkstascheit please click the buttons to "sign" the CLA

**Comment by LukasHirt** [comment]
@pmaier1 Pls, rebase this PR so the CI is passing (fix was merged in different PR). Thanks!

**Comment by micbar** [comment]
rebased to make CI happy

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
