### PR TITLE
[do-not-merge][tests-only]Run flaky test multiple times in CI

### PR DESCRIPTION
**Pull request by SwikritiT**
## Related Issue

- https://github.com/owncloud/web/issues/5853

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/19371/7/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:277
- webUIFilesActionMenu/versions.feature:167
- webUIFilesActionMenu/versions.feature:189
- webUIFilesActionMenu/versions.feature:222
- webUIFilesActionMenu/versions.feature:233
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/19372/7/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:277
- webUIFilesActionMenu/versions.feature:321
- webUIFilesActionMenu/versions.feature:310
- webUIFilesActionMenu/versions.feature:101
- webUIFilesActionMenu/versions.feature:299
- webUIFilesActionMenu/versions.feature:343
- webUIFilesActionMenu/versions.feature:233
- webUIFilesActionMenu/versions.feature:332
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/19373/7/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:101
- webUIFilesActionMenu/versions.feature:288
- webUIFilesActionMenu/versions.feature:354
- webUIFilesActionMenu/versions.feature:156
- webUIFilesActionMenu/versions.feature:343
- webUIFilesActionMenu/versions.feature:178
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/19375/7/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:112
- webUIFilesActionMenu/versions.feature:310
- webUIFilesActionMenu/versions.feature:343
- webUIFilesActionMenu/versions.feature:233
- webUIFilesActionMenu/versions.feature:178
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
@SwikritiT is there a specific reason to run this debugging in CI? Please refer to https://owncloud.dev/clients/web/testing/ for local debugging of the acceptance tests & a fast feedback loop since you don't need all the setup steps

**Comment by SwikritiT** [comment]
> @SwikritiT is there a specific reason to run this debugging in CI? Please refer to https://owncloud.dev/clients/web/testing/ for local debugging of the acceptance tests & a fast feedback loop since you don't need all the setup steps

The tests are passing locally for me (even if I run it multiple times) but it fails on CI.

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/19406/7/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:168
- webUIFilesActionMenu/versions.feature:323
- webUIFilesActionMenu/versions.feature:400
- webUIFilesActionMenu/versions.feature:245

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/19408/7/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:168
- webUIFilesActionMenu/versions.feature:323
- webUIFilesActionMenu/versions.feature:400
- webUIFilesActionMenu/versions.feature:245

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/19410/7/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:345

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/19413/7/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:168
- webUIFilesActionMenu/versions.feature:411
- webUIFilesActionMenu/versions.feature:334

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/19418/7/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/19420/7/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/19438/7/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>webUIFilesActionMenu</strong> https://drone.owncloud.com/owncloud/web/19439/7/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/19440/7/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/19447/7/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUIFilesActionMenu-versions-feature.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/19462/7/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUIFilesActionMenu-versions-feature.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/19506/7/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUIFilesActionMenu-versions-feature.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/19525/7/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUIFilesActionMenu-versions-feature.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Pull request closed without merging**
