### PR TITLE
[tests-only][full-ci] Bump middleware image from 1.2.0 to 1.2.1

### PR DESCRIPTION
**Pull request by saw-jan**
## Description
Bump middleware docker image from 1.2.0 to 1.2.1 for tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
LGTM if CI passes.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/22152/15/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingAcceptSharesToRoot-acceptShares_feature-L108.png
  


</p></details>

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/22152/15/21
```
runsh: Total unexpected failed scenarios throughout the test run:
webUISharingAcceptSharesToRoot/acceptShares.feature:108
```

IMO that already has an issue for intermittent failure. I will report there, and restart CI.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublic1</strong> https://drone.owncloud.com/owncloud/web/22154/37/1
The following scenarios passed on retry:
- webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:147

**Pull request merged**
