### PR TITLE
[full-ci] Bump ocis commit id to 8d4f4f8ccea02337fb0a2f123b2f22afc22013e0

### PR DESCRIPTION
**Pull request by kulmann**
Since the CI in ocis repo fails (hard) for https://github.com/owncloud/ocis/pull/2929 we'll check the other way around here as well (if web CI fails with bumped ocis commit id).

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp1</strong> https://drone.owncloud.com/owncloud/web/21592/68/1
The following scenarios passed on retry:
- webUIPrivateLinks/accessingPrivateLinks.feature:17

**Comment by pascalwengerter** [comment]
Has failing pipelines for both OC10 and oCIS. Perhaps needs some of the CI config adaptions from #6204?

**Comment by pascalwengerter** [comment]
> Has failing pipelines for both OC10 and oCIS. Perhaps needs some of the CI config adaptions from #6204?

Nope, turns out the middleware is currently broken

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles2</strong> https://drone.owncloud.com/owncloud/web/21630/56/1
The following scenarios passed on retry:
- webUIMarkdownEditor/markdownFile.feature:29

**Pull request closed without merging**
