### PR TITLE
[test-only] e2e.Delete creating link to space step

### PR DESCRIPTION
**Pull request by ScharfViktor**
https://github.com/owncloud/ocis/pull/6271
https://github.com/owncloud/ocis/issues/6278

Sharing of project space root via public link does no longer work -> I changed test to enable e2e tests again

### CODE REVIEW

**Review by SwikritiT — APPROVED** [review]
LGTM

**Comment by JammingBen** [comment]
Sorry, I don't get it: That means creating public links for spaces is no longer possible?! Because the UI currently doesn't reflect that.

**Comment by ScharfViktor** [comment]
> Sorry, I don't get it: That means creating public links for spaces is no longer possible?! Because the UI currently doesn't reflect that.

Yes, public link for project space disabled. https://github.com/owncloud/ocis/issues/6278#issuecomment-1543662136

This PR will return e2e to ocis

**Review by JammingBen — APPROVED** [review]
Approving to get the pipeline running, but we might need to re-add the steps later again. I think it was a misunderstanding and creating links for project spaces should still be possible in the future.

**Comment by ScharfViktor** [comment]
> Approving to get the pipeline running, but we might need to re-add the steps later again. I think it was a misunderstanding and creating links for project spaces should still be possible in the future.

Yes, sure. When or if we are able to create a link I will return deleted tests

**Pull request merged**
