### PR TITLE
Improve wording of access denied message to user

### PR DESCRIPTION
**Pull request by rpocklin**
## Description
We have had much feedback that the existing message, while not incorrect is confusing for users where their session has expired or been logged out.  There may be multiple scenarios where users come to this page but it should cater for all of these an explain what has happened in a clear way.

Totally open to alterations on this message - it's an important page to communicate what has happened to the user.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

### CODE REVIEW

**Comment by phil-davis** [comment]
Note: there is a new drone pipeline "stop-recent-builds". That is failing for PRs from a fork, like this one.

I raised issue https://github.com/owncloud/web/issues/5640 - we will have a look and sort that out...

**Review by pascalwengerter — APPROVED** [review]

**Comment by pascalwengerter** [comment]
@kulmann force-merge if you agree? Doesn't need acceptance tests imho

**Review by kulmann — APPROVED** [review]
Good change, thanks. Even nicer that it's based on user feedback 😍

**Comment by phil-davis** [comment]
> Doesn't need acceptance tests imho

Agree - that text string is not referred to explicitly by any test.

**Pull request merged**
