### PR TITLE
[stable] refactor: switch to upstream uppy on stable

### PR DESCRIPTION
**Pull request by dschmidt**
## Description
This is basically a backport of #12052 - 

## Motivation and Context
I would usually not recommend this kind of change on the stable branch, but if we want to update Uppy and Companion in the relevant production setup, we need it.

Up to you @kobergj @LukasHirt 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by LukasHirt** [comment]
> I would usually not recommend this kind of change on the stable branch, but if we want to update Uppy and Companion in the relevant production setup, we need it.

We discussed this with @kobergj and we will not include it in the next stable release (11.1.0) as we already are going to backport new notifications settings and we want to keep the release very lean.

**Comment by dschmidt** [comment]
ok, so do you want to merge it to this stable branch after the release or shall we close this PR and target only the main branch?

**Comment by LukasHirt** [comment]
Release is planned for January. I'd say let's drop this PR now and we can later on bring it together probably also with some bugfixes in one new PR. But I'd prefer @kobergj to confirm this.

**Comment by kobergj** [comment]
Sounds good to me 👍🏻

**Pull request closed without merging**
