### PR TITLE
Introduce UPSERT_RESOURCE to files mutations

### LINKED ISSUE #4996: Creating a new version of a file shows it duplicated in the file list (until page reload)
### Steps to reproduce
1. Run ocis v1.5.0-rc1 (or final) - issue is the same with oc10
2. upload a file
3. upload the same file again, creating a new version

### Expected behaviour
The file list row should be updated with the new version of the file.

### Actual behaviour
The new upload appears as duplicate in the file list. A page reload works for showing only one of them again.

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Merged PUSH_NEW_RESOURCE and UPDATE_RESOURCE to UPSERT_RESOURCE that checks if a file already exists and then either inserts *or* updates the resource

## Related Issue
- Fixes #4996

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsersRoot2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15561/

<p>


### webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-54.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsersRoot1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15561/

<p>


### webUISharingInternalUsersToRoot-shareWithUsers-feature-260.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublicBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15561/

<p>


### webUISharingPublicBasic-publicLinkPublicActions-feature-12.png
  


</p></details>

**Review by kulmann — APPROVED** [review]
good simplification 🤩

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15566/

<p>


### webUIFavorites-favoritesFile-feature-58.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15566/

<p>


### webUILogin-adminBlocksUser-feature-20.png
  

### webUIPreview-imageMediaViewer-feature-140.png
  

### webUIPreview-imageMediaViewer-feature-158.png
  

### webUIPreview-imageMediaViewer-feature-83.png
  

### webUIPreview-imageMediaViewer-feature-90.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15566/

<p>


### webUIRenameFiles-renameFiles-feature-186.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15567/

<p>


### webUIFavorites-favoritesFile-feature-58.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15572/

<p>


### webUIFavorites-favoritesFile-feature-58.png
  

### webUIFavorites-favoritesFile-feature-80.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15572/

<p>


### webUIRenameFiles-renameFiles-feature-186.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15575/

<p>


### webUIFavorites-favoritesFile-feature-58.png
  

### webUIFavorites-favoritesFile-feature-80.png
  


</p></details>

**Comment by kulmann** [comment]
Test scenario `webUIFavorites/favoritesFile.feature:58` is an actual failure, not a random one. Needs to be fixed.

**Comment by pascalwengerter** [comment]
> Test scenario `webUIFavorites/favoritesFile.feature:58` is an actual failure, not a random one. Needs to be fixed. It's succeeding on current master.

Thanks, will take care of this now!

**Comment by pascalwengerter** [comment]
> > Test scenario `webUIFavorites/favoritesFile.feature:58` is an actual failure, not a random one. Needs to be fixed. It's succeeding on current master.
> 
> Thanks, will take care of this now!

Can't really figure why this should be an actual failure 🤔  the CI is waiting (and then timing out) for `.files-empty` which I can see when navigation to the page myself - and the changes in this PR don't touch anything related to it AFAIK

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15583/

<p>


### webUIRenameFiles-renameFiles-feature-186.png
  


</p></details>

**Comment by kulmann** [comment]
> > > Test scenario `webUIFavorites/favoritesFile.feature:58` is an actual failure, not a random one. Needs to be fixed. It's succeeding on current master.
> > 
> > 
> > Thanks, will take care of this now!
> 
> Can't really figure why this should be an actual failure 🤔 the CI is waiting (and then timing out) for `.files-empty` which I can see when navigation to the page myself - and the changes in this PR don't touch anything related to it AFAIK

When I run the test locally I see a file in the favorites list. No idea why though. But it has to be related to the changes. `UDATE_RESOURCE` didn't do anything before if the id of the resource in the params was not found. Maybe that's the case for some favorites list update action and then it now inserts it while it shouldn't. Or a test (fixture?) bug related to this which didn't surface before.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15586/

<p>


### webUIFavorites-favoritesFile-feature-80.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15586/

<p>


### webUIRenameFiles-renameFiles-feature-186.png
  


</p></details>

**Comment by kulmann** [comment]
The issue why the test is failing is a sneaky bug, that was already pointed out by @labkode in https://github.com/owncloud/web/issues/5085

You can reproduce it by clicking very fast on the `All Files` menu item, not waiting until it's fully rendered but directly clicking on `Favorites` again. What you can observe then, is that the files that have async preview requests will appear in the `Favorites` view. Because they get inserted now with this PR (as it switches from update to upsert for the preview responses).

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15730/

<p>


### webUIRenameFiles-renameFiles-feature-186.png
  


</p></details>

**Comment by fschade** [comment]
the request cancelation bug is tracked in https://github.com/owncloud/web/issues/5163

**Comment by kulmann** [comment]
Re-introduced the `UPDATE_RESOURCE` store action, because in most of the situations we don't want to allow an insert. But for the upload scenarios the `UPSERT_RESOURCE` makes sense and solves the bug with two versions of the same file being displayed as two files in the list.

**Comment by micbar** [comment]
❤️ Unit tests

**Review by fschade — APPROVED** [review]
👍 LGTM

**Pull request merged**
