### PR TITLE
[tests-only] fix fileNotExists function in acceptance tests

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Related https://github.com/owncloud/owncloud-test-middleware/issues/61 
Fix the status code check in fileShouldNotExist in acceptance tests

## How Has This Been Tested?

:robot:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/20997/15/1
The following scenarios passed on retry:
- webUISharingAcceptShares/acceptShares.feature:111

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/20997/16/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/20999/16/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/21001/55/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/21004/16/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/21005/55/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Review by phil-davis — APPROVED** [review]
LGTM.

**Comment by phil-davis** [comment]
@dpakach looks good - please fill in some text in the PR, then make "Ready for Review" and merge if you are finished with this.

**Pull request merged**
