### PR TITLE
[full-ci] refactor pagination into composable, cleanup store, views and tests

### PR DESCRIPTION
**Pull request by fschade**
## Description
See #6048 

## Related Issue
- Part of #6048

## Motivation and Context
clean code ™️ 

## How Has This Been Tested?
- unit tests
- integration tests

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Technical debt
- [X] Tests

## Checklist:
- [X] Code changes
- [X] Unit tests added

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10Basic</strong> https://drone.owncloud.com/owncloud/web/20505/12/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/20518/16/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/20518/17/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Review by kulmann — APPROVED** [review]
The duplication of pagination templates is a bit verbose. Could still live in a dedicated `pagination` component with a few props. Would be more or less a template-only component. `v-if` should be placed in the views like you have it now, not inside the component.

Please decide for yourself if you want to do that in this PR or in a separate one to get this awesome change going fast. 🚀

**Comment by fschade** [comment]
> The duplication of pagination templates is a bit verbose. Could still live in a dedicated `pagination` component with a few props. Would be more or less a template-only component. `v-if` should be placed in the views like you have it now, not inside the component.
> 
> Please decide for yourself if you want to do that in this PR or in a separate one to get this awesome change going fast. 🚀

good point, done expect the outer if decision, i think in the case of this component where a pages of 0 is a potential displaying glitch its ok to have it battery included inside the component and let it decide on its own what to do.

THANKS for your review ❤️

**Pull request merged**
