### PR TITLE
Add URL handling to markdown-editor (fixes #5928)

### LINKED ISSUE #5928: closing the file editor routes back to all files page
### Steps to reproduce
1. create a folder `zzz`
2. click the new button and choose `New plain text file...` or any other new file option
3. add some text to the new file and hit the save button on the editor page
4. now click the close button i.e present at right of the editor page

### Expected behaviour
- user should get land on `All files / zzz` page

### Actual behaviour
- user lands on `All files` page

### Environment general
**Operating system**: Ubuntu

**Backend (ownCloud Core or Infinite Scale)**: same using any of the backends

**Are you using an external user-backend, if yes which one:** No

> please close the issue if this is an expected behaviour

### PR DESCRIPTION
**Pull request by dschmidt**
## Description
This adds URL handling to the markdown editor. Allows us to return to the source folder of the file and to reopen the editor on page reload.

I copied a bit of code from the web-app-mediaviewer. Where can we share this kind of code?

## Related Issue

- Fixes #5928 
- based on  #6290 
## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10iPhoneNotifications</strong> https://drone.owncloud.com/owncloud/web/20915/48/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/20915/44/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10XGAPortrait1</strong> https://drone.owncloud.com/owncloud/web/20915/46/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10XGAPortraitNotifications</strong> https://drone.owncloud.com/owncloud/web/20915/45/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISBasic</strong> https://drone.owncloud.com/owncloud/web/20915/51/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by dschmidt** [comment]
This fixes a few issues already, but should become way more useful and more resilient after #6156 is merged and it's ported to those apis.

**Comment by dschmidt** [comment]
Make sure this is fixed by this PR: https://github.com/owncloud/web/issues/5276

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/22096/10/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22096/2022-1-22-01-43-10-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22096/2022-1-22-01-44-01-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22096/2022-1-22-01-45-02-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22096/2022-1-22-01-45-22-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22096/2022-1-22-01-46-14-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22096/2022-1-22-01-46-58-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22096/2022-1-22-01-47-42-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22096/2022-1-22-01-48-05-Brian.zip 


</p></details>

**Comment by kulmann** [comment]
https://github.com/owncloud/web/pull/6290 is merged, please rebase :-)

**Review by kulmann — APPROVED** [review]
LGTM 👍

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/22108/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic2</strong> https://drone.owncloud.com/owncloud/web/22108/65/1
The following scenarios passed on retry:
- webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:78

**Comment by diocas** [comment]
@dschmidt @kulmann this PR introduced, at least, into drawio the same issue as reported in #6069 and #6045 :
If you set the `auth: false` into the routes, then if I try to directly (before being authenticated) open a file, I'm never redirected to the idp and the page is blank.

I don't know if the solution should be to create separate routes with auth on and off (as I did as a quick workaround in #6151) or if the new composable logic should check the auth status for personal routes.

**Comment by kulmann** [comment]
I'm currently looking into building a composable that handles the authentication redirect. I'd like to avoid adding extra routes for public links.

**Pull request merged**
