### PR TITLE
[full-ci] Only show batch actions for more than one selected resource

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
~Kinda experimental
**Note:** AppBar/SizeInfo/BatchAction unit tests need a major overhaul before this can get merged~ now that #6662 got merged this can be easily continued

## Related Issue
- Fixes *to_be_defined*

## Motivation and Context
Reduce "jumpiness" of UI, only show batch actions above files table when relevant

## TO-DOs
- [ ] Refactor AppBar/SizeInfo/BatchAction unit tests
- [ ] Green E2E & Acceptance tests
- [ ] Changelog item

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/22339/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22339/2022-2-1-08-15-40-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22339/2022-2-1-08-15-46-Brian.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/22339/10/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22339/2022-2-1-08-16-43-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22339/2022-2-1-08-16-49-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22339/2022-2-1-08-17-03-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22339/2022-2-1-08-17-09-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22339/2022-2-1-08-17-50-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22339/2022-2-1-08-17-56-Brian.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAndTrashbin</strong> https://drone.owncloud.com/owncloud/web/22340/32/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUITrashbinDelete-trashbinDelete_feature-L99.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Move</strong> https://drone.owncloud.com/owncloud/web/22340/19/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIMoveFilesFolders-moveFiles_feature-L139.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/22340/64/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUITrashbinDelete-trashbinDelete_feature-L99.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Files5</strong> https://drone.owncloud.com/owncloud/web/22340/18/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIFiles-batchAction_feature-L113.png
  

### webUIFiles-batchAction_feature-L14.png
  

### webUIFiles-batchAction_feature-L24.png
  

### webUIFiles-batchAction_feature-L62.png
  

### webUIFiles-batchAction_feature-L75.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternal2</strong> https://drone.owncloud.com/owncloud/web/22340/56/1
The following scenarios passed on retry:
- webUISharingInternalUsers/shareWithUsers.feature:342

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/22340/53/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIFiles-batchAction_feature-L113.png
  

### webUIFiles-batchAction_feature-L14.png
  

### webUIFiles-batchAction_feature-L24.png
  

### webUIFiles-batchAction_feature-L62.png
  

### webUIFiles-batchAction_feature-L75.png
  


</p></details>

**Comment by pascalwengerter** [comment]
Needs a rebase once https://github.com/owncloud/web/pull/6358 is merged but should be quite easy to finalize ✊🏽

**Comment by pascalwengerter** [comment]
Needs a rebase, I'll take care of it today

**Comment by tbsbdr** [comment]
reduces unnecessary changes in the ui - feels really good  

NEW - what you see in the video: batch actions are only shown, if at least 2 items are selected. i.e. if only 1 item is selected, batch actions are not shown (batch of 1 items doesnt make sense imo)

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/24303/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/24303/tracing/folder-alice-2022-3-31-08-14-52.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/24303/tracing/folder-brian-2022-3-31-08-15-03.zip 


</p></details>

**Comment by tbsbdr** [comment]
received positive feedback on the changes :-) lets do it.
@elizavetaRa noted that the gaps between the buttons could be bigger to get a better impression of what icon belongs to which text 👍

would be nice, if the `Empty trashbin` button would not change to `raw`

Current:
image

proposal with gaps aligned:
image

fyi @ChrisEdS

**Review by tbsbdr — CHANGES_REQUESTED** [review]
@pascalwengerter could you align the gaps of the row as mentioned in
https://github.com/owncloud/web/pull/6351#issuecomment-1087459493
to be more precise:
Clipboard - June 15, 2022 7_06 PM

everything else is fine, thanks!

**Comment by JammingBen** [comment]
@tbsbdr Whats the state here? The batch actions changed meanwhile - they are outlined buttons now, I think that's fine. What about the change to only show batch actions if >1 files are selected?

**Comment by kulmann** [comment]
> @tbsbdr Whats the state here? The batch actions changed meanwhile - they are outlined buttons now, I think that's fine. What about the change to only show batch actions if >1 files are selected?

I personally really like the UX when only showing batch actions if >1 files are selected. I think we had a reason against it, but I don't remember. Do you @tbsbdr ?

**Comment by tbsbdr** [comment]
> don't remember

sry, me neither.

jep, should still go with the "Only show batch actions for more than one selected resource" approach.

**Comment by pascalwengerter** [comment]
I think I just never followed on with this PR fearing the huge pains when having to fix acceptance tests 🥴 hope someone else can pick up my changes and finish them for good?

**Comment by JammingBen** [comment]
This has been superseded by https://github.com/owncloud/web/pull/7904. Tests were indeed unpleasant to fix :D

**Pull request closed without merging**
