### PR TITLE
[tests-only][not-for-merge] test middleware v1.0.0

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
- check webci with owncloud-test-middleware v1.0.0

## Related Issue

- https://github.com/owncloud/owncloud-test-middleware/issues/79

## How Has This Been Tested?

- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by kiranparajuli589** [comment]
webci is happy with middleware v1.0.0
cc @individual-it @phil-davis

**Comment by phil-davis** [comment]
@kiranparajuli589 I thought that we want to merge this - to pin the middleware version before we make more middleware changes?

**Comment by kiranparajuli589** [comment]
> @kiranparajuli589 I thought that we want to merge this - to pin the middleware version before we make more middleware changes?

okay...we can merge this one :+1: !

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Merged - we are now pinning the middleware to a particular version. docker has version tags. This will prevent sudden CI fails when we make middleware changes. We can change the middleware, release a new version, and then bump the version used here in web CI.

**Pull request merged**
