### PR TITLE
[full-ci] debugging tests of #5924

### PR DESCRIPTION
**Pull request by individual-it**
- feat(public-links): retrieve capabilities early
- fetch capabilities in external app if not already present, this could happen if the url is bookmarked
- Add changelog
- fix unit tests
- Fix option type for public token

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternalUsers2</strong> https://drone.owncloud.com/owncloud/web/20080/58/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/20082/15/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:15

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/20097/15/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:15

**Comment by pascalwengerter** [comment]
Found the error and fixing it in #5924, closing this and thanks for investigating!

**Pull request closed without merging**
