### PR TITLE
[full-ci] Bump (peer)dependencies

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Supersedes some dependabot PRs and bumps the SDK's dependencies to their most recent versions (most interesting here is `axios`, originally had the bump included in #7139 but then had unexpected failures in the acceptance tests)

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/26548/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/26548/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2022-6-30-12-05-42.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/26548/tracing/folder-alice-2022-6-30-12-02-37.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/26548/tracing/participant-management-alice-2022-6-30-12-03-39.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/26548/tracing/public-link-alice-2022-6-30-12-01-36.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/26548/tracing/unstructured-collection-of-testable-space-interactions-alice-2022-6-30-12-04-40.zip 


</p></details>

**Comment by kulmann** [comment]
@individual-it @phil-davis could you / your team have a look at this PR? I rebased it to current master. CI is failing hard. I tried the first 6 tests locally and they were all passing. Priority is low, but would be nice to get some dependencies up to date.

**Comment by SagarGi** [comment]
@kulmann  Able to reproduce the CI failures locally. Will be digging into it.

**Comment by SagarGi** [comment]
@kulmann @phil-davis @individual-it The main reason behind the CI failure above is apparently `axios` version bump
While using axios `0.27.1` (bumped version) it gives an error `Failed to load the setting values` as a pop up notification.

(Reload with axios verison `0.27.1`)

https://user-images.githubusercontent.com/46086950/182801666-853919f4-404f-46c1-8252-2fdea50c925d.mp4

So the pop up notification seems to be the main reason for the CI failure.

When using axios version `0.26.1` there is no such pop up failure notification

(Reload with axios verison `0.26.1`)

https://user-images.githubusercontent.com/46086950/182802273-8973d09a-5006-42ce-a3d9-c304818e6372.mp4

Need further information regarding this.

**Comment by kulmann** [comment]
> @kulmann @phil-davis @individual-it The main reason behind the CI failure above is apparently `axios` version bump While using axios `0.27.1` (bumped version) it gives an error `Failed to load the setting values` as a pop up notification.

Thank you for the pointers. I made some changes in the code so that with an oc10 backend we will not query the settings at all anymore. That made the CI green.

**Review by kulmann — COMMENTED** [review]
Uh, I thought I approved the PR already before. Apparently I didn't. Classic `yolo` 🙈

**Pull request merged**
