### PR TITLE
[full-ci] Vue 3: Use createApp and update portal-vue

### PR DESCRIPTION
**Pull request by dschmidt**
## Description
Use new Vue 3 `createApp` api and update `portal-vue`.

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/31413/54/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIWebdavLockProtection-move_feature-L59.png
  

### webUIWebdavLockProtection-move_feature-L60.png
  


</p></details>
:boom: The oCISWebdavLockProtection tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/31414/41/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L54.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L55.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L56.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L57.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L58.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L59.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L60.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L61.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L62.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L63.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L64.png
  

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup_feature-L65.png
  


</p></details>

**Comment by dschmidt** [comment]
3.0.0 final is released, I'd appreciate if someone could update the pr tomorrow morning

**Review by JammingBen — APPROVED** [review]
LGTM 👍

**Pull request merged**
