### PR TITLE
Configurable text editor autosave

### PR DESCRIPTION
**Pull request by elizavetaRa**
## Description
- enables the autosave with a configurable time interval (in ms)
- the autosave is triggered when the content has changed during the set interval 
- in config.json
- `  "options" : {
    "editor": {
      "autosaveEnabled": true,
      "autosaveInterval": 120000
    }
  }`

## Motivation and Context
Users are used to autosaves of modern editors

### CODE REVIEW

**Comment by pascalwengerter** [comment]
@elizavetaRa could you add a changelog item (at least referencing this PR) and document your changes in https://owncloud.dev/clients/web/getting-started/#options (`/docs/getting-started.md` in the repo)? That'd be awesome!

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/32895/74/1
:boom: The oC10IntegrationApp1 tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/32895/68/1
:boom: The oCISSharingPublic1 tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/32895/67/1
:boom: The oCISSharingPerm2 tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/32895/70/1
:boom: The oCISSharingPublic3 tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/32895/69/1
:boom: The oCISSharingPublic2 tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/32895/71/1
:boom: The oCISUploadMove tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/32895/72/1
:boom: The oCISTrashbinJourney tests pipeline failed. The build has been cancelled.

**Comment by kulmann** [comment]
Superseded by https://github.com/owncloud/web/pull/8457

**Pull request closed without merging**
