### PR TITLE
[full-ci]Too long text breaks incorrectly

### PR DESCRIPTION
**Pull request by lookacat**
## Description
We've had an visual bug in the context menu that caused any text break to center the text,
which looked off and weird.
Is now fixed by text-align:left which causes the break part of the text to start at the same position
as the first part

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by fschade — APPROVED** [review]
LGTM 🎸

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic2</strong> https://drone.owncloud.com/owncloud/web/22971/68/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/22971/69/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic1</strong> https://drone.owncloud.com/owncloud/web/22971/67/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Pull request merged**
