### PR TITLE
[full-ci] Upgrade uppy and its packages to v3.0.0

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
We've upgraded Uppy and its packages to v3.0.1.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/7177

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

### CODE REVIEW

**Comment by JammingBen** [comment]
Currently blocked due to https://github.com/transloadit/uppy/issues/4041.

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/27967/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/27967/tracing/re-sharing-alice-2022-9-1-09-05-51.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/27967/tracing/re-sharing-brian-2022-9-1-09-05-59.zip 


</p></details>

**Review by kulmann — CHANGES_REQUESTED** [review]
When I do a folder upload via drag&drop it uploads the content of the folder, not the folder itself. Can you confirm that? Tested in chrome on macOS...

**Comment by kulmann** [comment]
> When I do a folder upload via drag&drop it uploads the content of the folder, not the folder itself. Can you confirm that? Tested in chrome on macOS...

Correction: it uploads all files flattened. Deep nested folder structure -> only the files get uploaded into the current folder.

**Review by kulmann — APPROVED** [review]
Works now 💪 🥳

**Pull request merged**
