### PR TITLE
Bump tus client lib

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Supersedes some stuck dependabot PRs, works towards #5371

### CODE REVIEW

**Comment by pascalwengerter** [comment]
Failing oc10 smoke test due to flakiness, worked fine locally. Restarting CI

**Comment by kulmann** [comment]
> Failing oc10 smoke test due to flakiness, worked fine locally. Restarting CI

🤔 oc10 doesn't support TUS.

**Comment by pascalwengerter** [comment]
> > Failing oc10 smoke test due to flakiness, worked fine locally. Restarting CI
> 
> thinking oc10 doesn't support TUS.

Shouldn't matter since the TUS library should detect this and act accordingly from my understanding? Smoke tests failed again though..

**Review by fschade — APPROVED** [review]
LGTM 🤖

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21380/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Pull request merged**
