### PR TITLE
[full-ci][tests-only] bump ocis commit id for the tests

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
Bump `ocis` commit id for tests

## Related Issue

- Part of https://github.com/owncloud/QA/issues/744
- Part of https://github.com/owncloud/QA/issues/747

## How Has This Been Tested?

- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPerm3</strong> https://drone.owncloud.com/owncloud/web/26283/66/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by kiranparajuli589** [comment]
> Results for **oCISSharingPerm3** https://drone.owncloud.com/owncloud/web/26283/66/1 boom The acceptance tests pipeline failed. The build has been cancelled.

a big list of tests started passing:
webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature:47
webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature:48
webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature:49
webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature:50
webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature:51
webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature:52
webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:53
webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:54
webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:55
webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:56
webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:57
webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:58
webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature:48
webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature:49
webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature:50
webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature:51
webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature:52
webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature:53

**Review by phil-davis — APPROVED** [review]
Looks great to have passing tests. Do we have a link to what improved in oCIS so that these tests are passing?

**Comment by kiranparajuli589** [comment]
There are some more:
webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature:60
webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature:61
webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature:62
webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature:63
webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature:64
webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature:65
webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature:54
webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature:55
webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature:56
webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature:57
webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature:58
webUISharingFolderPermissionsGroups/sharePermissionsGroup.feature:59

**Comment by kiranparajuli589** [comment]
An ocis bug demonstration scenario has also failed
https://drone.owncloud.com/owncloud/web/26287/64/16
```console
@skipOnOC10
  Scenario: Share a folder without share permissions using API and check if it is listed on the collaborators list for original owner (ocis bug demonstration) # features/webUISharingPermissionsUsers/sharePermissionsUsers.feature:169
- Connecting to selenium on port 4444...

 Error while running .locateMultipleElements() protocol action: Unknown command 404 Not Found

√ Element <.files-recipient-custom-permissions-drop> was not present after 102 milliseconds.
ℹ Connected to selenium on port 4444 (285ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server
    And the administrator has set the default folder for received shares to "Shares" in the server
    And these users have been created with default attributes and without skeleton files in the server:
      │ username │
      │ Alice    │
      │ Brian    │
    And user "Brian" has created folder "simple-folder" in the server
    And user "Brian" has created folder "simple-empty-folder" in the server
    And user "Brian" has created folder "simple-folder/simple-empty-folder" in the server
    And user "Brian" has uploaded file "data.zip" to "data.zip" in the server
    And user "Brian" has uploaded file "lorem.txt" to "lorem.txt" in the server
    And user "Brian" has uploaded file "lorem.txt" to "simple-folder/lorem.txt" in the server
    Given user "Brian" has shared folder "simple-folder" with user "Alice" with "read" permissions in the server
    And user "Alice" has accepted the share "Shares/simple-folder" offered by user "Brian" in the server
    And user "Brian" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 788 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 190 milliseconds.
√ Element <#files-view> was visible after 734 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 33 milliseconds.
    When the user opens the share dialog for folder "simple-folder" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 34 milliseconds.
waiting for 500ms ...
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-sharing-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 14 milliseconds.
    Then user "Alice Hansen" should be listed as "Viewer" in the collaborators list for folder "simple-folder" on the webUI
√ Element <//*[@id="sidebar-panel-sharing-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 11 milliseconds.
√ Element <#files-collaborators-list> was present after 18 milliseconds.
    ✖ failed
      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
      + actual - expected

      + 'Viewer'
      - 'Custom permissions'
          + expected - actual

          -Viewer
          +Custom permissions

          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/sharingContext.js:115:16
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    And no custom permissions should be set for collaborator "Alice Hansen" for folder "simple-folder" on the webUI
    - skipped
```

**Comment by kiranparajuli589** [comment]
There are more things to update in the expected failures list. I will follow up on this on coming Monday.

**Comment by pascalwengerter** [comment]
Please squash-on-merge 😇

**Pull request merged**
