### PR TITLE
[tests-only][full-ci]Remove function present in middleware from sharingHelper

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description
This PR removes functions present in middleware that are no longer needed in web

## Related Issue

- Part of https://github.com/owncloud/web/issues/6111

## How Has This Been Tested?

- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10Basic2</strong> https://drone.owncloud.com/owncloud/web/22141/13/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIWebdavLockProtection-delete_feature-L73.png
  

### webUIWebdavLockProtection-delete_feature-L74.png
  

### webUIWebdavLockProtection-move_feature-L123.png
  

### webUIWebdavLockProtection-move_feature-L124.png
  

### webUIWebdavLockProtection-move_feature-L146.png
  

### webUIWebdavLockProtection-move_feature-L147.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10FileOperations</strong> https://drone.owncloud.com/owncloud/web/22141/14/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUICreateFilesFolders-createFolders_feature-L59.png
  

### webUIDeleteFilesFolders-deleteFilesFolders_feature-L146.png
  

### webUIDeleteFilesFolders-deleteFilesFolders_feature-L167.png
  

### webUIDeleteFilesFolders-deleteFilesFolders_feature-L202.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Move</strong> https://drone.owncloud.com/owncloud/web/22141/21/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIMoveFilesFolders-moveFiles_feature-L85.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Files4</strong> https://drone.owncloud.com/owncloud/web/22141/19/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIPreview-imageMediaViewer_feature-L25.png
  

### webUIPreview-imageMediaViewer_feature-L35.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp2</strong> https://drone.owncloud.com/owncloud/web/22141/69/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicBasic-publicLinkCreate_feature-L11.png
  

### webUISharingPublicBasic-publicLinkCreate_feature-L28.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L33.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L34.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L35.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Files3</strong> https://drone.owncloud.com/owncloud/web/22141/18/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIRenameFiles-renameFiles_feature-L183.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublic2</strong> https://drone.owncloud.com/owncloud/web/22141/38/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L114.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L134.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L141.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L149.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L159.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L169.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L181.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L189.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L199.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L209.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L221.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L227.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L236.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L257.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L266.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L33.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L34.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L35.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L60.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L93.png
  

### webUISharingPublicManagement-publicLinkIndicator_feature-L98.png
  

### webUISharingPublicManagement-shareByPublicLink_feature-L12.png
  

### webUISharingPublicManagement-shareByPublicLink_feature-L152.png
  

### webUISharingPublicManagement-shareByPublicLink_feature-L159.png
  

### webUISharingPublicManagement-shareByPublicLink_feature-L19.png
  

### webUISharingPublicManagement-shareByPublicLink_feature-L25.png
  

### webUISharingPublicManagement-shareByPublicLink_feature-L90.png
  

### webUISharingPublicManagement-sharingPublicSession_feature-L10.png
  

### webUISharingPublicManagement-sharingPublicSession_feature-L20.png
  

### webUISharingPublicManagement-sharingPublicSession_feature-L28.png
  

### webUISharingPublicManagement-sharingPublicSession_feature-L35.png
  

### webUISharingPublicManagement-sharingPublicSession_feature-L48.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingPublic1</strong> https://drone.owncloud.com/owncloud/web/22141/37/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicBasic-publicLinkCreate_feature-L11.png
  

### webUISharingPublicBasic-publicLinkCreate_feature-L28.png
  

### webUISharingPublicBasic-publicLinkCreate_feature-L77.png
  

### webUISharingPublicBasic-publicLinkEdit_feature-L101.png
  

### webUISharingPublicBasic-publicLinkEdit_feature-L115.png
  

### webUISharingPublicBasic-publicLinkEdit_feature-L130.png
  

### webUISharingPublicBasic-publicLinkEdit_feature-L145.png
  

### webUISharingPublicBasic-publicLinkEdit_feature-L160.png
  

### webUISharingPublicBasic-publicLinkEdit_feature-L191.png
  

### webUISharingPublicBasic-publicLinkEdit_feature-L207.png
  

### webUISharingPublicBasic-publicLinkEdit_feature-L88.png
  

### webUISharingPublicBasic-publicLinkPublicActions_feature-L18.png
  

### webUISharingPublicBasic-publicLinkPublicActions_feature-L25.png
  

### webUISharingPublicBasic-publicLinkPublicActions_feature-L31.png
  

### webUISharingPublicBasic-publicLinkPublicActions_feature-L67.png
  

### webUISharingPublicBasic-publicLinkPublicActions_feature-L82.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/22141/16/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIFilesCopy-copy_feature-L76.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10Files2</strong> https://drone.owncloud.com/owncloud/web/22141/17/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIUpload-upload_feature-L152.png
  


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/22145/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Review by phil-davis — APPROVED** [review]
That's great to be able to delete all that old code, and still CI passes.

**Pull request merged**
