### PR TITLE
Fix: do not reset file selection in batch actions

### PR DESCRIPTION
**Pull request by LukasHirt**

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUINotificationBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUINotifications-displayNotificationsOnWebUI-feature-18.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>TrashbinDelete</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUITrashbinDelete-trashbinDelete-feature-113.png
  

### webUITrashbinDelete-trashbinDelete-feature-29.png
  

### webUITrashbinDelete-trashbinDelete-feature-42.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>MarkdownEditor</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUIMarkdownEditor-markdownFile-feature-62.png
  

### webUIMarkdownEditor-markdownFile-feature-63.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersExpire</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-240.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>TrashbinFilesFolders</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUITrashbinFilesFolders-trashbinFilesFolders-feature-23.png
  

### webUITrashbinFilesFolders-trashbinFilesFolders-feature-38.png
  

### webUITrashbinFilesFolders-trashbinFilesFolders-feature-82.png
  

### webUITrashbinFilesFolders-trashbinFilesFolders-feature-97.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersExpireToRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingInternalUsersExpireToRoot-shareWithUsersExpiringShares-feature-232.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublicExpire</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-106.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-11.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-147.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-24.png
  

### webUISharingPublicExpire-shareByPublicLinkExpiringLinks-feature-86.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublicDifferentRoles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-114.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-93.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Upload</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUIUpload-upload-feature-130.png
  

### webUIUpload-upload-feature-151.png
  

### webUIUpload-upload-feature-89.png
  

### webUIUpload-upload-feature-98.png
  

### webUIUpload-uploadEdgecases-feature-109.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsersRoot2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-109.png
  

### webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-26.png
  

### webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-79.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>oc10-integration-notifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingNotifications-shareWithUsers-feature-21.png
  

### webUISharingNotifications-shareWithUsers-feature-32.png
  

### webUISharingNotifications-shareWithUsers-feature-40.png
  

### webUISharingNotifications-shareWithUsers-feature-53.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-19.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-31.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-40.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-53.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>TrashbinRestore</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUITrashbinRestore-trashbinRestore-feature-138.png
  

### webUITrashbinRestore-trashbinRestore-feature-14.png
  

### webUITrashbinRestore-trashbinRestore-feature-181.png
  

### webUITrashbinRestore-trashbinRestore-feature-222.png
  

### webUITrashbinRestore-trashbinRestore-feature-241.png
  

### webUITrashbinRestore-trashbinRestore-feature-260.png
  

### webUITrashbinRestore-trashbinRestore-feature-30.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublicManagement</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingPublicManagement-publicLinkIndicator-feature-110.png
  

### webUISharingPublicManagement-shareByPublicLink-feature-102.png
  

### webUISharingPublicManagement-shareByPublicLink-feature-12.png
  

### webUISharingPublicManagement-shareByPublicLink-feature-201.png
  

### webUISharingPublicManagement-shareByPublicLink-feature-64.png
  

### webUISharingPublicManagement-shareByPublicLink-feature-90.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingInternalGroups-shareWithGroups-feature-100.png
  

### webUISharingInternalGroups-shareWithGroups-feature-260.png
  

### webUISharingInternalGroups-shareWithGroups-feature-72.png
  

### webUISharingInternalGroups-shareWithGroups-feature-73.png
  

### webUISharingInternalGroups-shareWithGroups-feature-74.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUIFilesList-fileList-feature-46.png
  

### webUIFilesList-sort-feature-51.png
  

### webUIFilesList-sort-feature-72.png
  

### webUIFilesSearch-search-feature-122.png
  

### webUIFilesSearch-search-feature-175.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsersRoot1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingInternalUsersToRoot-shareWithUsers-feature-103.png
  

### webUISharingInternalUsersToRoot-shareWithUsers-feature-275.png
  

### webUISharingInternalUsersToRoot-shareWithUsers-feature-57.png
  

### webUISharingInternalUsersToRoot-shareWithUsers-feature-74.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUIFavorites-favoritesFile-feature-110.png
  

### webUIFavorites-favoritesFile-feature-131.png
  

### webUIFavorites-favoritesFile-feature-14.png
  

### webUIFavorites-favoritesFile-feature-30.png
  

### webUIFavorites-favoritesFile-feature-85.png
  

### webUIFavorites-unfavoriteFile-feature-104.png
  

### webUIFavorites-unfavoriteFile-feature-13.png
  

### webUIFavorites-unfavoriteFile-feature-34.png
  

### webUIFavorites-unfavoriteFile-feature-55.png
  

### webUIFavorites-unfavoriteFile-feature-72.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingNotifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingNotifications-shareWithGroups-feature-24.png
  

### webUISharingNotifications-shareWithUsers-feature-21.png
  

### webUISharingNotifications-shareWithUsers-feature-32.png
  

### webUISharingNotifications-shareWithUsers-feature-40.png
  

### webUISharingNotifications-shareWithUsers-feature-53.png
  

### webUISharingNotificationsToRoot-shareWithGroups-feature-24.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-19.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-31.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-40.png
  

### webUISharingNotificationsToRoot-shareWithUsers-feature-53.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups-feature-128.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-234.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-69.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-70.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-71.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-74.png
  

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-95.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIDelete</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUIDeleteFilesFolders-deleteFilesFolders-feature-111.png
  

### webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png
  

### webUIDeleteFilesFolders-deleteFilesFolders-feature-122.png
  

### webUIDeleteFilesFolders-deleteFilesFolders-feature-159.png
  

### webUIDeleteFilesFolders-deleteFilesFolders-feature-180.png
  

### webUIDeleteFilesFolders-deleteFilesFolders-feature-235.png
  

### webUIDeleteFilesFolders-deleteFilesFolders-feature-249.png
  

### webUIDeleteFilesFolders-deleteFilesFolders-feature-295.png
  

### webUIDeleteFilesFolders-deleteFilesFolders-feature-308.png
  

### webUIDeleteFilesFolders-deleteFilesFolders-feature-53.png
  

### webUIDeleteFilesFolders-deleteFilesFolders-feature-54.png
  

### webUIDeleteFilesFolders-deleteFilesFolders-feature-55.png
  

### webUIDeleteFilesFolders-deleteFilesFolders-feature-56.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>IntegrationApp2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUIMoveFilesFolders-moveFiles-feature-20.png
  

### webUIMoveFilesFolders-moveFolders-feature-20.png
  

### webUITrashbinDelete-trashbinDelete-feature-29.png
  

### webUITrashbinFilesFolders-trashbinFilesFolders-feature-23.png
  

### webUITrashbinRestore-trashbinRestore-feature-14.png
  

### webUIUpload-upload-feature-89.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png
  

### webUIFavorites-favoritesFile-feature-14.png
  

### webUIFavorites-unfavoriteFile-feature-13.png
  

### webUIFavorites-unfavoriteFile-feature-55.png
  

### webUIFilesCopy-copy-feature-10.png
  

### webUIRenameFiles-renameFiles-feature-22.png
  

### webUIRenameFiles-renameFiles-feature-23.png
  

### webUIRenameFiles-renameFiles-feature-24.png
  

### webUIRenameFiles-renameFiles-feature-25.png
  

### webUIRenameFiles-renameFiles-feature-26.png
  

### webUIRenameFiles-renameFiles-feature-43.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-50.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-72.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIFiles1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUIFiles-download-feature-11.png
  

### webUIFiles-download-feature-24.png
  

### webUIFilesActionMenu-versions-feature-14.png
  

### webUIFilesCopy-copy-feature-10.png
  

### webUIFilesCopy-copy-feature-108.png
  

### webUIFilesCopy-copy-feature-116.png
  

### webUIFilesCopy-copy-feature-127.png
  

### webUIFilesCopy-copy-feature-26.png
  

### webUIFilesCopy-copy-feature-68.png
  

### webUIFilesCopy-copy-feature-69.png
  

### webUIFilesCopy-copy-feature-70.png
  

### webUIFilesCopy-copy-feature-71.png
  

### webUIFilesCopy-copy-feature-74.png
  

### webUIFilesCopy-copy-feature-87.png
  

### webUIFilesCopy-copy-feature-98.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUILogin-adminBlocksUser-feature-20.png
  

### webUIPreview-imageMediaViewer-feature-13.png
  

### webUIPreview-imageMediaViewer-feature-131.png
  

### webUIPreview-imageMediaViewer-feature-14.png
  

### webUIPreview-imageMediaViewer-feature-140.png
  

### webUIPreview-imageMediaViewer-feature-149.png
  

### webUIPreview-imageMediaViewer-feature-15.png
  

### webUIPreview-imageMediaViewer-feature-158.png
  

### webUIPreview-imageMediaViewer-feature-17.png
  

### webUIPreview-imageMediaViewer-feature-24.png
  

### webUIPreview-imageMediaViewer-feature-34.png
  

### webUIPreview-imageMediaViewer-feature-55.png
  

### webUIPreview-imageMediaViewer-feature-56.png
  

### webUIPreview-imageMediaViewer-feature-59.png
  

### webUIPreview-imageMediaViewer-feature-67.png
  

### webUIPreview-imageMediaViewer-feature-83.png
  

### webUIPreview-imageMediaViewer-feature-90.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsers</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingInternalUsers-shareWithUsers-feature-112.png
  

### webUISharingInternalUsers-shareWithUsers-feature-341.png
  

### webUISharingInternalUsers-shareWithUsers-feature-82.png
  

### webUISharingInternalUsersShareWithPage-shareWithUsers-feature-199.png
  

### webUISharingInternalUsersShareWithPage-shareWithUsers-feature-31.png
  

### webUISharingInternalUsersShareWithPage-shareWithUsers-feature-92.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Move</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUIMoveFilesFolders-moveFiles-feature-105.png
  

### webUIMoveFilesFolders-moveFiles-feature-12.png
  

### webUIMoveFilesFolders-moveFiles-feature-140.png
  

### webUIMoveFilesFolders-moveFiles-feature-20.png
  

### webUIMoveFilesFolders-moveFiles-feature-43.png
  

### webUIMoveFilesFolders-moveFiles-feature-79.png
  

### webUIMoveFilesFolders-moveFiles-feature-81.png
  

### webUIMoveFilesFolders-moveFiles-feature-82.png
  

### webUIMoveFilesFolders-moveFiles-feature-85.png
  

### webUIMoveFilesFolders-moveFiles-feature-97.png
  

### webUIMoveFilesFolders-moveFolders-feature-12.png
  

### webUIMoveFilesFolders-moveFolders-feature-20.png
  

### webUIMoveFilesFolders-moveFolders-feature-33.png
  

### webUIMoveFilesFolders-moveFolders-feature-66.png
  

### webUIMoveFilesFolders-moveFolders-feature-68.png
  

### webUIMoveFilesFolders-moveFolders-feature-69.png
  

### webUIMoveFilesFolders-moveFolders-feature-72.png
  

### webUIMoveFilesFolders-moveFolders-feature-81.png
  

### webUIMoveFilesFolders-moveFolders-feature-88.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublicBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingPublicBasic-publicLinkCreate-feature-102.png
  

### webUISharingPublicBasic-publicLinkCreate-feature-120.png
  

### webUISharingPublicBasic-publicLinkCreate-feature-138.png
  

### webUISharingPublicBasic-publicLinkCreate-feature-177.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-102.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-116.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-131.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-146.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-161.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-181.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-204.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-30.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-31.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-32.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-33.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-56.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-57.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-58.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-59.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-82.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-83.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-84.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-85.png
  

### webUISharingPublicBasic-publicLinkEdit-feature-88.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUISharingAcceptShares-acceptShares-feature-100.png
  

### webUISharingAcceptShares-acceptShares-feature-116.png
  

### webUISharingAcceptShares-acceptShares-feature-135.png
  

### webUISharingAcceptShares-acceptShares-feature-16.png
  

### webUISharingAcceptShares-acceptShares-feature-203.png
  

### webUISharingAcceptShares-acceptShares-feature-218.png
  

### webUISharingAcceptShares-acceptShares-feature-235.png
  

### webUISharingAcceptShares-acceptShares-feature-78.png
  

### webUISharingAcceptShares-acceptShares-feature-89.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-110.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-131.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-143.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-15.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-158.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-235.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-245.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-255.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-267.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-282.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-299.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-31.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-315.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-357.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-366.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-379.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-397.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-50.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-72.png
  

### webUISharingAcceptSharesToRoot-acceptShares-feature-90.png
  


</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRename</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15457/

<p>


### webUIRenameFiles-renameFiles-feature-117.png
  

### webUIRenameFiles-renameFiles-feature-118.png
  

### webUIRenameFiles-renameFiles-feature-119.png
  

### webUIRenameFiles-renameFiles-feature-138.png
  

### webUIRenameFiles-renameFiles-feature-139.png
  

### webUIRenameFiles-renameFiles-feature-143.png
  

### webUIRenameFiles-renameFiles-feature-151.png
  

### webUIRenameFiles-renameFiles-feature-157.png
  

### webUIRenameFiles-renameFiles-feature-163.png
  

### webUIRenameFiles-renameFiles-feature-169.png
  

### webUIRenameFiles-renameFiles-feature-176.png
  

### webUIRenameFiles-renameFiles-feature-186.png
  

### webUIRenameFiles-renameFiles-feature-202.png
  

### webUIRenameFiles-renameFiles-feature-22.png
  

### webUIRenameFiles-renameFiles-feature-227.png
  

### webUIRenameFiles-renameFiles-feature-23.png
  

### webUIRenameFiles-renameFiles-feature-24.png
  

### webUIRenameFiles-renameFiles-feature-249.png
  

### webUIRenameFiles-renameFiles-feature-25.png
  

### webUIRenameFiles-renameFiles-feature-26.png
  

### webUIRenameFiles-renameFiles-feature-260.png
  

### webUIRenameFiles-renameFiles-feature-38.png
  

### webUIRenameFiles-renameFiles-feature-39.png
  

### webUIRenameFiles-renameFiles-feature-40.png
  

### webUIRenameFiles-renameFiles-feature-43.png
  

### webUIRenameFiles-renameFiles-feature-62.png
  

### webUIRenameFiles-renameFiles-feature-77.png
  

### webUIRenameFiles-renameFiles-feature-90.png
  

### webUIRenameFiles-renameFilesInsideProblematicFolderName-feature-21.png
  

### webUIRenameFiles-renameFilesInsideProblematicFolderName-feature-22.png
  

### webUIRenameFiles-renameFilesInsideProblematicFolderName-feature-36.png
  

### webUIRenameFolders-renameFolders-feature-107.png
  

### webUIRenameFolders-renameFolders-feature-108.png
  

### webUIRenameFolders-renameFolders-feature-109.png
  

### webUIRenameFolders-renameFolders-feature-122.png
  

### webUIRenameFolders-renameFolders-feature-127.png
  

### webUIRenameFolders-renameFolders-feature-132.png
  

### webUIRenameFolders-renameFolders-feature-138.png
  

### webUIRenameFolders-renameFolders-feature-147.png
  

### webUIRenameFolders-renameFolders-feature-22.png
  

### webUIRenameFolders-renameFolders-feature-23.png
  

### webUIRenameFolders-renameFolders-feature-24.png
  

### webUIRenameFolders-renameFolders-feature-25.png
  

### webUIRenameFolders-renameFolders-feature-26.png
  

### webUIRenameFolders-renameFolders-feature-38.png
  

### webUIRenameFolders-renameFolders-feature-39.png
  

### webUIRenameFolders-renameFolders-feature-40.png
  

### webUIRenameFolders-renameFolders-feature-43.png
  

### webUIRenameFolders-renameFolders-feature-58.png
  

### webUIRenameFolders-renameFolders-feature-67.png
  

### webUIRenameFolders-renameFolders-feature-79.png
  


</p></details>

**Comment by LukasHirt** [comment]
@kulmann PR is basically ready for the delete modal but needs a decision if the same should happen also when cancelling location picker since that is a completely custom route...

**Review by kulmann — COMMENTED** [review]
needs a changelog, then it's good to go

**Review by pascalwengerter — APPROVED** [review]
LGTM 🎯

**Review by kulmann — APPROVED** [review]
👍

**Pull request merged**
