### PR TITLE
[tests-only] fix bash script for running acceptance tests

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Fix bash script for running the tests in CI

## Related Issue

- Fixes issue with waiting for the server in CI.

## Motivation and Context

the script doesnt works as expected currently and waits for 3 minutes regardless of weather the server has started or not.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/19197/12/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/19197/12/15
```
runsh: Total unexpected failed scenarios throughout the test run:
webUIFilesActionMenu/versions.feature:15
```

I guess this is one of the intermittent failing scenarios. I will restart.

**Comment by ownclouders** [comment]
Results for <strong>oCISRename</strong> https://drone.owncloud.com/owncloud/web/19198/49/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/19199/39/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:363

**Comment by ownclouders** [comment]
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/19199/12/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:36

**Pull request merged**
