### PR TITLE
[tests-only] [full-ci] Force some fails

### PR DESCRIPTION
**Pull request by phil-davis**
Force some test fails to check how they are reported back in GitHub comments.

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/15887/11/21
The fail got a 500 error when trying to post to GitHub:
`time="2021-06-02T08:32:50Z" level=fatal msg="POST https://api.github.com/repos/owncloud/web/issues/5187/comments: 500  []" `

But I am getting 500 errors in my browser for various GitHub stuff the last 30 minutes. So there might be a GitHub problem right now.

**Comment by kulmann** [comment]
> https://drone.owncloud.com/owncloud/web/15887/11/21
> The fail got a 500 error when trying to post to GitHub:
> `time="2021-06-02T08:32:50Z" level=fatal msg="POST https://api.github.com/repos/owncloud/web/issues/5187/comments: 500 []" `
> 
> But I am getting 500 errors in my browser for various GitHub stuff the last 30 minutes. So there might be a GitHub problem right now.

```
Update - API Requests is experiencing degraded performance. We are continuing to investigate.
Jun 2, 08:36 UTC
```
see https://www.githubstatus.com/

**Comment by xoxys** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15889/

<p>


### webUIAccount-accountInformation-feature-20.png
  

### webUILogin-adminBlocksUser-feature-20.png
  

### webUIPreview-imageMediaViewer-feature-140.png
  

### webUIPreview-imageMediaViewer-feature-158.png
  

### webUIPreview-imageMediaViewer-feature-83.png
  

### webUIPreview-imageMediaViewer-feature-90.png
  


</p></details>

**Comment by xoxys** [comment]
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15889/

<p>


### webUIFavorites-unfavoriteFile-feature-13.png
  


</p></details>

**Comment by phil-davis** [comment]
@xoxys what? How do the comments from drone CI end up with your GitHub name?

**Comment by xoxys** [comment]
I don't know that's what we are discussing already....

**Pull request closed without merging**
