### PR TITLE
remove node globals and buildins from build steps

### PR DESCRIPTION
**Pull request by fschade**
replace @erquhart/rollup-plugin-node-builtins and rollup-plugin-node-globals with rollup-plugin-polyfill-node which is maintained by the snowpackjs team.

This was needed because used rollup-plugin-node-builtins as a parsing dependency acorn which was error prone

### CODE REVIEW

**Review by pascalwengerter — APPROVED** [review]
Happy if CI is happy

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/22048/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-40-27-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-40-44-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-41-23-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-41-29-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-42-07-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-42-13-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-42-51-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-42-57-Brian.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/22048/10/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-42-43-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-43-05-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-43-49-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-43-57-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-44-40-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-44-49-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-45-32-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22048/2022-1-20-11-45-41-Brian.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/22058/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-01-58-51-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-01-59-07-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-01-59-45-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-01-59-51-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-02-00-27-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-02-00-33-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-02-01-10-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-02-01-17-Brian.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/22058/10/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-02-00-26-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-02-00-44-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-02-01-27-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-02-01-34-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-02-02-44-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-02-02-51-Brian.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-02-03-33-Alice.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22058/2022-1-20-02-03-41-Brian.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingAndUpload</strong> https://drone.owncloud.com/owncloud/web/22063/63/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ScharfViktor** [comment]
e2e tests are green)) 
all the tests failed in one place. it doesn't look like flaky. there was a strange error. Button "download" was clicked, but it would not downloading.

**Comment by fschade** [comment]
> e2e tests are green)) all the tests failed in one place. it doesn't look like flaky. there was a strange error. Button "download" was clicked, but it would not downloading.

Thanks, yup.

We need to see if it really works. We were forced to use another node polyfilling library.
Sadly the new lib dos not have crypto support right now (https://github.com/snowpackjs/rollup-plugin-polyfill-node/blob/11da30d82b79bf0b15c8ae5ed11eadb09c0ff5be/src/modules.ts#L41) and we had to add it on our own.

Lets see if it works as expected

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingAndUpload</strong> https://drone.owncloud.com/owncloud/web/22064/63/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10iPhone2</strong> https://drone.owncloud.com/owncloud/web/22065/48/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10iPhone3</strong> https://drone.owncloud.com/owncloud/web/22065/49/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10iPhoneNotifications</strong> https://drone.owncloud.com/owncloud/web/22065/46/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Sharing1</strong> https://drone.owncloud.com/owncloud/web/22065/23/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Files5</strong> https://drone.owncloud.com/owncloud/web/22065/20/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10Resharing</strong> https://drone.owncloud.com/owncloud/web/22065/22/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/22066/41/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:111

**Pull request merged**
