### PR TITLE
Clear files searched in spaces overview

### PR DESCRIPTION
**Pull request by JanAckermann**
## Description
We've fixed a bug where searching for a file in the search bar messes up the spaces overview and instead of listing
the spaces, and found files according to the search term were shown.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/6995

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by pascalwengerter — APPROVED** [review]
Couldn't reproduce on master but code LGTM

**Comment by JanAckermann** [comment]
@pascalwengerter 
1. Create a file name test.txt
2. Search for file in “current folder” search instead of “all files”
3. Hit enter to see the files list
4. Head over to spaces 


For me reproducible

**Comment by pascalwengerter** [comment]
> @pascalwengerter
> 
>     1. Create a file name test.txt
> 
>     2. Search for file in “current folder” search instead of “all files”
> 
>     3. Hit enter to see the files list
> 
>     4. Head over to spaces
> 
> 
> For me reproducible

Oh good read it wrong then, was checking the "real search"

**Comment by JanAckermann** [comment]
@pascalwengerter can you force merge ? Liscence check is broken

**Comment by pascalwengerter** [comment]
> @pascalwengerter can you force merge ? Liscence check is broken

Nope, but I can re-run the check 😎 please squash-merge later

**Pull request merged**
