### PR TITLE
[tests-only] Test failing acceptance test 20210622

### PR DESCRIPTION
**Pull request by phil-davis**

### CODE REVIEW

**Comment by ownclouders** [comment]
<summary>:boom: Acceptance tests <strong>oCISFiles1</strong> failed. The build is cancelled...</summary>

https://drone.owncloud.com/owncloud/web/16696/

**Comment by ownclouders** [comment]
<summary>:boom: Acceptance tests <strong>oCISSharingPermissions1</strong> failed. The build is cancelled...</summary>

https://drone.owncloud.com/owncloud/web/16696/

**Comment by ownclouders** [comment]
<summary>:boom: Acceptance tests <strong>oCISSharingPermissions2</strong> failed. The build is cancelled...</summary>

https://drone.owncloud.com/owncloud/web/16696/

**Comment by ownclouders** [comment]
<summary>:boom: Acceptance tests <strong>oCISSharingPermissions3</strong> failed. The build is cancelled...</summary>

https://drone.owncloud.com/owncloud/web/16696/

**Comment by ownclouders** [comment]
<summary>:boom: Acceptance tests <strong>oCISTrashbinUploadMoveJourney</strong> failed. The build is cancelled...</summary>

https://drone.owncloud.com/owncloud/web/16696/

**Comment by ownclouders** [comment]
<summary>:boom: Acceptance tests <strong>oCISSharingPublic</strong> failed. The build is cancelled...</summary>

https://drone.owncloud.com/owncloud/web/16704//58

**Comment by ownclouders** [comment]
<summary>:boom: Acceptance tests <strong>oC10Basic</strong> failed. The build is cancelled...</summary>

https://drone.owncloud.com/owncloud/web/16706/6/1

**Comment by phil-davis** [comment]
> boom Acceptance tests **oC10Basic** failed. The build is cancelled...
> 
> https://drone.owncloud.com/owncloud/web/16706/6/1

That link works nicely to take you to the drone pipeline stage that failed.

**Pull request closed without merging**
