### PR TITLE
Show search button in search bar

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
Show search button in search bar to make it a11y compliant.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Visual regression tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14848/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14848/

<p>









</p></details>

**Review by pascalwengerter — CHANGES_REQUESTED** [review]
Did you discuss this further somewhere outside of Confluence? The way I understood it the button could/should only be visually hidden as long as there's no input in the search field and then appear as soon as `input.length() > 0` or sth

In any case you may want to delete the example for the `Search example with visually hidden button` and make sure linter & tests are happy 🤓

**Comment by JammingBen** [comment]
> Did you discuss this further somewhere outside of Confluence? The way I understood it the button could/should only be visually hidden as long as there's no input in the search field and then appear as soon as input.length() > 0 or sth

Ahh okay. I only worked with the infos in Confluence, which basically state that the button should be "invisible" for screen readers only. I mean, it's not on me to decide, but buttons which suddenly (dis-)appear based the on input... Sure you want to go this way? :D

**Comment by pascalwengerter** [comment]
> > Did you discuss this further somewhere outside of Confluence? The way I understood it the button could/should only be visually hidden as long as there's no input in the search field and then appear as soon as input.length() > 0 or sth
> 
> Ahh okay. I only worked with the infos in Confluence, which basically state that the button should be "invisible" for screen readers only. I mean, it's not on me to decide, but buttons which suddenly (dis-)appear based the on input... Sure you want to go this way? :D

Same reservations from my side on this, let me summon @tbsbdr & @kulmann on this and let them decide?

**Comment by pascalwengerter** [comment]
> Did you discuss this further somewhere outside of Confluence? The way I understood it the button could/should only be visually hidden as long as there's no input in the search field and then appear as soon as `input.length() > 0` or sth
> 
> In any case you may want to delete the example for the `Search example with visually hidden button` and make sure linter & tests are happy 🤓

Forget about the example stuff, thought we're inside ODS but this is web, after all...

**Comment by ownclouders** [comment]
<details><summary>:boom: Visual regression tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14867/

<p>


Diff Image: </br>

Actual Image: </br>

Comparing Against: </br>


</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14867/

<p>









</p></details>

**Comment by JammingBen** [comment]
@individual-it Do you have an idea why the tests fail here?

>  Visual regression tests webUIFiles2 failed. Please find the screenshots inside ...

I updated the screenshot, but the test still fails.

> Acceptance tests webUIFiles2 failed. Please find the screenshots inside ...

Drone complains about failing tests related to sorting, which is not part of this PR at all.

**Comment by individual-it** [comment]
@JammingBen let me look into the updated screenshot, the other failures in the github comment are IMO a bug in the script that uploads the screenshot see https://github.com/owncloud/web/issues/4869

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14897/

<p>









</p></details>

**Comment by individual-it** [comment]
@JammingBen I've updated the screenshot, please rebase on master, that should make more tests green

**Comment by JammingBen** [comment]
Awesome, thanks!

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14903/

<p>








</p></details>

**Review by pascalwengerter — APPROVED** [review]
LGTM!

**Pull request merged**
