### PR TITLE
[tests-only][full-ci] trigger CI

### PR DESCRIPTION
**Pull request by phil-davis**
to see exactly what is currently failing.

To know what PR #6072 needs to fix, and...

### CODE REVIEW

**Comment by phil-davis** [comment]
The test fails are very similar to those reported in issue #6071 - that's good to know.

**Comment by phil-davis** [comment]
I reopened and restarted CI.

The smoke tests failed in #6072 so I need to see if they will fail in this test PR directly branched off master.

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/20568/16/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by phil-davis** [comment]
I rebased. The acceptance tests have been fixed. There may be an intermittent problem with the smoke tests. Let's see.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/20575/10/16
smoke-tests ran 10 times and passed every time. I don't know why they were failing a lot yesterday on oC10.
I will close this and open again if failures are noticed.

**Pull request closed without merging**
