### PR TITLE
Fix-8008: Don't open sharing sidebar after creating/copying quicklink

### LINKED ISSUE #8008: Fileslist: Don't open sidebar if you copy the quicklink
### Steps to reproduce
1. Open the fileslist
2. click on the "copy quicklink" icon of a file
3. quicklink gets copied
4. right sidebar opens

### Expected behaviour
just copy the link
- Don't open right sidebar if you copy the quicklink
- Don't switch to the shares panel if right sidebar is already open

### Actual behaviour
- right sidebar opens

### Background & reasoning
IIRC the idea was to present the quicklink upfront as soon as it got generated & copied in the right sidebar.
My observation is, that users are primarily confused why the right sidebar opens and often check, if they need to do somethiing else in the right sidebar which is counterproductive to the idea of getting the link really quick.

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Green unit tests, let's see how tightly e2e/acceptance tests are woven into this

## Related Issue
- Fixes #8008

### CODE REVIEW

**Review by kulmann — APPROVED** [review]
Nice, thank you! Could you please rebase this PR to current master? The sidebar panel ids have been renamed, so this PR has conflicting files. ;-)

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingIntGroupsToRoot</strong> https://drone.owncloud.com/owncloud/web/30253/26/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups_feature-L203.png
  


</p></details>
:boom: The oC10SharingIntGroupsToRoot tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
> Results for **oC10SharingIntGroupsToRoot** https://drone.owncloud.com/owncloud/web/30253/26/1
> 💥 The acceptance tests failed on retry. Please find the screenshots inside ...
> 
> ### webUISharingInternalGroupsToRoot-shareWithGroups_feature-L203.png
> 
> 
> 
> 💥 The oC10SharingIntGroupsToRoot tests pipeline failed. The build has been cancelled.

Looking  at `webUISharingInternalGroupsToRoot/shareWithGroups.feature:203` this looks unrelated to the changes from the PR, possibly a date issue? Re-running the test suite...

**Comment by JammingBen** [comment]
@pascalwengerter The pipeline on master has been fixed, another rebase and your PR should be good to go 👍

**Comment by pascalwengerter** [comment]
> @pascalwengerter The pipeline on master has been fixed, another rebase and your PR should be good to go 👍

Thanks for the reminder (and fix!), done

**Pull request merged**
