### PR TITLE
Enable command shortcuts on text-editor

### LINKED ISSUE #11326: No undo operation using keyboard shortcut (cmd+z) in text editor
```
ocis 6.1.0+4b8acf7e4

web 10.0.0
```

Steps: 
- create .txt file or .md file
- add content and try to undo change using keyboard shortcut (cmd+z)

Expected: works
Actual: doesn't work

https://github.com/user-attachments/assets/54866118-22bc-4ef8-b8df-fd9084f2411c

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Related Issue

- Fixes #11326 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by AlexAndBear** [comment]
I don't remember why we disabled the command shortcuts...
any idea?

**Review by JammingBen — APPROVED** [review]
> I don't remember why we disabled the command shortcuts...
> any idea?

I don't have one 🤷 Tested the other shortcuts as well, things are still working -> LGTM

**Comment by AlexAndBear** [comment]
@ScharfViktor can you maybe check as well, hopefully we don't miss something

**Comment by ScharfViktor** [comment]
> @ScharfViktor can you maybe check as well, hopefully we don't miss something

sure, I'll test

**Comment by ScharfViktor** [comment]
I don't know how deep should we test shortcut but cmd+z works fine how base shortcut operation

cmd+S - should save md file -> but it save file and add `~~~~` to the end of context
cmd+K (insert link) - doesn't work

**Comment by AlexAndBear** [comment]
> cmd+S - should save md file -> but it save file and add ~~~~ to the end of context
Oh yes :/ this was the issue

**Comment by AlexAndBear** [comment]
Found a proper solution please re check and re review @ScharfViktor @JammingBen

**Pull request merged**
