### PR TITLE
Space role manager: Fix description wording

### PR DESCRIPTION
**Pull request by lookacat**
## Description
See https://github.com/owncloud/web/issues/8162

## Related Issue

- Fixes https://github.com/owncloud/web/issues/8162

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/35197/70/1
:boom: The oC10IntegrationApp1 tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/35197/68/1
:boom: The oCISUploadMove tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/35197/69/1
:boom: The oCISTrashbinJourney tests pipeline failed. The build has been cancelled.

**Comment by JammingBen** [comment]
I'm confused - have you seen https://github.com/owncloud/web/pull/8916#issuecomment-1523244102?

**Comment by lookacat** [comment]
huh okay didn't see that comment, then i think we can close this

**Pull request closed without merging**
