### PR TITLE
add dark ownCloud logo

### PR DESCRIPTION
**Pull request by hurradieweltgehtunter**
## Description
Add dark ownCloud logo

## Related Issue
- Fixes https://github.com/owncloud/web/issues/8425

## Screenshots (if appropriate):
grafik

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

### CODE REVIEW

**Review by kulmann — COMMENTED** [review]
Could you please change the file reference for the logo in the `common` section of the default theme to this file? That way the other clients can pick up this new variant of the logo.

here:
https://github.com/owncloud/web/blob/master/packages/web-runtime/themes/owncloud/theme.json#L5

**Comment by hurradieweltgehtunter** [comment]
> Could you please change the file reference for the logo in the `common` section of the default theme to this file? That way the other clients can pick up this new variant of the logo.
> 
> here: https://github.com/owncloud/web/blob/master/packages/web-runtime/themes/owncloud/theme.json#L5

The purpose of this PR is to just provide a dark logo, so one could use it if needed. I'm not sure if we should change the default one.
Let's wait for #8425 if this idea is even suitable.

**Review by kulmann — APPROVED** [review]
👍

**Comment by kulmann** [comment]
> The purpose of this PR is to just provide a dark logo, so one could use it if needed. I'm not sure if we should change the default one. Let's wait for #8425 if this idea is even suitable.

Yes, makes sense. Then let's get this merged.

**Pull request merged**
