### PR TITLE
[CI] start acceptance tests only after unit and integration tests are complete

### PR DESCRIPTION
**Pull request by dpakach**
… complete

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by pascalwengerter** [comment]
@dpakach as before, please kill builds once the acceptance tests start when they shouldn't to reduce CI load😉

**Comment by dpakach** [comment]
@pascalwengerter, I just wanted to check that that builds start as expected.
A lot of times we also create PR with only acceptance tests change where the chances of unit tests failing are highly unlikely. So I thought we could start the acceptance tests and unit tests at the same time in such case. looks like it works as expected.

Another thing is that for unit tests there is a `build-web` step. We dont really need to build it just for running unit tests . Maybe we can remove that to make the unit tests pipeline a bit faster..

**Comment by phil-davis** [comment]
> Another thing is that for unit tests there is a build-web step. We don't really need to build it just for running unit tests . Maybe we can remove that to make the unit tests pipeline a bit faster.

That took 89 seconds. If we don't use it for unit/integration tests then there is no point running the step there.

sonarcloud takes about 2 minutes. Waiting for that delays the start of acceptance tests. 

Note: I will be optimizing the npm-install stuff next, so I could also look at making the start of acceptance tests not depend on waiting for sonarcloud.

**Review by phil-davis — APPROVED** [review]
This looks OK to me - it does what is required in the issue.

@pascalwengerter do we merge this, and then we (I) look at optimizations when I split out the npm-install stuff?

**Comment by pascalwengerter** [comment]
> > Another thing is that for unit tests there is a build-web step. We don't really need to build it just for running unit tests . Maybe we can remove that to make the unit tests pipeline a bit faster.
> 
> That took 89 seconds. If we don't use it for unit/integration tests then there is no point running the step there.
> 
> sonarcloud takes about 2 minutes. Waiting for that delays the start of acceptance tests.
> 
> Note: I will be optimizing the npm-install stuff next, so I could also look at making the start of acceptance tests not depend on waiting for sonarcloud.

Actually I think it's fine if acceptance tests don't run if sonarcloud is unhappy. @kulmann opinions?

**Comment by pascalwengerter** [comment]
> This looks OK to me - it does what is required in the issue.
> 
> @pascalwengerter do we merge this, and then we (I) look at optimizations when I split out the npm-install stuff?

Yes please. Let the CI stop if unit/integration tests fail is awesome, and you taking care of the npm-install stuff next is 🥇

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/16832/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Pull request merged**
