### PR TITLE
[Tests-Only] Split webUiSharingPublic suite into smaller suites

### PR DESCRIPTION
**Pull request by saw-jan**
## Description
move some of the `webUISharingPublic` feature files into a separate suite folder
- webUISharingPublicBasic
- webUISharingPublicManagement

## Related Issue
https://github.com/owncloud/web/issues/4876

## How Has This Been Tested?
- test environment:

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRootSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14013/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Move</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14069/

<p>













































</p></details>

**Comment by kiranparajuli589** [comment]
there are some unexpected passed scenarios https://drone.owncloud.com/owncloud/web/14136/80/11
maybe shouldn't be added as expected failures.

**Review by dpakach — COMMENTED** [review]
lgtm 👍🏼

**Review by swoichha — COMMENTED** [review]
LGTM

**Review by kiranparajuli589 — COMMENTED** [review]
lgtm 👍🏼

**Review by individual-it — APPROVED** [review]

**Pull request merged**
