### PR TITLE
[full-ci] [tests-only] Split "Basic" pipelines to reduce CI time

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) Delete webUIAdminSettings test suite (those scenarios will not be implemented directly in web)
2) Split out Webdav Lock test suites into separate pipelines

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17139/47/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by phil-davis** [comment]
oC10Basic-chrome is still 43 minutes. I will split it...

**Review by individual-it — APPROVED** [review]
if the admin setting will not be implemented, that decision should be documented in https://github.com/owncloud/web/issues/5015 and the issue should be closed

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17143/49/1
The following scenarios passed on retry:
- webUIRestrictSharing/restrictSharing.feature:49

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/17143 oC10Locks is the longest at 28 minutes.

**Pull request merged**
