### PR TITLE
[full-ci] [tests-only] test against oc10.9.0-beta1

### PR DESCRIPTION
**Pull request by kulmann**
This PR is an early check for compatibility with ownCloud server 10.9. Never to be merged, hence only a draft. Can be closed and the branch deleted after the results are documented / investigated.

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/20496
`bool value is not iterable`

**Comment by phil-davis** [comment]
The tarball is https://download.owncloud.org/community/testing/owncloud-10.9.0beta1.tar.bz2

"10.9.0beta1" (no "-")

**Comment by phil-davis** [comment]
Passes :100:

**Comment by kulmann** [comment]
thanks for taking care @phil-davis :heart: closing this PR now, since it was only meant for compatibility testing.

**Pull request closed without merging**
