### PR TITLE
Replace filter-obj dep with lodash-es function

### PR DESCRIPTION
**Pull request by pascalwengerter**
Supersedes #6197 by replacing the dependency alltogether

### CODE REVIEW

**Review by kulmann — APPROVED** [review]
Nice spot 😎

**Comment by pascalwengerter** [comment]
> Nice spot 😎 

Thanks for the quick review! Thinking about it, why is actions an object of objects and not an array of action objects to begin with? 🤔

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21945/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by kulmann** [comment]
> > Nice spot 😎
> 
> Thanks for the quick review! Thinking about it, why is actions an object of objects and not an array of action objects to begin with? 🤔

Because we reference the quick actions by their names in other parts of the source code. And the quick actions themselves are objects because they're simple key-value-data.

**Comment by pascalwengerter** [comment]
> > > Nice spot sunglasses
> > 
> > 
> > Thanks for the quick review! Thinking about it, why is actions an object of objects and not an array of action objects to begin with? thinking
> 
> Because we reference the quick actions by their names in other parts of the source code. And the quick actions themselves are objects because they're simple key-value-data.

Yeah I took another look this morning, should be fine ;) an array would be nicer to filter (since the underlying key-value-data is pretty uniform) but then we loose the reference-by-name part...

**Comment by kulmann** [comment]
> Yeah I took another look this morning, should be fine ;) an array would be nicer to filter (since the underlying key-value-data is pretty uniform) but then we loose the reference-by-name part...

You could use `Object.values()` and filter the resulting array.

**Pull request merged**
