### PR TITLE
[Tests-Only][Not-For-Merge] Bug reproduction of issue #4795

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
As stated in the issue linked, the server and client had to be running on different domains which is perfectly replecated on drone pipelines.
As owncloud-core and web are running on different they should be running on different host network and the bug is reproduced i.e user session of a blocked user is not cleared properly.

## Related Issue
- Part of #4743
- Part of #4795 

## Motivation and Context
Scenario webUILogin/adminBlocksUser.feature:20 behaves differently on CI than locally, that needs to be investigated and removed from expected failure file

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- :robot:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Login1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13320/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Login1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13322/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Login1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13378/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Login1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13380/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Login1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13394/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Login1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13396/

<p>













</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Login1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13397/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Login1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13399/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Login1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13400/

<p>





</p></details>

**Comment by kiranparajuli589** [comment]
Closing as its purpose has been made.

**Pull request closed without merging**
